// Short, factual answers about Ramayanam, Mahabharatham and Puranam characters and events.
// The long daily-reading series lives in shared/ithihasa/* (screen 'ithihasa'); these are quick look-ups.
import { B } from './common.js';

const C = (id, epic, en, ta, aliases, who, story, lesson, related = []) => ({
  id: `char-${id}`, kind: 'character', epic, names: B(en, ta), aliases,
  who: B(who[0], who[1]), story: B(story[0], story[1]), lesson: B(lesson[0], lesson[1]), related: related.map((r) => `char-${r}`),
});

export const CHARACTERS = [
  // ------------------------------------------------------------ Ramayanam
  C('rama', 'ramayanam', 'Rama', 'ராமர்', ['rama', 'raman', 'sri rama', 'ramar', 'ராமன்', 'ராமர்', 'ஸ்ரீ ராமர்'],
    ['Eldest son of King Dasaratha of Ayodhya and Kausalya; the seventh avatar of Vishnu and hero of the Ramayanam.', 'அயோத்தி மன்னன் தசரதன்-கௌசல்யையின் மூத்த மகன்; திருமாலின் ஏழாவது அவதாரம், இராமாயண நாயகன்.'],
    ['To keep his father’s word he went to the forest for 14 years with Sita and Lakshmana. When Ravana carried Sita away, he allied with Sugriva and Hanuman, built a bridge to Lanka, defeated Ravana and returned to rule Ayodhya (Rama Rajyam).', 'தந்தையின் வாக்கைக் காக்கச் சீதை, லட்சுமணனுடன் 14 ஆண்டு வனவாசம் சென்றார். ராவணன் சீதையைக் கவர்ந்து செல்ல, சுக்ரீவன், அனுமனுடன் நட்புக் கொண்டு, இலங்கைக்குப் பாலம் கட்டி, ராவணனை வென்று அயோத்தி திரும்பி ஆண்டார் (ராம ராஜ்யம்).'],
    ['Truth, keeping one’s word and fairness even to opponents.', 'சத்தியம், சொன்ன சொல் காத்தல், எதிரிக்கும் நியாயம்.'], ['sita', 'lakshmana', 'hanuman']),
  C('sita', 'ramayanam', 'Sita', 'சீதை', ['sita', 'seetha', 'seethai', 'janaki', 'vaidehi', 'சீதை', 'சீதா', 'ஜானகி', 'வைதேகி'],
    ['Daughter of King Janaka of Mithila, found in a furrow of the earth; Rama’s wife, revered as Lakshmi.', 'மிதிலை மன்னன் ஜனகன் நிலத்தை உழும்போது கிடைத்த மகள்; ராமரின் மனைவி, லட்சுமியாகப் போற்றப்படுபவள்.'],
    ['She married Rama after he lifted and broke Shiva’s bow, chose to follow him to the forest, was carried to Lanka by Ravana and held in the Ashoka grove, refusing all threats, until Rama’s victory.', 'சிவ தனுசை ராமர் உடைத்ததும் அவரை மணந்தாள்; தானே வனவாசம் உடன் சென்றாள்; ராவணனால் இலங்கைக்குக் கவரப்பட்டு அசோக வனத்தில் எல்லா மிரட்டலையும் மறுத்து, ராமரின் வெற்றி வரை உறுதியாக இருந்தாள்.'],
    ['Inner strength, dignity and steadfastness.', 'உள் வலிமை, கண்ணியம், உறுதி.'], ['rama', 'ravana', 'hanuman']),
  C('lakshmana', 'ramayanam', 'Lakshmana', 'லட்சுமணன்', ['lakshmana', 'lakshmanan', 'latchumanan', 'லட்சுமணன்', 'இலக்குவன்'],
    ['Son of Dasaratha and Sumitra; Rama’s devoted younger brother, seen as an aspect of Adisesha.', 'தசரதன்-சுமித்திரையின் மகன்; ராமரின் பாசமிகு தம்பி, ஆதிசேஷனின் அம்சம்.'],
    ['He left palace comforts to serve Rama and Sita through the 14 years in the forest, guarding them day and night, and fought Indrajit in the Lanka war.', 'அரண்மனை வசதிகளை விட்டு 14 ஆண்டும் ராமர்-சீதைக்குப் பணிவிடை செய்து இரவு பகலாகக் காத்தான்; இலங்கைப் போரில் இந்திரஜித்தை வென்றான்.'],
    ['Loyal, selfless service to family.', 'குடும்பத்துக்குத் தன்னலமற்ற விசுவாசப் பணி.'], ['rama', 'urmila']),
  C('urmila', 'ramayanam', 'Urmila', 'ஊர்மிளை', ['urmila', 'urmilai', 'ஊர்மிளை'],
    ['Sita’s sister and Lakshmana’s wife.', 'சீதையின் தங்கை, லட்சுமணனின் மனைவி.'],
    ['She stayed back in Ayodhya for 14 years so Lakshmana could serve Rama; tradition says she took on his sleep so he could stay awake guarding them.', 'லட்சுமணன் ராமருக்குப் பணிவிடை செய்ய 14 ஆண்டு அயோத்தியில் தங்கினாள்; அவன் விழித்திருந்து காக்க, அவன் உறக்கத்தைத் தானே ஏற்றாள் என்பது மரபு.'],
    ['Quiet sacrifice is also greatness.', 'அமைதியான தியாகமும் பெருமையே.'], ['lakshmana']),
  C('bharata', 'ramayanam', 'Bharata', 'பரதன்', ['bharata', 'bharathan', 'bharatan', 'பரதன்'],
    ['Son of Dasaratha and Kaikeyi.', 'தசரதன்-கைகேயியின் மகன்.'],
    ['Though the throne was given to him, he refused it, went to the forest to bring Rama back, and when Rama would not return, ruled for 14 years with Rama’s padukas (sandals) on the throne, living simply at Nandigram.', 'அரியணை தனக்குக் கொடுக்கப்பட்டும் மறுத்து, ராமரை அழைத்து வரக் காட்டுக்குச் சென்றான்; ராமர் வர மறுக்க, அவர் பாதுகைகளை அரியணையில் வைத்து நந்திகிராமத்தில் எளிமையாக வாழ்ந்து 14 ஆண்டு ஆண்டான்.'],
    ['Power held as a trust, not a prize.', 'அதிகாரம் பரிசு அல்ல, ஒப்படைப்பு.'], ['rama', 'kaikeyi']),
  C('shatrughna', 'ramayanam', 'Shatrughna', 'சத்ருக்னன்', ['shatrughna', 'sathrugnan', 'சத்ருக்னன்'],
    ['Youngest son of Dasaratha and Sumitra; Bharata’s companion.', 'தசரதன்-சுமித்திரையின் இளைய மகன்; பரதனின் துணை.'],
    ['He stood with Bharata in Ayodhya and later defeated the asura Lavana and founded Mathura.', 'அயோத்தியில் பரதனுடன் நின்றான்; பின்னர் லவணாசுரனை வென்று மதுராவை நிறுவினான்.'],
    ['Steady support behind the scenes.', 'பின்னணியில் உறுதியான துணை.'], ['bharata']),
  C('dasaratha', 'ramayanam', 'Dasaratha', 'தசரதன்', ['dasaratha', 'dasarathan', 'thasarathan', 'தசரதன்', 'தசரத'],
    ['King of Ayodhya, father of Rama, Lakshmana, Bharata and Shatrughna.', 'அயோத்தி மன்னன்; ராமர், லட்சுமணன், பரதன், சத்ருக்னனின் தந்தை.'],
    ['Bound by two boons he had promised Kaikeyi, he had to send his beloved Rama to the forest, and passed away in grief soon after.', 'கைகேயிக்கு அளித்த இரு வரங்களால் கட்டுண்டு அன்பு மகன் ராமரைக் காட்டுக்கு அனுப்ப நேர்ந்தது; விரைவில் துயரத்தில் உயிர் நீத்தார்.'],
    ['Promises must be made with care.', 'வாக்குக் கொடுப்பதில் கவனம் தேவை.'], ['kaikeyi', 'rama']),
  C('kausalya', 'ramayanam', 'Kausalya', 'கௌசல்யை', ['kausalya', 'kousalya', 'கௌசல்யை', 'கோசலை'],
    ['Dasaratha’s eldest queen and Rama’s mother.', 'தசரதனின் பட்டத்தரசி, ராமரின் தாய்.'],
    ['She blessed Rama as he left for the forest, holding back her grief for his dharma.', 'ராமரின் தர்மத்துக்காகத் துயரை அடக்கி, காட்டுக்குச் செல்லும்போது ஆசீர்வதித்தாள்.'],
    ['A mother’s strength in letting go.', 'விட்டுக்கொடுப்பதில் தாயின் வலிமை.'], ['rama']),
  C('kaikeyi', 'ramayanam', 'Kaikeyi', 'கைகேயி', ['kaikeyi', 'kaikei', 'கைகேயி'],
    ['Dasaratha’s queen and Bharata’s mother.', 'தசரதனின் அரசி, பரதனின் தாய்.'],
    ['Influenced by her maid Manthara, she asked Dasaratha for two boons — Bharata’s coronation and Rama’s 14-year exile. She later repented; Rama never spoke ill of her.', 'பணிப்பெண் மந்தரையின் தூண்டுதலால் பரதனுக்கு முடிசூட்டல், ராமருக்கு 14 ஆண்டு வனவாசம் என்ற இரு வரங்களைக் கேட்டாள். பின்னர் வருந்தினாள்; ராமர் அவளைப் பற்றி ஒருபோதும் தவறாகப் பேசவில்லை.'],
    ['Wrong advice can cloud a good heart.', 'தவறான ஆலோசனை நல்ல மனத்தையும் மறைக்கும்.'], ['manthara', 'bharata']),
  C('manthara', 'ramayanam', 'Manthara', 'மந்தரை', ['manthara', 'mandharai', 'koonai', 'மந்தரை', 'கூனி'],
    ['Kaikeyi’s maid.', 'கைகேயியின் பணிப்பெண்.'],
    ['She persuaded Kaikeyi that Rama’s coronation would harm Bharata, setting the exile in motion.', 'ராமரின் முடிசூட்டல் பரதனுக்குக் கேடு என்று கைகேயியை நம்பவைத்து வனவாசத்துக்குக் காரணமானாள்.'],
    ['Beware of words that spread suspicion.', 'சந்தேகம் பரப்பும் சொற்களில் கவனம்.'], ['kaikeyi']),
  C('hanuman', 'ramayanam', 'Hanuman', 'அனுமன்', ['hanuman', 'hanuma', 'anjaneya', 'anjaneyar', 'maruti', 'அனுமன்', 'ஆஞ்சநேயர்', 'அனுமார்'],
    ['Son of Anjana and Vayu (the wind god); Rama’s greatest devotee and Sugriva’s minister.', 'அஞ்சனை-வாயுவின் மகன்; ராமரின் பெரும் பக்தன், சுக்ரீவனின் அமைச்சர்.'],
    ['He leapt across the ocean to Lanka, found Sita in the Ashoka grove and gave her Rama’s ring, burned Lanka with his tail, and brought the Sanjeevi hill to revive Lakshmana. The Sundara Kandam is his story.', 'கடலைத் தாண்டி இலங்கை சென்று அசோக வனத்தில் சீதையைக் கண்டு ராமரின் கணையாழியைக் கொடுத்தான்; வாலால் இலங்கையை எரித்தான்; லட்சுமணனுக்காகச் சஞ்சீவி மலையைக் கொண்டு வந்தான். சுந்தர காண்டம் அவன் கதை.'],
    ['Strength with humility; devotion that acts.', 'பணிவுடன் வலிமை; செயலில் காட்டும் பக்தி.'], ['rama', 'sita', 'sugriva']),
  C('sugriva', 'ramayanam', 'Sugriva', 'சுக்ரீவன்', ['sugriva', 'sugreevan', 'sugriivan', 'சுக்ரீவன்'],
    ['King of the vanaras of Kishkindha, Vali’s younger brother.', 'கிஷ்கிந்தை வானர மன்னன், வாலியின் தம்பி.'],
    ['Driven out by Vali, he befriended Rama; Rama helped him regain the throne and he sent his armies to search for Sita and fight in Lanka.', 'வாலியால் துரத்தப்பட்டு ராமருடன் நட்புக் கொண்டான்; ராமர் உதவியால் அரசு பெற்று, சீதையைத் தேடவும் இலங்கைப் போருக்கும் படைகளை அனுப்பினான்.'],
    ['Friendship means keeping promises.', 'நட்பு என்றால் வாக்குக் காத்தல்.'], ['vali', 'hanuman']),
  C('vali', 'ramayanam', 'Vali', 'வாலி', ['vali', 'vaali', 'bali kishkindha', 'வாலி'],
    ['Mighty vanara king of Kishkindha, son of Indra.', 'இந்திரனின் மகனான வலிமைமிக்க கிஷ்கிந்தை வானர மன்னன்.'],
    ['He wronged his brother Sugriva and took his wife; Rama ended his life from behind a tree during his duel with Sugriva — an episode much debated in tradition. Vali’s son was Angada.', 'தம்பி சுக்ரீவனுக்கு அநீதி செய்து அவன் மனைவியைக் கவர்ந்தான்; சுக்ரீவனுடன் போரிடும்போது மரத்தின் பின்னிருந்து ராமர் அவனை வீழ்த்தினார் — மரபில் பெரிதும் விவாதிக்கப்படும் நிகழ்வு. வாலியின் மகன் அங்கதன்.'],
    ['Power without fairness falls.', 'நியாயமற்ற வலிமை வீழும்.'], ['sugriva', 'angada']),
  C('angada', 'ramayanam', 'Angada', 'அங்கதன்', ['angada', 'angadan', 'அங்கதன்'],
    ['Vali’s son and crown prince of Kishkindha.', 'வாலியின் மகன், கிஷ்கிந்தை இளவரசன்.'],
    ['He led the southern search party and went to Ravana’s court as Rama’s messenger, planting his foot so firmly that none could move it.', 'தெற்குத் தேடல் குழுவை வழிநடத்தி, ராமரின் தூதனாக ராவணன் அவைக்குச் சென்று யாரும் அசைக்க முடியாதபடி காலை ஊன்றினான்.'],
    ['Courage in speaking truth to power.', 'அதிகாரத்தின் முன் உண்மை பேசும் துணிவு.'], ['vali']),
  C('jambavan', 'ramayanam', 'Jambavan', 'ஜாம்பவான்', ['jambavan', 'jambavantha', 'ஜாம்பவான்'],
    ['Wise king of the bears, elder adviser in Rama’s army.', 'கரடிகளின் அறிவார்ந்த மன்னன், ராமர் படையின் மூத்த ஆலோசகர்.'],
    ['He reminded Hanuman of his forgotten strength, inspiring the leap to Lanka.', 'மறந்திருந்த வலிமையை அனுமனுக்கு நினைவூட்டி இலங்கைத் தாண்டலுக்கு ஊக்கமளித்தான்.'],
    ['A good elder helps us see our own strength.', 'நல்ல பெரியவர் நம் வலிமையை நமக்கே காட்டுவார்.'], ['hanuman']),
  C('vibhishana', 'ramayanam', 'Vibhishana', 'விபீஷணன்', ['vibhishana', 'vibishana', 'vibeeshanan', 'vibishanan', 'veebishanan', 'விபீஷணன்', 'வீடணன்'],
    ['Ravana’s younger brother, a righteous rakshasa and devotee of Vishnu.', 'ராவணனின் தம்பி, நேர்மையான அரக்கன், திருமால் பக்தன்.'],
    ['He advised Ravana to return Sita; when insulted and expelled, he took refuge with Rama (saranagati). After the war Rama crowned him king of Lanka. Tradition says he carried Ranganatha toward Lanka and the idol settled at Srirangam.', 'சீதையைத் திருப்பி அனுப்புமாறு ராவணனுக்கு அறிவுரை சொன்னான்; அவமதித்து வெளியேற்றப்பட, ராமரிடம் சரணடைந்தான் (சரணாகதி). போருக்குப் பின் ராமர் அவனை இலங்கை மன்னனாக்கினார். அவன் இலங்கைக்கு எடுத்துச் சென்ற ரங்கநாதர் ஸ்ரீரங்கத்தில் நிலைகொண்டார் என்பது மரபு.'],
    ['Standing for dharma even against one’s own family.', 'சொந்தக் குடும்பத்துக்கு எதிராகவும் தர்மத்தின் பக்கம் நிற்றல்.'], ['ravana', 'rama', 'kumbhakarna']),
  C('ravana', 'ramayanam', 'Ravana', 'ராவணன்', ['ravana', 'ravanan', 'raavanan', 'dasakanta', 'ராவணன்', 'இராவணன்'],
    ['Ten-headed king of Lanka, a great scholar and Shiva devotee, son of sage Vishravas.', 'பத்துத் தலை இலங்கை மன்னன்; விச்ரவஸ் முனிவரின் மகன், பெரும் அறிஞன், சிவபக்தன்.'],
    ['Proud of his boons, he carried Sita away from Panchavati. Despite every warning — from Vibhishana, Mandodari and Kumbhakarna — he would not return her, and was defeated by Rama in battle.', 'வரங்களால் கர்வமுற்று பஞ்சவடியிலிருந்து சீதையைக் கவர்ந்தான். விபீஷணன், மண்டோதரி, கும்பகர்ணன் எச்சரித்தும் திருப்பி அனுப்பாமல், போரில் ராமரால் வெல்லப்பட்டான்.'],
    ['Learning without humility leads to a fall.', 'பணிவில்லாக் கல்வி வீழ்ச்சிக்கு வழி.'], ['vibhishana', 'mandodari', 'kumbhakarna']),
  C('mandodari', 'ramayanam', 'Mandodari', 'மண்டோதரி', ['mandodari', 'mandothari', 'மண்டோதரி'],
    ['Ravana’s wise queen, counted among the five ideal women (Panchakanya).', 'ராவணனின் அறிவார்ந்த அரசி; பஞ்சகன்னியரில் ஒருத்தி.'],
    ['She repeatedly urged Ravana to return Sita and make peace.', 'சீதையைத் திருப்பி அனுப்பிச் சமாதானம் செய்யுமாறு ராவணனை மீண்டும் மீண்டும் வேண்டினாள்.'],
    ['Good counsel deserves to be heard.', 'நல்ல ஆலோசனை கேட்கப்பட வேண்டியது.'], ['ravana']),
  C('kumbhakarna', 'ramayanam', 'Kumbhakarna', 'கும்பகர்ணன்', ['kumbhakarna', 'kumbakarnan', 'kumbhakarnan', 'கும்பகர்ணன்'],
    ['Ravana’s giant brother who, by a twisted boon, slept for six months at a time.', 'தவறாகக் கேட்ட வரத்தால் ஆறு மாதம் உறங்கிய ராவணனின் பெருவுருவச் சகோதரன்.'],
    ['Woken for the war, he told Ravana he was wrong, yet fought for his brother out of loyalty and fell to Rama’s arrows.', 'போருக்காக எழுப்பப்பட்டதும் ராவணன் செய்தது தவறு என்று சொல்லியும், சகோதரப் பாசத்தால் போரிட்டு ராமரின் அம்புகளால் வீழ்ந்தான்.'],
    ['Loyalty and right action can pull in different ways.', 'விசுவாசமும் சரியான செயலும் வேறு திசையில் இழுக்கலாம்.'], ['ravana', 'vibhishana']),
  C('indrajit', 'ramayanam', 'Indrajit (Meghanada)', 'இந்திரஜித் (மேகநாதன்)', ['indrajit', 'indrajith', 'meghanada', 'meghanathan', 'இந்திரஜித்', 'மேகநாதன்'],
    ['Ravana’s son, a powerful warrior who once defeated Indra.', 'இந்திரனையே வென்ற ராவணனின் மகன், பெரும் வீரன்.'],
    ['He fought invisibly from the clouds and bound Rama and Lakshmana with serpent arrows; Lakshmana finally defeated him.', 'மேகங்களுக்குள் மறைந்து போரிட்டு ராம-லட்சுமணரை நாகாஸ்திரத்தால் கட்டினான்; இறுதியில் லட்சுமணனால் வெல்லப்பட்டான்.'],
    ['Skill used for a wrong cause still fails.', 'தவறான நோக்கிற்குப் பயன்படும் திறமை தோற்கும்.'], ['ravana', 'lakshmana']),
  C('surpanakha', 'ramayanam', 'Surpanakha', 'சூர்ப்பணகை', ['surpanakha', 'soorpanagai', 'shurpanakha', 'சூர்ப்பணகை'],
    ['Ravana’s sister.', 'ராவணனின் தங்கை.'],
    ['Her advances to Rama and Lakshmana at Panchavati were refused; Lakshmana cut her nose, and she went to Ravana, setting off the abduction of Sita.', 'பஞ்சவடியில் ராம-லட்சுமணரிடம் அவள் விருப்பம் மறுக்கப்பட்டது; லட்சுமணன் அவள் மூக்கை அறுக்க, ராவணனிடம் முறையிட்டு சீதை கவரப்படக் காரணமானாள்.'],
    ['Anger seeking revenge spreads harm.', 'பழிவாங்கும் கோபம் தீங்கைப் பரப்பும்.'], ['ravana']),
  C('jatayu', 'ramayanam', 'Jatayu', 'ஜடாயு', ['jatayu', 'jadayu', 'சடாயு', 'ஜடாயு'],
    ['The aged eagle-king, friend of Dasaratha.', 'தசரதனின் நண்பனான வயதான கழுகரசன்.'],
    ['He fought Ravana in the sky to save Sita and fell, mortally wounded. He told Rama which way Sita was taken, and Rama performed his last rites like a son.', 'சீதையைக் காக்க வானில் ராவணனுடன் போரிட்டு வீழ்ந்தான். சீதை எந்தத் திசையில் கொண்டு செல்லப்பட்டாள் என்று ராமருக்குச் சொல்ல, ராமர் மகன் போல அவனுக்கு இறுதிச் சடங்கு செய்தார்.'],
    ['Doing right, whatever the odds.', 'எத்தனை கடினமானாலும் சரியானதைச் செய்தல்.'], ['sita', 'rama']),
  C('sabari', 'ramayanam', 'Sabari', 'சபரி', ['sabari', 'shabari', 'sabari ramayanam', 'சபரி'],
    ['An elderly tribal woman devotee, disciple of sage Matanga.', 'மதங்க முனிவரின் சீடையான வயதான வேட்டுவக் குலப் பக்தை.'],
    ['She waited for years for Rama at her hermitage near Pampa. When he came, she offered berries she had tasted to make sure they were sweet; Rama accepted them with love and told her to guide them to Sugriva.', 'பம்பை அருகே தன் ஆசிரமத்தில் ஆண்டுகளாக ராமருக்காகக் காத்திருந்தாள். அவர் வந்தபோது இனிப்பா என்று சுவைத்துப் பார்த்த இலந்தைப் பழங்களைப் படைத்தாள்; ராமர் அன்புடன் ஏற்று, சுக்ரீவனிடம் செல்லும் வழி கேட்டார்.'],
    ['God values love, not status.', 'இறைவன் மதிப்பது அன்பையே, அந்தஸ்தை அல்ல.'], ['rama']),
  C('ahalya', 'ramayanam', 'Ahalya', 'அகலிகை', ['ahalya', 'agaligai', 'akalikai', 'அகலிகை'],
    ['Wife of sage Gautama, counted among the Panchakanya.', 'கௌதம முனிவரின் மனைவி; பஞ்சகன்னியரில் ஒருத்தி.'],
    ['Deceived by Indra, she was cursed by Gautama to remain like a stone; Rama’s touch (his feet’s dust, in the Tamil telling) freed her.', 'இந்திரனால் ஏமாற்றப்பட்டு, கௌதமர் சாபத்தால் கல் போல் இருந்தாள்; ராமரின் பாதத் தூசு பட்டு விடுதலை பெற்றாள்.'],
    ['Grace restores dignity.', 'அருள் கண்ணியத்தை மீட்டுத் தரும்.'], ['rama', 'vishwamitra']),
  C('vishwamitra', 'ramayanam', 'Vishwamitra', 'விஸ்வாமித்திரர்', ['vishwamitra', 'viswamitrar', 'vishvamitra', 'விஸ்வாமித்திரர்'],
    ['A king who became a great sage (Brahmarishi) by penance; seer of the Gayatri mantra.', 'தவத்தால் பிரம்மரிஷியான மன்னன்; காயத்ரி மந்திரத்தைக் கண்டவர்.'],
    ['He took young Rama and Lakshmana to protect his yagna, taught them divine weapons, and led them to Mithila where Rama married Sita.', 'யாகம் காக்க இளம் ராம-லட்சுமணரை அழைத்துச் சென்று தெய்வ அஸ்திரங்கள் கற்பித்து, ராமர் சீதையை மணந்த மிதிலைக்கு அழைத்துச் சென்றார்.'],
    ['Effort can transform a life.', 'முயற்சி வாழ்வையே மாற்றும்.'], ['rama']),
  C('guha', 'ramayanam', 'Guha', 'குகன்', ['guha', 'guhan', 'kugan', 'குகன்'],
    ['Chief of the boatmen at Sringiverapura.', 'சிருங்கிபேரபுரப் படகோட்டிகளின் தலைவன்.'],
    ['He ferried Rama, Sita and Lakshmana across the Ganga; Rama embraced him as a brother — Kambar sings “we were four brothers, with you now five”.', 'ராமர், சீதை, லட்சுமணரைக் கங்கை கடத்தினான்; ராமர் அவனைத் தம்பியாக அணைத்தார் — "நால்வரோடு ஐவரானோம்" என்று கம்பர் பாடுகிறார்.'],
    ['True friendship crosses every boundary.', 'உண்மை நட்பு எல்லா எல்லைகளையும் கடக்கும்.'], ['rama']),
  C('valmiki', 'ramayanam', 'Valmiki', 'வால்மீகி', ['valmiki', 'vaalmiki', 'வால்மீகி'],
    ['The Adi Kavi (first poet), author of the Sanskrit Ramayanam.', 'சமஸ்கிருத இராமாயணம் இயற்றிய ஆதி கவி.'],
    ['Tradition says he was once a highway robber, Ratnakara, transformed by sage Narada and by chanting Rama’s name; Sita lived in his ashram where Lava and Kusha were born.', 'ஒரு காலத்தில் வழிப்பறி செய்த ரத்னாகரன், நாரதரால் மாறி ராம நாமத்தால் முனிவரானார் என்பது மரபு; அவர் ஆசிரமத்தில் சீதை தங்கி லவ-குசர் பிறந்தனர்.'],
    ['Anyone can change.', 'யாரும் மாறலாம்.'], ['kambar', 'rama']),
  C('kambar', 'ramayanam', 'Kambar', 'கம்பர்', ['kambar', 'kamban', 'kamba ramayanam', 'கம்பர்', 'கம்பன்', 'கம்ப ராமாயணம்'],
    ['The 12th-century Tamil poet who wrote the Ramavataram (Kamba Ramayanam).', '12-ஆம் நூற்றாண்டில் இராமாவதாரம் (கம்ப ராமாயணம்) இயற்றிய தமிழ்க் கவிஞர்.'],
    ['His Ramayanam, first presented at Srirangam, is the best-loved Tamil telling, famous for its poetry and for portraying Rama with deep humanity.', 'ஸ்ரீரங்கத்தில் அரங்கேற்றப்பட்ட அவர் இராமாயணம், கவிநயத்துக்கும் ராமரை மனிதநேயத்துடன் காட்டியதற்கும் புகழ்பெற்ற தமிழ் வடிவம்.'],
    ['“Kalvi karaiyila” — learning has no shore.', '"கல்வி கரையில" — கல்விக்கு எல்லை இல்லை.'], ['valmiki']),
  // ------------------------------------------------------------ Mahabharatham
  C('krishna', 'mahabharatham', 'Krishna', 'கிருஷ்ணர்', ['krishna', 'krishnan', 'kannan', 'sri krishna', 'கிருஷ்ணர்', 'கண்ணன்', 'கிருஷ்ணன்'],
    ['The eighth avatar of Vishnu, born in Mathura, raised in Gokulam; friend and guide of the Pandavas.', 'மதுராவில் பிறந்து கோகுலத்தில் வளர்ந்த திருமாலின் எட்டாவது அவதாரம்; பாண்டவர்களின் தோழன், வழிகாட்டி.'],
    ['He tried to make peace as the Pandavas’ messenger, then served as Arjuna’s charioteer at Kurukshetra and taught him the Bhagavad Gita when Arjuna lost heart.', 'பாண்டவர் தூதனாகச் சமாதானத்துக்கு முயன்றார்; பின் குருக்ஷேத்திரத்தில் அர்ஜுனனின் சாரதியாகி, அவன் மனம் தளர்ந்தபோது பகவத் கீதையை உபதேசித்தார்.'],
    ['Do your duty without attachment to results.', 'பலனில் பற்றின்றிக் கடமையைச் செய்.'], ['arjuna', 'gita', 'draupadi']),
  C('arjuna', 'mahabharatham', 'Arjuna', 'அர்ஜுனன்', ['arjuna', 'arjunan', 'partha', 'dhananjaya', 'அர்ஜுனன்', 'பார்த்தன்', 'அருச்சுனன்'],
    ['The third Pandava, son of Kunti and Indra; the greatest archer, wielder of the Gandiva bow.', 'குந்தி-இந்திரனின் மகனான மூன்றாவது பாண்டவன்; காண்டீபம் ஏந்திய சிறந்த வில்லாளி.'],
    ['He won Draupadi at her swayamvara, earned the Pasupata weapon from Shiva, and at Kurukshetra received the Gita from Krishna before leading the Pandava army to victory.', 'சுயம்வரத்தில் திரௌபதியை வென்றான், சிவனிடம் பாசுபதாஸ்திரம் பெற்றான், குருக்ஷேத்திரத்தில் கண்ணனிடம் கீதை கேட்டுப் பாண்டவப் படையை வெற்றிக்கு வழிநடத்தினான்.'],
    ['Focus and humility to learn.', 'கவனமும் கற்கும் பணிவும்.'], ['krishna', 'draupadi', 'karna']),
  C('yudhishthira', 'mahabharatham', 'Yudhishthira (Dharmaputra)', 'தருமர் (யுதிஷ்டிரன்)', ['yudhishthira', 'yudhishtira', 'dharmar', 'dharmaputra', 'tharumar', 'தருமர்', 'யுதிஷ்டிரன்', 'தர்மபுத்திரன்'],
    ['Eldest Pandava, son of Kunti and Yama (Dharma); known for truthfulness.', 'குந்தி-எமதர்மனின் மகனான மூத்த பாண்டவன்; சத்தியத்துக்குப் பெயர் பெற்றவன்.'],
    ['His weakness for the dice game cost the Pandavas their kingdom and led to 13 years of exile; he answered the Yaksha’s questions wisely and later ruled as a just king.', 'சூதாட்டப் பலவீனத்தால் அரசை இழந்து 13 ஆண்டு வனவாசம்; யட்சனின் கேள்விகளுக்கு அறிவுடன் பதிலளித்தான்; பின்னர் நீதியான மன்னனாக ஆண்டான்.'],
    ['Even the good must guard against one weakness.', 'நல்லவரும் ஒரு பலவீனத்தில் கவனம் வேண்டும்.'], ['dice-game', 'bhima']),
  C('bhima', 'mahabharatham', 'Bhima', 'பீமன்', ['bhima', 'bheema', 'bhiman', 'beeman', 'vrikodara', 'பீமன்', 'வீமன்'],
    ['Second Pandava, son of Kunti and Vayu; immensely strong.', 'குந்தி-வாயுவின் மகனான இரண்டாம் பாண்டவன்; பெரும் வலிமையாளன்.'],
    ['He protected his family through every danger, defeated Bakasura, Hidimba, Jarasandha and Kichaka, and fulfilled his vow against Duryodhana in the final mace duel.', 'எல்லா ஆபத்திலும் குடும்பத்தைக் காத்தான்; பகாசுரன், இடும்பன், ஜராசந்தன், கீசகனை வென்றான்; இறுதிக் கதைப் போரில் துரியோதனனுக்கு எதிரான சபதத்தை நிறைவேற்றினான்.'],
    ['Strength used to protect others.', 'பிறரைக் காக்கும் வலிமை.'], ['ghatotkacha', 'duryodhana']),
  C('nakula-sahadeva', 'mahabharatham', 'Nakula and Sahadeva', 'நகுலன், சகாதேவன்', ['nakula', 'sahadeva', 'nakulan', 'sahadevan', 'நகுலன்', 'சகாதேவன்'],
    ['The twin Pandavas, sons of Madri and the Ashvini devas.', 'மாத்ரி-அஸ்வினி தேவர்களின் மகன்களான இரட்டைப் பாண்டவர்கள்.'],
    ['Nakula was known for his skill with horses and swords; Sahadeva for wisdom and astrology — Tamil tradition calls a clever silent knower “Sahadevan”.', 'நகுலன் குதிரை, வாள் திறமைக்கும்; சகாதேவன் ஞானம், ஜோதிடத்துக்கும் பெயர் பெற்றவர் — அறிந்தும் அமைதியாக இருப்பவரைத் தமிழில் "சகாதேவன்" என்பர்.'],
    ['Quiet talent matters.', 'அமைதியான திறமையும் முக்கியம்.'], ['yudhishthira']),
  C('draupadi', 'mahabharatham', 'Draupadi (Panchali)', 'திரௌபதி (பாஞ்சாலி)', ['draupadi', 'droupadi', 'panchali', 'thiraupathi', 'திரௌபதி', 'பாஞ்சாலி', 'திரௌபதை'],
    ['Daughter of King Drupada, born of the sacrificial fire; wife of the Pandavas.', 'யாக நெருப்பில் தோன்றிய துருபதன் மகள்; பாண்டவர்களின் மனைவி.'],
    ['After the dice game she was dragged into the Kaurava court; when Dushasana tried to disrobe her, she called on Krishna and her sari became endless. Her questions in that court are among the epic’s sharpest moments. Tamil villages worship her as Draupadi Amman.', 'சூதாட்டத்துக்குப் பின் கௌரவர் அவைக்கு இழுத்து வரப்பட்டாள்; துச்சாதனன் துகிலுரிய முயன்றபோது கண்ணனை அழைக்க, புடவை முடிவில்லாமல் நீண்டது. அந்த அவையில் அவள் கேட்ட கேள்விகள் காவியத்தின் கூர்மையான தருணங்கள். தமிழ்க் கிராமங்களில் திரௌபதி அம்மனாக வழிபடப்படுகிறாள்.'],
    ['Dignity and the courage to question injustice.', 'கண்ணியமும் அநீதியைக் கேள்வி கேட்கும் துணிவும்.'], ['krishna', 'dice-game']),
  C('kunti', 'mahabharatham', 'Kunti', 'குந்தி', ['kunti', 'kunthi', 'kunthi devi', 'குந்தி'],
    ['Mother of Karna and the three elder Pandavas.', 'கர்ணனுக்கும் மூத்த மூன்று பாண்டவர்களுக்கும் தாய்.'],
    ['Given a mantra by sage Durvasa to call any deva, she had Karna as a young girl and set him afloat; she raised the Pandavas through exile, and revealed the truth to Karna only before the war.', 'துர்வாசர் தந்த மந்திரத்தால் இளம் வயதில் கர்ணனைப் பெற்று ஆற்றில் விட்டாள்; வனவாசத்திலும் பாண்டவர்களை வளர்த்தாள்; போருக்கு முன்பே கர்ணனுக்கு உண்மையைச் சொன்னாள்.'],
    ['Hidden truths weigh heavily.', 'மறைத்த உண்மைகள் சுமையாகும்.'], ['karna']),
  C('karna', 'mahabharatham', 'Karna', 'கர்ணன்', ['karna', 'karnan', 'radheya', 'கர்ணன்', 'ராதேயன்'],
    ['Kunti’s first-born son by Surya, raised by the charioteer Adhiratha and Radha; famed for his generosity (Dhaana Veera Soora Karna).', 'சூரியன் மூலம் குந்திக்கு முதலில் பிறந்து, தேரோட்டி அதிரதன்-ராதையால் வளர்க்கப்பட்டவன்; கொடைக்குப் புகழ் பெற்றவன் (தான வீர சூர கர்ணன்).'],
    ['Mocked for his birth, he was made king of Anga by Duryodhana and stayed loyal to him for life. He gave away his divine armour and earrings to Indra, promised Kunti he would spare four of her sons, and fell to Arjuna at Kurukshetra.', 'பிறப்புக்காக ஏளனம் செய்யப்பட்டவனைத் துரியோதனன் அங்க நாட்டு மன்னனாக்க, வாழ்நாள் முழுவதும் அவனுக்கு விசுவாசமாக இருந்தான். தெய்வக் கவச குண்டலங்களை இந்திரனுக்குக் கொடுத்தான், நான்கு மகன்களைக் கொல்லேன் என்று குந்திக்கு வாக்களித்தான், குருக்ஷேத்திரத்தில் அர்ஜுனனால் வீழ்ந்தான்.'],
    ['Generosity and loyalty — and the cost of standing with the wrong side.', 'கொடையும் விசுவாசமும் — தவறான பக்கம் நிற்பதன் விலையும்.'], ['kunti', 'duryodhana', 'arjuna']),
  C('bhishma', 'mahabharatham', 'Bhishma', 'பீஷ்மர்', ['bhishma', 'bheeshma', 'bhishmar', 'devavrata', 'பீஷ்மர்'],
    ['Son of King Shantanu and Ganga; grandsire of both Kauravas and Pandavas.', 'சந்தனு மன்னன்-கங்கையின் மகன்; கௌரவர், பாண்டவர் இருவருக்கும் பாட்டனார்.'],
    ['He vowed lifelong celibacy so his father could marry Satyavati, earning the boon to choose his time of passing. He led the Kaurava army for ten days, then lay on a bed of arrows, teaching the Vishnu Sahasranamam and dharma to Yudhishthira, and left his body in Uttarayanam.', 'தந்தை சத்தியவதியை மணக்க ஆயுள் முழுவதும் பிரம்மச்சரியம் என்று சபதம் செய்து, விரும்பிய நேரத்தில் உயிர் நீக்கும் வரம் பெற்றார். பத்து நாள் கௌரவப் படையை நடத்தி, அம்புப் படுக்கையில் கிடந்து யுதிஷ்டிரனுக்கு விஷ்ணு சகஸ்ரநாமமும் தர்மமும் உபதேசித்து, உத்தராயணத்தில் உடலை நீத்தார்.'],
    ['A vow kept, even at great personal cost.', 'பெரும் தனிப்பட்ட விலையிலும் காத்த சபதம்.'], ['yudhishthira', 'kurukshetra']),
  C('drona', 'mahabharatham', 'Dronacharya', 'துரோணாச்சாரியார்', ['drona', 'dronacharya', 'dronar', 'துரோணர்', 'துரோணாச்சாரியார்'],
    ['Teacher of archery to the Kauravas and Pandavas; father of Ashwatthama.', 'கௌரவர், பாண்டவர்களுக்கு வில்வித்தை கற்பித்த ஆசான்; அஸ்வத்தாமனின் தந்தை.'],
    ['He loved Arjuna as his best pupil, asked Ekalavya for his thumb, and commanded the Kaurava army after Bhishma.', 'அர்ஜுனனைச் சிறந்த சீடனாக நேசித்தார்; ஏகலைவனிடம் கட்டைவிரலைக் குருதட்சிணையாகக் கேட்டார்; பீஷ்மருக்குப் பின் கௌரவப் படைத் தலைவரானார்.'],
    ['A teacher’s choices shape lives.', 'ஆசிரியரின் முடிவுகள் வாழ்வுகளை வடிவமைக்கும்.'], ['ekalavya', 'arjuna']),
  C('ekalavya', 'mahabharatham', 'Ekalavya', 'ஏகலைவன்', ['ekalavya', 'ekalaivan', 'eklavya', 'ஏகலைவன்'],
    ['A tribal prince who learned archery by himself before a clay image of Drona.', 'துரோணரின் களிமண் உருவத்தின் முன் தானே வில்வித்தை கற்ற வேட்டுவ இளவரசன்.'],
    ['When Drona asked for his right thumb as guru dakshina, he gave it without hesitation.', 'துரோணர் வலது கட்டைவிரலைக் குருதட்சிணையாகக் கேட்க, தயங்காமல் கொடுத்தான்.'],
    ['Devotion to learning; and a question about fairness that still matters.', 'கல்வி மீதான பக்தி; இன்றும் பொருந்தும் நியாயக் கேள்வி.'], ['drona']),
  C('duryodhana', 'mahabharatham', 'Duryodhana', 'துரியோதனன்', ['duryodhana', 'duryodhanan', 'suyodhana', 'துரியோதனன்'],
    ['Eldest of the hundred Kaurava brothers, son of Dhritarashtra and Gandhari.', 'திருதராஷ்டிரன்-காந்தாரியின் மகன், நூறு கௌரவர்களில் மூத்தவன்.'],
    ['Jealous of the Pandavas, he plotted against them (the house of lac, the dice game) and refused even five villages for peace — “not even a needle’s point of land” — which led to the war.', 'பாண்டவர்கள் மீது பொறாமையால் அரக்கு மாளிகை, சூதாட்டம் எனச் சதி செய்தான்; சமாதானத்துக்கு ஐந்து ஊர் கூடத் தர மறுத்தான் — "ஊசி முனை நிலமும் இல்லை" — அதுவே போருக்கு வழிவகுத்தது.'],
    ['Jealousy and stubbornness destroy.', 'பொறாமையும் பிடிவாதமும் அழிவு தரும்.'], ['shakuni', 'karna', 'bhima']),
  C('dhritarashtra', 'mahabharatham', 'Dhritarashtra', 'திருதராஷ்டிரன்', ['dhritarashtra', 'thirutharashtiran', 'திருதராஷ்டிரன்'],
    ['The blind king of Hastinapura, father of the Kauravas.', 'அஸ்தினாபுரத்தின் கண்பார்வையற்ற மன்னன், கௌரவர்களின் தந்தை.'],
    ['Blinded more by love for his son than by his eyes, he never stopped Duryodhana’s wrongs; Sanjaya narrated the war to him.', 'கண்களை விட மகன் மீதான பாசத்தால் குருடனாகி, துரியோதனனின் தவறுகளைத் தடுக்கவில்லை; சஞ்சயன் போரை அவனுக்கு விவரித்தான்.'],
    ['Blind love for one’s own harms everyone.', 'சொந்தத்தின் மீதான குருட்டுப் பாசம் அனைவருக்கும் கேடு.'], ['gandhari', 'sanjaya']),
  C('gandhari', 'mahabharatham', 'Gandhari', 'காந்தாரி', ['gandhari', 'kanthari', 'காந்தாரி'],
    ['Queen of Hastinapura who blindfolded herself for life to share her husband’s blindness.', 'கணவனின் பார்வையின்மையைப் பகிர வாழ்நாள் முழுவதும் கண்ணைக் கட்டிக்கொண்ட அஸ்தினாபுர அரசி.'],
    ['Mother of the hundred Kauravas; she told Duryodhana “where dharma is, there is victory”.', 'நூறு கௌரவர்களின் தாய்; "தர்மம் எங்கோ வெற்றி அங்கே" என்று துரியோதனனுக்குச் சொன்னாள்.'],
    ['Strength of character in sorrow.', 'துயரிலும் குண வலிமை.'], ['dhritarashtra']),
  C('shakuni', 'mahabharatham', 'Shakuni', 'சகுனி', ['shakuni', 'sakuni', 'சகுனி'],
    ['Gandhari’s brother and Duryodhana’s uncle, master of the dice.', 'காந்தாரியின் சகோதரன், துரியோதனனின் மாமா, சூதாட்ட நிபுணன்.'],
    ['He won the dice game against Yudhishthira by trickery, causing the Pandavas’ exile.', 'தந்திரத்தால் யுதிஷ்டிரனைச் சூதில் வென்று பாண்டவர் வனவாசத்துக்குக் காரணமானான்.'],
    ['Cunning advice ruins those who follow it.', 'சூழ்ச்சி ஆலோசனை பின்பற்றுவோரையே அழிக்கும்.'], ['dice-game', 'duryodhana']),
  C('abhimanyu', 'mahabharatham', 'Abhimanyu', 'அபிமன்யு', ['abhimanyu', 'abimanyu', 'அபிமன்யு'],
    ['Son of Arjuna and Subhadra.', 'அர்ஜுனன்-சுபத்திரையின் மகன்.'],
    ['He learned how to enter the Chakravyuha formation while still in his mother’s womb but not how to exit; on the 13th day he broke in alone and fought many warriors bravely before falling.', 'தாய் வயிற்றிலேயே சக்கரவியூகத்தில் நுழையக் கற்றான், வெளியேறக் கற்கவில்லை; 13-ஆம் நாள் தனியாக நுழைந்து பல வீரர்களுடன் துணிவுடன் போரிட்டு வீழ்ந்தான்.'],
    ['Complete your learning.', 'கற்பதை முழுமையாகக் கல்.'], ['arjuna']),
  C('ghatotkacha', 'mahabharatham', 'Ghatotkacha', 'கடோத்கஜன்', ['ghatotkacha', 'kadothkajan', 'ghatotkach', 'கடோத்கஜன்'],
    ['Son of Bhima and Hidimbi.', 'பீமன்-இடும்பியின் மகன்.'],
    ['In the night battle he fought so fiercely that Karna had to use his one-time Shakti weapon on him — which saved Arjuna.', 'இரவுப் போரில் கடுமையாகப் போரிட்டதால், அர்ஜுனனுக்காக வைத்திருந்த ஒருமுறைச் சக்தி ஆயுதத்தைக் கர்ணன் அவன் மேல் பயன்படுத்த நேர்ந்தது — அது அர்ஜுனனைக் காத்தது.'],
    ['Sacrifice that protects others.', 'பிறரைக் காக்கும் தியாகம்.'], ['bhima', 'karna']),
  C('vidura', 'mahabharatham', 'Vidura', 'விதுரர்', ['vidura', 'vidurar', 'விதுரர்'],
    ['Half-brother of Dhritarashtra and Pandu; wise minister, seen as Dharma himself.', 'திருதராஷ்டிரன், பாண்டுவின் ஒன்றுவிட்ட சகோதரர்; தர்மத்தின் வடிவமான அறிவார்ந்த அமைச்சர்.'],
    ['He warned the Pandavas about the house of lac and always gave honest advice (Vidura Neeti); Krishna chose to stay at his simple home rather than the palace.', 'அரக்கு மாளிகை பற்றிப் பாண்டவர்களை எச்சரித்தார்; எப்போதும் நேர்மையான அறிவுரை (விதுர நீதி) தந்தார்; அரண்மனைக்குப் பதில் அவர் எளிய இல்லத்தில் கண்ணன் தங்கினார்.'],
    ['Honest counsel, even when unwelcome.', 'விரும்பாவிட்டாலும் நேர்மையான ஆலோசனை.'], ['krishna']),
  C('vyasa', 'mahabharatham', 'Vyasa', 'வியாசர்', ['vyasa', 'vyasar', 'veda vyasa', 'krishna dvaipayana', 'வியாசர்'],
    ['Sage who arranged the Vedas and composed the Mahabharatham; grandfather of the Kauravas and Pandavas.', 'வேதங்களைத் தொகுத்து மகாபாரதம் இயற்றிய முனிவர்; கௌரவ-பாண்டவர்களின் பாட்டனார்.'],
    ['Tradition says Ganesha wrote the Mahabharatham as Vyasa dictated, on the condition that the dictation never pause.', 'வியாசர் சொல்லச் சொல்ல, இடைவிடாமல் சொல்ல வேண்டும் என்ற நிபந்தனையுடன் விநாயகர் மகாபாரதம் எழுதினார் என்பது மரபு.'],
    ['Knowledge shared freely lives on.', 'பகிரப்படும் அறிவு நிலைக்கும்.'], ['krishna']),
  C('sanjaya', 'mahabharatham', 'Sanjaya', 'சஞ்சயன்', ['sanjaya', 'sanjayan', 'சஞ்சயன்'],
    ['Dhritarashtra’s charioteer and adviser.', 'திருதராஷ்டிரனின் தேரோட்டி, ஆலோசகர்.'],
    ['Granted divine sight by Vyasa, he narrated the whole Kurukshetra war — including the Gita — to the blind king.', 'வியாசர் தந்த ஞானப் பார்வையால் குருக்ஷேத்திரப் போர் முழுவதையும் — கீதை உட்பட — பார்வையற்ற மன்னனுக்கு விவரித்தான்.'],
    ['Report the truth faithfully.', 'உண்மையை நேர்மையாகச் சொல்.'], ['dhritarashtra', 'gita']),
  C('ashwatthama', 'mahabharatham', 'Ashwatthama', 'அஸ்வத்தாமன்', ['ashwatthama', 'aswathama', 'asvathaman', 'அஸ்வத்தாமன்'],
    ['Son of Drona, a great warrior on the Kaurava side.', 'துரோணரின் மகன், கௌரவர் பக்க வீரன்.'],
    ['After the war he attacked the sleeping Pandava camp at night; Krishna cursed him to wander the earth.', 'போருக்குப் பின் இரவில் உறங்கிய பாண்டவர் முகாமைத் தாக்கினான்; கண்ணன் அவனைப் பூமியில் அலையச் சபித்தார்.'],
    ['Revenge breaks every rule of dharma.', 'பழிவாங்கல் தர்ம விதிகளை எல்லாம் உடைக்கும்.'], ['drona']),
  C('dice-game', 'mahabharatham', 'The dice game (Soothattam)', 'சூதாட்டம் (பகடை)', ['dice game', 'game of dice', 'soothattam', 'sudhattam', 'pagadai', 'சூதாட்டம்', 'பகடை ஆட்டம்'],
    ['The turning point of the Mahabharatham, held at Hastinapura.', 'அஸ்தினாபுரத்தில் நடந்த, மகாபாரதத்தின் திருப்புமுனை.'],
    ['Shakuni’s loaded dice made Yudhishthira lose his wealth, kingdom, brothers, himself and Draupadi; Draupadi’s humiliation led to the Pandavas’ vows and, after 13 years of exile, to the war.', 'சகுனியின் தந்திரப் பகடையால் யுதிஷ்டிரன் செல்வம், அரசு, சகோதரர்கள், தன்னை, திரௌபதியை இழந்தான்; திரௌபதியின் அவமானம் பாண்டவர் சபதங்களுக்கும், 13 ஆண்டு வனவாசத்துக்குப் பின் போருக்கும் வழிவகுத்தது.'],
    ['Gambling and pride can cost everything.', 'சூதும் கர்வமும் எல்லாவற்றையும் இழக்கச் செய்யும்.'], ['yudhishthira', 'shakuni', 'draupadi']),
  C('kurukshetra', 'mahabharatham', 'Kurukshetra war', 'குருக்ஷேத்திரப் போர்', ['kurukshetra', 'kurukshetra war', 'bharata war', 'mahabharata war', 'குருக்ஷேத்திரம்', 'குருக்ஷேத்திரப் போர்', 'பாரதப் போர்'],
    ['The 18-day war between the Kauravas and Pandavas.', 'கௌரவர்-பாண்டவர்களிடையே நடந்த 18 நாள் போர்.'],
    ['Bhishma led the Kauravas for 10 days, Drona for 5, Karna for 2 and Shalya for 1. The Pandavas won with Krishna’s guidance, but at a terrible cost to both sides; Yudhishthira then ruled with sorrow and humility.', 'கௌரவர்களை 10 நாள் பீஷ்மர், 5 நாள் துரோணர், 2 நாள் கர்ணன், 1 நாள் சல்லியன் நடத்தினர். கண்ணன் வழிகாட்டலில் பாண்டவர் வென்றனர் — இரு பக்கமும் பெரும் இழப்புடன்; பின் யுதிஷ்டிரன் துயரத்துடனும் பணிவுடனும் ஆண்டான்.'],
    ['War has no real winners; dharma must guide power.', 'போரில் உண்மையான வெற்றியாளர் இல்லை; அதிகாரத்தைத் தர்மம் வழிநடத்த வேண்டும்.'], ['gita', 'bhishma']),
  C('gita', 'mahabharatham', 'Bhagavad Gita', 'பகவத் கீதை', ['bhagavad gita', 'gita', 'geetha', 'gita upadesam', 'gita upadesham', 'பகவத் கீதை', 'கீதை', 'கீதோபதேசம்'],
    ['Krishna’s 700-verse teaching to Arjuna on the battlefield, part of the Bhishma Parva.', 'போர்க்களத்தில் அர்ஜுனனுக்குக் கண்ணன் சொன்ன 700 சுலோக உபதேசம்; பீஷ்ம பர்வத்தின் பகுதி.'],
    ['Arjuna, seeing his elders and teachers in the opposing army, put down his bow. Krishna taught him about the eternal self, selfless action (karma yoga), knowledge and devotion, showed his universal form, and Arjuna rose to do his duty.', 'எதிர்ப் படையில் பெரியோர், ஆசிரியர்களைக் கண்டு அர்ஜுனன் வில்லைக் கீழே வைத்தான். நிலையான ஆன்மா, பற்றற்ற செயல் (கர்ம யோகம்), ஞானம், பக்தி பற்றிக் கண்ணன் உபதேசித்து விஸ்வரூபம் காட்ட, அர்ஜுனன் கடமையைச் செய்ய எழுந்தான்.'],
    ['“Your right is to the work, not to its fruits.”', '"கடமையைச் செய், பலனை எதிர்பாராதே."'], ['krishna', 'arjuna']),
  C('savitri', 'puranam', 'Savitri', 'சாவித்திரி', ['savitri', 'savithri', 'satyavan', 'சாவித்திரி', 'சத்தியவான்'],
    ['A princess from the Mahabharatham’s Vana Parva, wife of Satyavan.', 'மகாபாரத வன பர்வத்தில் வரும் இளவரசி, சத்தியவானின் மனைவி.'],
    ['She followed Yama when he came for her husband, and with wisdom and devotion won his life back — remembered on Karadaiyan Nombu.', 'கணவனை அழைத்துச் செல்ல வந்த எமனைப் பின்தொடர்ந்து, அறிவாலும் பக்தியாலும் அவன் உயிரை மீட்டாள் — காரடையான் நோன்பில் நினைவுகூரப்படுகிறாள்.'],
    ['Wisdom and love together are unbeatable.', 'அறிவும் அன்பும் சேர்ந்தால் வெல்ல முடியாது.'], []),
  // ------------------------------------------------------------ Puranam & Tamil saints
  C('prahlada', 'puranam', 'Prahlada', 'பிரகலாதன்', ['prahlada', 'prahladan', 'pragalathan', 'பிரகலாதன்'],
    ['Child devotee of Vishnu, son of the asura king Hiranyakasipu.', 'அசுர மன்னன் இரணியனின் மகனான திருமால் பக்தச் சிறுவன்.'],
    ['His father tried every means to turn him away from Vishnu; he stayed unafraid, saying the Lord is everywhere — even in the pillar. Narasimha emerged from it to protect him.', 'திருமாலை விட்டுவிடச் செய்ய தந்தை எல்லா வழியும் முயன்றான்; இறைவன் தூணிலும் இருக்கிறான் என்று அஞ்சாமல் நின்றான். அந்தத் தூணிலிருந்து நரசிம்மர் தோன்றிக் காத்தார்.'],
    ['Faith without fear.', 'பயமற்ற நம்பிக்கை.'], ['narasimha']),
  C('narasimha', 'puranam', 'Narasimha', 'நரசிம்மர்', ['narasimha', 'narasimhar', 'nrusimha', 'நரசிம்மர்'],
    ['The man-lion avatar of Vishnu.', 'திருமாலின் மனித-சிங்க அவதாரம்.'],
    ['He appeared from a pillar at twilight to end Hiranyakasipu’s tyranny and protect Prahlada, honouring every condition of the asura’s boon.', 'இரணியனின் வரத்தின் எல்லா நிபந்தனைகளையும் மதித்து, அந்தியில் தூணிலிருந்து தோன்றி அவன் கொடுங்கோன்மையை முடித்துப் பிரகலாதனைக் காத்தார்.'],
    ['The Lord protects the sincere.', 'உண்மையானவரை இறைவன் காப்பான்.'], ['prahlada']),
  C('dhruva', 'puranam', 'Dhruva', 'துருவன்', ['dhruva', 'dhruvan', 'thuruvan', 'துருவன்'],
    ['A young prince who, hurt by his stepmother’s words, did intense penance to Vishnu.', 'மாற்றாந்தாயின் சொல்லால் மனம் நொந்து திருமாலை நோக்கித் தவம் செய்த இளவரசன்.'],
    ['Guided by Narada, the five-year-old meditated with "Om Namo Bhagavate Vasudevaya"; Vishnu blessed him with a lasting place as the Pole Star (Dhruva Nakshatra).', 'நாரதர் வழிகாட்ட, ஐந்து வயதுச் சிறுவன் "ஓம் நமோ பகவதே வாசுதேவாய" என்று தியானித்தான்; துருவ நட்சத்திரமாக நிலையான இடம் தந்து திருமால் அருளினார்.'],
    ['Determination at any age.', 'எந்த வயதிலும் உறுதி.'], []),
  C('markandeya', 'puranam', 'Markandeya', 'மார்க்கண்டேயன்', ['markandeya', 'markandeyan', 'markandeyar', 'மார்க்கண்டேயன்', 'மார்க்கண்டேயர்'],
    ['A boy sage, great devotee of Shiva.', 'சிறுவயது முனிவன், பெரும் சிவபக்தன்.'],
    ['He was destined to have a brief life, and when Yama came he hugged the Shiva lingam at Thirukadaiyur; Shiva appeared as Kalasamhara Murthy, protected him and blessed him to be forever sixteen. Hence 60th and 80th celebrations are held at Thirukadaiyur.', 'குறுகிய ஆயுள் என்று விதிக்கப்பட்ட அவன், எமன் வந்தபோது திருக்கடையூரில் சிவலிங்கத்தைத் தழுவினான்; சிவன் காலசம்ஹார மூர்த்தியாகத் தோன்றிக் காத்து, என்றும் பதினாறு வயதாக இருக்க அருளினார். அதனால் 60, 80-ஆம் விழாக்கள் திருக்கடையூரில் நடக்கின்றன.'],
    ['Sincere devotion overcomes fear.', 'உண்மையான பக்தி பயத்தை வெல்லும்.'], []),
  C('murugan', 'puranam', 'Murugan', 'முருகன்', ['murugan', 'muruga', 'karthikeya', 'subramanya', 'skanda', 'shanmukha', 'murugar', 'முருகன்', 'முருகா', 'கார்த்திகேயன்', 'சுப்பிரமணியர்', 'ஆறுமுகன்', 'கந்தன்'],
    ['Son of Shiva and Parvati, Tamil God of youth, beauty and wisdom; the Tamil kadavul.', 'சிவ-பார்வதியின் மகன்; இளமை, அழகு, ஞானத்தின் தமிழ்க் கடவுள்.'],
    ['Born from six sparks of Shiva’s third eye at Saravana Poigai, he defeated Soorapadman with the Vel; at Swamimalai he taught the meaning of "Om" to Shiva. His six abodes (Arupadai Veedu) are Thiruparankundram, Tiruchendur, Palani, Swamimalai, Thiruthani and Pazhamudircholai.', 'சிவனின் நெற்றிக்கண் ஆறு தீப்பொறிகளிலிருந்து சரவணப் பொய்கையில் தோன்றி, வேலால் சூரபத்மனை வென்றார்; சுவாமிமலையில் சிவனுக்கே "ஓம்" பொருள் உரைத்தார். ஆறுபடை வீடுகள்: திருப்பரங்குன்றம், திருச்செந்தூர், பழனி, சுவாமிமலை, திருத்தணி, பழமுதிர்ச்சோலை.'],
    ['Wisdom (the Vel) cuts through ignorance.', 'ஞானம் (வேல்) அறியாமையை அறுக்கும்.'], ['vinayagar']),
  C('vinayagar', 'puranam', 'Vinayagar (Ganesha)', 'விநாயகர்', ['vinayagar', 'pillaiyar', 'ganesha', 'ganapathi', 'ganesh', 'vinayaka', 'விநாயகர்', 'பிள்ளையார்', 'கணபதி', 'கணேசன்'],
    ['Elephant-faced son of Shiva and Parvati, remover of obstacles, worshipped first.', 'சிவ-பார்வதியின் யானைமுக மகன்; தடைகளை நீக்குபவர், முதலில் வழிபடப்படுபவர்.'],
    ['When a mango of wisdom was offered to whichever son went round the world first, Murugan flew around the world on his peacock, but Ganesha simply circled his parents — saying they were his world — and won the fruit.', 'உலகை முதலில் சுற்றி வருபவருக்கு ஞானப்பழம் என்றபோது, முருகன் மயிலில் உலகைச் சுற்ற, விநாயகர் "பெற்றோரே என் உலகம்" என்று பெற்றோரைச் சுற்றிப் பழத்தை வென்றார்.'],
    ['Parents are our world; wisdom over speed.', 'பெற்றோரே நம் உலகம்; வேகத்தை விட விவேகம்.'], ['murugan']),
  C('ayyappan', 'puranam', 'Ayyappan', 'ஐயப்பன்', ['ayyappan', 'ayyappa', 'dharma sastha', 'manikandan', 'sastha', 'ஐயப்பன்', 'சாஸ்தா', 'மணிகண்டன்'],
    ['Son of Shiva and Mohini (Vishnu), raised as Manikandan by the King of Pandalam; the deity of Sabarimala.', 'சிவன்-மோகினியின் (திருமால்) மகன்; பந்தள மன்னனால் மணிகண்டனாக வளர்க்கப்பட்டவர்; சபரிமலை தெய்வம்.'],
    ['He defeated the demoness Mahishi and brought tiger’s milk for his foster mother; he sits in yoga posture at Sabarimala, where all devotees are equal as "Swami".', 'மகிஷி என்ற அரக்கியை வென்று, வளர்ப்புத் தாய்க்குப் புலிப்பால் கொண்டு வந்தார்; சபரிமலையில் யோக நிலையில் அமர்ந்துள்ளார் — அங்கு எல்லாப் பக்தரும் "சாமி" என்ற சமம்.'],
    ['Discipline and equality.', 'ஒழுக்கமும் சமத்துவமும்.'], []),
  C('andal', 'puranam', 'Andal', 'ஆண்டாள்', ['andal', 'aandal', 'kodhai', 'goda devi', 'ஆண்டாள்', 'கோதை'],
    ['The only woman among the 12 Azhvars; foster daughter of Periyazhvar at Srivilliputhur.', '12 ஆழ்வார்களில் ஒரே பெண்; ஸ்ரீவில்லிபுத்தூரில் பெரியாழ்வாரின் வளர்ப்பு மகள்.'],
    ['She wore the garlands meant for the Lord before offering them ("Soodi kodutha sudarkodi"), sang the Thiruppavai and Nachiyar Thirumozhi, and is believed to have merged with Ranganatha at Srirangam.', 'இறைவனுக்கான மாலையைத் தானே சூடிக் கொடுத்தாள் ("சூடிக் கொடுத்த சுடர்க்கொடி"); திருப்பாவை, நாச்சியார் திருமொழி பாடி, ஸ்ரீரங்கத்தில் அரங்கனுடன் கலந்தாள் என்பது நம்பிக்கை.'],
    ['Love for God can be joyful and personal.', 'இறை அன்பு மகிழ்ச்சியானதும் நெருக்கமானதும்.'], []),
  C('manikkavasagar', 'puranam', 'Manikkavasagar', 'மாணிக்கவாசகர்', ['manikkavasagar', 'manickavasagar', 'thiruvasagam', 'மாணிக்கவாசகர்', 'திருவாசகம்'],
    ['Minister of the Pandya king who became a Shaiva saint; author of Thiruvasagam and Thiruvempavai.', 'சைவ அடியாரான பாண்டிய மன்னனின் அமைச்சர்; திருவாசகம், திருவெம்பாவை இயற்றியவர்.'],
    ['Sent to buy horses, he spent the money building a temple at Thirupperunthurai; Shiva turned jackals into horses to save him (the "nari pari" story).', 'குதிரை வாங்க அனுப்பப்பட்ட பணத்தில் திருப்பெருந்துறையில் கோவில் கட்டினார்; அவரைக் காக்கச் சிவன் நரிகளைப் பரிகளாக்கினார் ("நரி பரியாக்கிய" கதை).'],
    ['"Thiruvasagathukku urugaar oru vasagathukkum urugaar."', '"திருவாசகத்துக்கு உருகார் ஒரு வாசகத்துக்கும் உருகார்."'], []),
  C('kannappa', 'puranam', 'Kannappa Nayanar', 'கண்ணப்ப நாயனார்', ['kannappa', 'kannappar', 'thinnan', 'கண்ணப்பர்', 'கண்ணப்ப நாயனார்', 'திண்ணன்'],
    ['A hunter, one of the 63 Nayanmars, at Srikalahasti.', 'ஸ்ரீகாளஹஸ்தியில் வேடர்; 63 நாயன்மார்களில் ஒருவர்.'],
    ['He offered meat and water from his mouth with pure love; when the lingam’s eye seemed to bleed, he offered his own eye, and Shiva stopped him and blessed him.', 'தூய அன்புடன் இறைச்சியும் வாயால் கொண்ட நீரும் படைத்தார்; லிங்கத்தின் கண்ணில் ரத்தம் வழிவது போலத் தோன்ற, தன் கண்ணையே கொடுக்க, சிவன் தடுத்து அருளினார்.'],
    ['God sees the heart, not the rules.', 'இறைவன் பார்ப்பது மனத்தை, விதிகளை அல்ல.'], []),
  C('nandanar', 'puranam', 'Nandanar', 'நந்தனார்', ['nandanar', 'thirunalai povar', 'நந்தனார்', 'திருநாளைப் போவார்'],
    ['A farm labourer and Nayanmar who longed to see Nataraja at Chidambaram.', 'சிதம்பர நடராஜரைக் காண ஏங்கிய விவசாயத் தொழிலாளி, நாயன்மார்.'],
    ['Kept out because of caste, he kept saying "I will go tomorrow"; at Thiruppunkur the Nandi moved aside so he could see Shiva, and at Chidambaram he was welcomed by the Lord.', 'சாதியால் தடுக்கப்பட்டு "நாளை போவேன்" என்றே சொல்லி வந்தார்; திருப்புன்கூரில் அவர் சிவனைக் காண நந்தி விலகியது; சிதம்பரத்தில் இறைவன் ஏற்றுக்கொண்டார்.'],
    ['Devotion is above birth.', 'பிறப்பை விடப் பக்தி மேலானது.'], []),
  C('karaikal-ammaiyar', 'puranam', 'Karaikal Ammaiyar', 'காரைக்கால் அம்மையார்', ['karaikal ammaiyar', 'karaikkal ammaiyar', 'punithavathi', 'காரைக்கால் அம்மையார்', 'புனிதவதி'],
    ['One of the earliest Tamil Shaiva poets and one of the three women among the 63 Nayanmars.', 'தொன்மையான தமிழ்ச் சைவக் கவிஞர்; 63 நாயன்மார்களில் மூன்று பெண்களில் ஒருவர்.'],
    ['Shiva gave her a mango by grace when she had offered her husband’s mango to a devotee; she later chose a life of devotion and sang at Thiruvalangadu, where Shiva calls her "Amma".', 'கணவனின் மாம்பழத்தை அடியாருக்குக் கொடுத்த அவளுக்குச் சிவன் அருளால் மாம்பழம் தந்தார்; பின் பக்தி வாழ்வைத் தேர்ந்து திருவாலங்காட்டில் பாடினார் — சிவனே "அம்மையே" என்று அழைத்தார்.'],
    ['Generosity is never lost.', 'கொடை என்றும் வீணாகாது.'], []),
  C('avvaiyar', 'puranam', 'Avvaiyar', 'அவ்வையார்', ['avvaiyar', 'auvaiyar', 'avvai', 'அவ்வையார்', 'ஔவையார்', 'அவ்வை'],
    ['The beloved Tamil woman poet of wisdom; Aathichoodi and Kondrai Vendhan are hers.', 'அன்பான தமிழ்ப் பெண் ஞானக் கவிஞர்; ஆத்திசூடி, கொன்றை வேந்தன் அவர் படைப்புகள்.'],
    ['In the famous story young Murugan asked her "chutta pazham vendumaa, chudaatha pazham vendumaa?" — teaching her humility. She is also linked with Aadi Sevvai Avvaiyar nombu.', 'புகழ்பெற்ற கதையில் சிறுவன் முருகன் "சுட்ட பழம் வேண்டுமா, சுடாத பழம் வேண்டுமா?" என்று கேட்டுப் பணிவைக் கற்பித்தார். ஆடி செவ்வாய் அவ்வையார் நோன்புடனும் தொடர்புடையவர்.'],
    ['"Aram seyya virumbu" — love to do good.', '"அறம் செய விரும்பு."'], ['murugan']),
  C('harischandra', 'puranam', 'Harischandra', 'அரிச்சந்திரன்', ['harischandra', 'arichandran', 'harishchandra', 'அரிச்சந்திரன்'],
    ['A king who never told a lie.', 'ஒருபோதும் பொய் சொல்லாத மன்னன்.'],
    ['Tested by Vishwamitra, he gave up his kingdom, family and freedom, working at a cremation ground, yet would not break his word; the gods restored everything.', 'விஸ்வாமித்திரரின் சோதனையில் அரசு, குடும்பம், சுதந்திரம் இழந்து மயானத்தில் பணிசெய்தும் சொல் தவறவில்லை; தேவர்கள் அனைத்தையும் திருப்பித் தந்தனர்.'],
    ['Truth above all.', 'எல்லாவற்றுக்கும் மேல் சத்தியம்.'], []),
  C('nachiketa', 'puranam', 'Nachiketa', 'நசிகேதன்', ['nachiketa', 'nachiketas', 'nasikethan', 'நசிகேதன்'],
    ['A boy in the Katha Upanishad who questioned Yama.', 'கடோபநிஷத்தில் எமனிடம் கேள்வி கேட்ட சிறுவன்.'],
    ['Waiting three days at Yama’s door, he received three boons and refused all riches, asking only what happens to the self — and Yama taught him the knowledge of the eternal Atma.', 'எமன் வாசலில் மூன்று நாள் காத்திருந்து மூன்று வரங்கள் பெற்று, எல்லாச் செல்வத்தையும் மறுத்து ஆன்மா பற்றியே கேட்டான் — எமன் நிலையான ஆன்ம ஞானத்தை உபதேசித்தார்.'],
    ['Seek lasting truth over passing pleasures.', 'தற்காலிக இன்பத்தை விட நிலையான உண்மையைத் தேடு.'], []),
  C('bhagiratha', 'puranam', 'Bhagiratha (Ganga’s descent)', 'பகீரதன் (கங்கை இறங்குதல்)', ['bhagiratha', 'bhageerathan', 'ganga descent', 'bhagiratha prayatnam', 'பகீரதன்', 'பகீரதப் பிரயத்தனம்'],
    ['A king of Rama’s line (Ikshvaku) who brought the Ganga down to earth.', 'கங்கையைப் பூமிக்குக் கொண்டு வந்த ராமர் குல (இக்ஷ்வாகு) மன்னன்.'],
    ['After long penance, Ganga agreed to descend; Shiva caught her in his matted hair to soften her fall, and she flowed to free Bhagiratha’s ancestors. A huge effort is still called "Bhagiratha prayatnam".', 'நீண்ட தவத்துக்குப் பின் கங்கை இறங்க ஒப்ப, அவள் வேகத்தைக் குறைக்கச் சிவன் சடையில் தாங்கினார்; பகீரதனின் முன்னோரைக் கரைசேர்க்க ஓடினாள். பெரும் முயற்சியை இன்றும் "பகீரதப் பிரயத்தனம்" என்பர்.'],
    ['Persistence achieves the impossible.', 'விடாமுயற்சி முடியாததையும் முடிக்கும்.'], []),
  C('mahabali', 'puranam', 'Mahabali and Vamana', 'மகாபலி, வாமனர்', ['mahabali', 'maveli', 'vamana', 'vamanar', 'மகாபலி', 'வாமனர்', 'வாமனன்'],
    ['A generous asura king and Vishnu’s dwarf avatar Vamana.', 'வள்ளல் அசுர மன்னன், திருமாலின் குள்ள அவதாரம் வாமனர்.'],
    ['Vamana asked Bali for three steps of land, then grew to measure the worlds; Bali offered his head for the third step and was blessed to visit his people every Onam.', 'வாமனர் பலியிடம் மூன்றடி நிலம் கேட்டு விஸ்வரூபம் எடுத்து உலகங்களை அளந்தார்; மூன்றாம் அடிக்குப் பலி தலையைக் கொடுத்து, ஒவ்வொரு ஓணத்திலும் மக்களைக் காண வரம் பெற்றான்.'],
    ['Humility makes even the defeated great.', 'பணிவு தோற்றவனையும் உயர்த்தும்.'], []),
  C('samudra-manthan', 'puranam', 'Churning of the ocean (Samudra Manthan)', 'பாற்கடல் கடைதல்', ['samudra manthan', 'parkadal', 'churning of the ocean', 'amirtham', 'halahala', 'பாற்கடல்', 'பாற்கடல் கடைதல்', 'ஆலகால விஷம்'],
    ['The great churning of the milk ocean by devas and asuras for amrita (nectar).', 'அமுதத்துக்காகத் தேவரும் அசுரரும் பாற்கடலைக் கடைந்த பெரும் நிகழ்வு.'],
    ['Mount Mandara was the churning rod and Vasuki the rope, with Vishnu as the tortoise (Kurma) holding the mountain. The Halahala poison came first — Shiva swallowed it (Pradosham); then Lakshmi, Kamadhenu, Airavata and finally amrita, which Vishnu as Mohini gave to the devas.', 'மந்தர மலை மத்தாகவும் வாசுகி கயிறாகவும், மலையைத் தாங்க திருமால் ஆமையாகவும் (கூர்மம்). முதலில் ஆலகால விஷம் — சிவன் விழுங்கினார் (பிரதோஷம்); பின் லட்சுமி, காமதேனு, ஐராவதம், இறுதியில் அமுதம் — மோகினியாகத் திருமால் தேவர்களுக்கு வழங்கினார்.'],
    ['Good things come after patience — and someone must bear the poison first.', 'பொறுமைக்குப் பின்னே நன்மை — விஷத்தை முதலில் யாராவது தாங்க வேண்டும்.'], []),
];
