// General spiritual concepts and life-events (no fixed festival date). `planet` entries get live transit dates
// from peyarchi.js; `grahanam` gets eclipse dates from astronomy-engine; the rest point to the right screen.
import { B, SRC } from './common.js';

export const CONCEPTS = [
  {
    id: 'guru-peyarchi', kind: 'concept', planet: 'Jupiter', personalNull: true, mantra: 'guru',
    names: B('Guru Peyarchi', 'குருப் பெயர்ச்சி'),
    aliases: ['guru peyarchi', 'guru peyarchi 2026', 'jupiter transit', 'guru payarchi', 'guru peyarchi eppo', 'குரு பெயர்ச்சி', 'குருப் பெயர்ச்சி'],
    deity: B('Guru (Brihaspati), Dakshinamurthy', 'குரு பகவான் (பிரகஸ்பதி), தட்சிணாமூர்த்தி'),
    line: B('Jupiter moving into the next rasi — about once a year.', 'வியாழன் அடுத்த ராசிக்கு நகர்வது — ஏறக்குறைய ஆண்டுக்கு ஒருமுறை.'),
    why: B('Guru (Jupiter) spends about a year in each rasi. Its change of sign is a traditional time for prayer, as Guru is linked with wisdom, children, teachers and good counsel. Effects are read differently for each person’s Moon sign — see the Peyarchi screen for yours.', 'குரு (வியாழன்) ஒவ்வொரு ராசியிலும் சுமார் ஓராண்டு இருப்பார். ஞானம், குழந்தைகள், ஆசிரியர், நல்ல ஆலோசனையுடன் தொடர்புடைய குரு ராசி மாறும் நேரம் வழிபாட்டுக்கு உரியது என்பது மரபு. பலன் ஒவ்வொருவரின் சந்திர ராசிக்கு ஏற்ப மாறும் — உங்களுக்குப் பெயர்ச்சி பகுதியில் பாருங்கள்.'),
    how: B(['On Thursdays, light a ghee lamp to Dakshinamurthy; offer yellow flowers and chickpeas (kondakadalai).', 'Respect teachers and elders; help a student — these are the simplest Guru prayers.'], ['வியாழக்கிழமைகளில் தட்சிணாமூர்த்திக்கு நெய் விளக்கு; மஞ்சள் மலர், கொண்டைக்கடலை சமர்ப்பித்தல்.', 'ஆசிரியர், பெரியவர்களை மதித்தல்; ஒரு மாணவருக்கு உதவுதல் — இவையே எளிய குரு வழிபாடு.']),
    temples: ['alangudi', 'tiruchendur'],
    see: ['sani-peyarchi'], sources: SRC,
  },
  {
    id: 'sani-peyarchi', kind: 'concept', planet: 'Saturn', personalNull: true, mantra: 'rama',
    names: B('Sani Peyarchi', 'சனிப் பெயர்ச்சி'),
    aliases: ['sani peyarchi', 'shani peyarchi', 'saturn transit', 'sani payarchi', 'சனி பெயர்ச்சி', 'சனிப் பெயர்ச்சி'],
    deity: B('Sani Bhagavan (Saneeswaran)', 'சனி பகவான் (சனீஸ்வரன்)'),
    line: B('Saturn moving into the next rasi — about every 2½ years.', 'சனி அடுத்த ராசிக்கு நகர்வது — ஏறக்குறைய 2½ ஆண்டுக்கு ஒருமுறை.'),
    why: B('Sani is seen in tradition as the teacher of patience, hard work and fairness. His sign change is a time for prayer and for steady, honest effort; it is not something to fear. Personal effects depend on your Moon sign — see the Peyarchi screen.', 'பொறுமை, உழைப்பு, நேர்மையைக் கற்றுத் தரும் ஆசானாகச் சனியை மரபு பார்க்கிறது. அவர் ராசி மாற்றம் வழிபாட்டுக்கும் உறுதியான, நேர்மையான முயற்சிக்கும் உரிய நேரம்; பயப்பட வேண்டியது அல்ல. உங்கள் சந்திர ராசிக்கான பலனைப் பெயர்ச்சி பகுதியில் பாருங்கள்.'),
    how: B(['On Saturdays light a sesame-oil lamp; pray to Perumal or Anjaneyar; feed crows and the needy; help elderly people and workers.'], ['சனிக்கிழமைகளில் நல்லெண்ணெய் விளக்கு; பெருமாள் அல்லது ஆஞ்சநேயர் வழிபாடு; காக்கைக்கும் ஏழைகளுக்கும் உணவு; முதியவர்கள், உழைப்பாளிகளுக்கு உதவி.']),
    temples: ['thirunallar', 'kuchanur'], sources: SRC,
  },
  {
    id: 'rahu-ketu-peyarchi', kind: 'concept', planet: 'Rahu', personalNull: true, mantra: 'durga',
    names: B('Rahu–Ketu Peyarchi', 'ராகு-கேது பெயர்ச்சி'),
    aliases: ['rahu ketu peyarchi', 'rahu peyarchi', 'ketu peyarchi', 'rahu ketu transit', 'ராகு கேது பெயர்ச்சி', 'ராகு பெயர்ச்சி', 'கேது பெயர்ச்சி'],
    deity: B('Rahu and Ketu; Durga, Vinayagar', 'ராகு, கேது; துர்க்கை, விநாயகர்'),
    line: B('The lunar nodes change sign together, moving backwards, about every 18 months.', 'சந்திரக் கணுக்கள் ஒன்றாகப் பின்னோக்கி ராசி மாறுவது — ஏறக்குறைய 18 மாதத்துக்கு ஒருமுறை.'),
    why: B('Rahu and Ketu are the points where the Moon’s path crosses the Sun’s — they are where eclipses happen. Traditionally Durga is prayed to for Rahu and Vinayagar for Ketu.', 'சந்திரனின் பாதை சூரியப் பாதையைக் கடக்கும் புள்ளிகள் ராகு, கேது — கிரகணங்கள் நிகழும் இடம். மரபுப்படி ராகுவுக்குத் துர்க்கை, கேதுவுக்கு விநாயகர் வழிபாடு.'),
    how: B(['Rahu kalam lamp to Durga on Tuesdays/Fridays; arugampul to Vinayagar for Ketu.'], ['செவ்வாய்/வெள்ளி ராகு காலத்தில் துர்க்கைக்கு விளக்கு; கேதுவுக்கு விநாயகருக்கு அருகம்புல்.']),
    temples: ['thirunageswaram', 'keezhaperumpallam', 'kalahasti'], sources: SRC,
  },
  {
    id: 'grahanam', kind: 'concept', mantra: 'gayatri',
    names: B('Grahanam (eclipse)', 'கிரகணம்'),
    aliases: ['grahanam', 'grahan', 'eclipse', 'chandra grahanam', 'surya grahanam', 'lunar eclipse', 'solar eclipse', 'kiraganam', 'கிரகணம்', 'சந்திர கிரகணம்', 'சூரிய கிரகணம்'],
    deity: B('Surya, Chandra', 'சூரியன், சந்திரன்'),
    line: B('Solar and lunar eclipses — a traditional time for prayer, chanting and charity.', 'சூரிய, சந்திர கிரகணங்கள் — பிரார்த்தனை, ஜபம், தானத்துக்கான மரபு நேரம்.'),
    why: B('An eclipse happens when the Moon comes exactly between the Sun and Earth (solar) or the Earth’s shadow falls on the full Moon (lunar). The puranic story tells of Rahu, who drank nectar in disguise and was cut by Vishnu’s discus — his head is said to swallow the Sun or Moon briefly. Tradition treats the eclipse as a time to pause, chant and bathe afterwards; temples close and reopen after cleaning.',
      'சூரியனுக்கும் பூமிக்கும் நடுவே சந்திரன் நேராக வரும்போது சூரிய கிரகணம்; பூமியின் நிழல் முழு நிலவில் விழும்போது சந்திர கிரகணம். மாறுவேடத்தில் அமுதம் அருந்திய ராகுவைத் திருமாலின் சக்கரம் வெட்டியது; அவன் தலை சூரியனையோ சந்திரனையோ சிறிது நேரம் விழுங்குவதாகப் புராணம் சொல்கிறது. கிரகண நேரத்தில் நிதானித்து ஜபித்து, பின் நீராடுவது மரபு; கோவில்கள் மூடப்பட்டு சுத்தம் செய்த பின் திறக்கப்படும்.'),
    how: B(['During the eclipse: chant Gayatri or your family mantra; many avoid cooking and eating, but children, elderly people, diabetics and anyone on medicines should eat as needed.', 'After it ends: bath, light a lamp, give food or grains as dhanam.', 'Pregnant women traditionally rest indoors; there is no medical reason for fear — follow your doctor.', 'Never look at a solar eclipse with bare eyes — use certified eclipse glasses.'],
      ['கிரகணத்தின்போது: காயத்ரி அல்லது குடும்ப மந்திர ஜபம்; பலர் சமையல், உணவைத் தவிர்ப்பர் — ஆனால் குழந்தைகள், முதியவர்கள், சர்க்கரை நோயாளர், மருந்து எடுப்பவர்கள் தேவைக்கேற்ப உண்ணுங்கள்.', 'முடிந்த பின்: நீராடி, விளக்கேற்றி, உணவு அல்லது தானியம் தானம்.', 'கர்ப்பிணிகள் வீட்டுக்குள் ஓய்வெடுப்பது மரபு; பயப்பட மருத்துவக் காரணம் இல்லை — மருத்துவர் ஆலோசனைப்படி நடங்கள்.', 'சூரிய கிரகணத்தை வெறும் கண்ணால் பார்க்கவே வேண்டாம் — சான்றளிக்கப்பட்ட கிரகணக் கண்ணாடி பயன்படுத்துங்கள்.']),
    temples: ['kalahasti'],
    regional: B('Srikalahasti temple stays open during eclipses and holds special Rahu-Ketu pujas.', 'கிரகணத்தின்போதும் ஸ்ரீகாளஹஸ்தி கோவில் திறந்திருக்கும்; ராகு-கேது சிறப்புப் பூஜை.'), sources: SRC,
  },
  {
    id: 'star-birthday', kind: 'concept', personalNull: true,
    names: B('Star birthday (Natchathira Piranthanaal)', 'நட்சத்திரப் பிறந்தநாள்'),
    aliases: ['star birthday', 'natchathira birthday', 'natchathira piranthanaal', 'nakshatra birthday', 'janma nakshatra', 'jenma natchathiram', 'நட்சத்திரப் பிறந்தநாள்', 'நட்சத்திர பிறந்தநாள்', 'ஜென்ம நட்சத்திரம்'],
    line: B('Birthday by birth star in the birth Tamil month — the traditional Tamil birthday.', 'பிறந்த தமிழ் மாதத்தில் பிறந்த நட்சத்திரம் வரும் நாள் — மரபுவழித் தமிழ்ப் பிறந்தநாள்.'),
    whenText: B('It is the day in your birth Tamil month when the Moon is in your birth star. Open “Star birthday” in the app to see your family’s dates.', 'உங்கள் பிறந்த தமிழ் மாதத்தில் சந்திரன் உங்கள் பிறந்த நட்சத்திரத்தில் இருக்கும் நாள். செயலியில் "நட்சத்திரப் பிறந்தநாள்" பகுதியில் உங்கள் குடும்பத்தினரின் தேதிகளைப் பாருங்கள்.'),
    why: B('Tamil families traditionally celebrate the star birthday with temple archanai in the person’s name and star, new clothes and sweets; for elders it is the basis of the 60th and 80th celebrations.', 'நபரின் பெயர், நட்சத்திரத்தில் கோவில் அர்ச்சனை, புத்தாடை, இனிப்புடன் நட்சத்திரப் பிறந்தநாள் கொண்டாடுவது தமிழ் மரபு; பெரியவர்களுக்கு 60, 80-ஆம் விழாக்களுக்கும் இதுவே அடிப்படை.'),
    how: B(['Oil bath, new clothes, archanai with name–star–gothram, blessings of elders, feed someone in need.'], ['எண்ணெய்க் குளியல், புத்தாடை, பெயர்-நட்சத்திரம்-கோத்திரத்துடன் அர்ச்சனை, பெரியவர் ஆசி, ஒருவருக்கு அன்னம்.']),
    see: ['shashtiabdapoorthi'], sources: SRC,
  },
  {
    id: 'shashtiabdapoorthi', kind: 'concept',
    names: B('Shashtiabdapoorthi (60th)', 'சஷ்டியப்தபூர்த்தி (60-ஆம் கல்யாணம்)'),
    aliases: ['shashtiabdapoorthi', 'sashtiapthapoorthi', 'shashti poorthi', 'sashti poorthi', '60th kalyanam', 'manivizha', 'arupatham kalyanam', 'sashtiabdapurthi', 'சஷ்டியப்தபூர்த்தி', 'சஷ்டியப்த பூர்த்தி', 'அறுபதாம் கல்யாணம்', 'மணிவிழா', '60ஆம் கல்யாணம்'],
    deity: B('Mrityunjaya (Shiva), Abhirami — Thirukadaiyur', 'மிருத்யுஞ்ஜயர் (சிவன்), அபிராமி — திருக்கடையூர்'),
    line: B('Completion of 60 years — the couple renew their wedding vows with family blessings.', '60 ஆண்டு நிறைவு — குடும்ப ஆசியுடன் தம்பதிகள் மீண்டும் திருமணம்.'),
    whenText: B('When the husband completes 60 years — traditionally on his birth star in his birth Tamil month in the 61st year (the 60-year cycle returns to his birth year name). See “Star birthday & 60th / 80th”.', 'கணவர் 60 ஆண்டு நிறைவு செய்யும்போது — மரபுப்படி 61-ஆம் வயதில் பிறந்த தமிழ் மாதத்தில் பிறந்த நட்சத்திர நாளில் (60 ஆண்டுச் சுழற்சி பிறந்த ஆண்டுப் பெயருக்குத் திரும்புகிறது). "நட்சத்திரப் பிறந்தநாள் & சஷ்டியப்தபூர்த்தி" பகுதியைப் பாருங்கள்.'),
    why: B('After 60 years the Tamil year cycle returns to the year of birth — a full circle of life. The couple, who have lived through a full cycle together, thank God and renew their bond; children and grandchildren take part. Thirukadaiyur, where Shiva protected Markandeya, is the favourite place.', '60 ஆண்டுகளில் தமிழ் ஆண்டுச் சுழற்சி பிறந்த ஆண்டுக்கே திரும்புகிறது — வாழ்வின் ஒரு முழு வட்டம். ஒன்றாக ஒரு சுழற்சி வாழ்ந்த தம்பதிகள் இறைவனுக்கு நன்றி சொல்லிப் பிணைப்பைப் புதுப்பிப்பர்; பிள்ளைகளும் பேரப்பிள்ளைகளும் பங்கேற்பர். மார்க்கண்டேயனைச் சிவன் காத்த திருக்கடையூர் விருப்பமான தலம்.'),
    how: B(['Ayushya homam and Mrityunjaya homam, kalasa abhishekam for the couple, mangalya dharanam, blessings of elders and children.', 'Keep it simple and comfortable for the elders — a temple archanai with family is also complete.'], ['ஆயுஷ்ய ஹோமம், மிருத்யுஞ்ஜய ஹோமம், தம்பதிக்குக் கலச அபிஷேகம், மாங்கல்ய தாரணம், பெரியவர்-பிள்ளைகள் ஆசி.', 'பெரியவர்களுக்கு வசதியாக எளிமையாக வையுங்கள் — குடும்பத்துடன் கோவில் அர்ச்சனையும் முழுமையானதே.']),
    mantra: 'mrityunjaya',
    temples: ['thirukadaiyur'],
    extra: [{ key: 'milestones', title: B('Other milestones', 'பிற விழாக்கள்'), lines: B(['Bheemaratha Shanti — 70 years.', 'Sathabishekam — 80 years (after seeing 1,000 full moons).', 'Kanakabhishekam / Poorna abhishekam — 90 and 100 years.'], ['பீமரத சாந்தி — 70 வயது.', 'சதாபிஷேகம் — 80 வயது (ஆயிரம் பிறை கண்ட பின்).', 'கனகாபிஷேகம் / பூர்ணாபிஷேகம் — 90, 100 வயது.']) }],
    see: ['star-birthday', 'sathabishekam'], sources: SRC,
  },
  {
    id: 'sathabishekam', kind: 'concept', mantra: 'mrityunjaya',
    names: B('Sathabishekam (80th)', 'சதாபிஷேகம் (80-ஆம் விழா)'),
    aliases: ['sathabishekam', 'sadabhishekam', 'sathabhishekam', '80th birthday', 'aayiram pirai', 'சதாபிஷேகம்', 'ஆயிரம் பிறை'],
    line: B('Celebrating 80 years — having seen a thousand full moons.', '80 ஆண்டு நிறைவு — ஆயிரம் பிறை கண்ட விழா.'),
    whenText: B('Traditionally after the 1,000th full moon of life, around age 80–81, on the birth star. See “Star birthday & 60th / 80th”.', 'வாழ்வின் 1,000-ஆவது பௌர்ணமிக்குப் பின், ஏறக்குறைய 80–81 வயதில், பிறந்த நட்சத்திர நாளில். "நட்சத்திரப் பிறந்தநாள் & சஷ்டியப்தபூர்த்தி" பகுதியைப் பாருங்கள்.'),
    why: B('Seeing a thousand full moons is considered a great blessing; the family honours the elders with abhishekam and seeks their blessings.', 'ஆயிரம் பௌர்ணமிகள் காண்பது பெரும் பேறு; குடும்பம் பெரியவர்களுக்கு அபிஷேகம் செய்து ஆசி பெறும்.'),
    how: B(['Homam and kalasa abhishekam for the couple; family blessings; keep it gentle for their health.'], ['ஹோமம், தம்பதிக்குக் கலச அபிஷேகம்; குடும்ப ஆசி; அவர்கள் உடல்நலத்துக்கு ஏற்ப மென்மையாக.']),
    temples: ['thirukadaiyur'], sources: SRC,
  },
  {
    id: 'viratham', kind: 'concept', needIntent: true, fast: true,
    names: B('Viratham (fasting) — general', 'விரதம் — பொது'),
    aliases: ['viratham', 'vratham', 'vrat', 'upavasam', 'fasting rules', 'nombu', 'nonbu', 'விரதம்', 'உபவாசம்', 'நோன்பு'],
    line: B('A vow of discipline and prayer — the heart of it is the mind, not hunger.', 'கட்டுப்பாடும் பிரார்த்தனையும் கொண்ட வாக்கு — அதன் மையம் மனம், பசி அல்ல.'),
    why: B('A viratham is a sankalpam (resolve) to spend a day close to God — eating simply, speaking kindly and praying. Tradition values the intention more than the severity; a light meal with devotion is a complete viratham.', 'விரதம் என்பது இறைவனுக்கு அருகில் ஒரு நாள் செலவழிக்கும் சங்கல்பம் — எளிய உணவு, இனிய பேச்சு, பிரார்த்தனை. கடுமையை விட எண்ணத்தையே மரபு மதிக்கிறது; பக்தியுடன் லேசான உணவும் முழு விரதமே.'),
    how: B(['Take a sankalpam in the morning after bathing; choose a level that suits your health — one meal, fruit and milk, or no change in food but extra prayer.', 'Drink enough water unless you are healthy and used to a nirjala fast.', 'Break the fast at the right time with simple food; share food with someone.'],
      ['காலை நீராடிய பின் சங்கல்பம்; உடல்நிலைக்கு ஏற்ற நிலை — ஒருவேளை உணவு, பழம்-பால், அல்லது உணவில் மாற்றமின்றிக் கூடுதல் பிரார்த்தனை.', 'ஆரோக்கியமாகவும் பழக்கமாகவும் இருந்தாலன்றி போதுமான தண்ணீர் அருந்துங்கள்.', 'உரிய நேரத்தில் எளிய உணவுடன் விரதம் முடித்து, ஒருவருடன் பகிருங்கள்.']),
    see: ['ekadasi', 'sashti', 'pradosham'], sources: SRC,
  },
  {
    id: 'thivasam', kind: 'concept', needIntent: true,
    names: B('Thivasam / Tharpanam', 'திவசம் / தர்ப்பணம்'),
    aliases: ['thivasam', 'dhivasam', 'tharpanam', 'tarpanam', 'shraddham', 'sraddha', 'thithi kodukka', 'திவசம்', 'தர்ப்பணம்', 'சிராத்தம்'],
    deity: B('Ancestors (pitrus)', 'முன்னோர்கள்'),
    line: B('Remembering departed parents on their tithi with tharpanam and food for others.', 'மறைந்த பெற்றோரை அவர் திதியில் தர்ப்பணம், அன்னதானத்துடன் நினைத்தல்.'),
    whenText: B('Thivasam is on the same tithi (and Tamil month) as the day the person passed away. Use the “Thivasam / tharpanam” screen to find the next date.', 'மறைந்த நாளின் அதே தமிழ் மாதத் திதியில் திவசம். அடுத்த தேதிக்கு "திவசம் / தர்ப்பணம்" பகுதியைப் பாருங்கள்.'),
    why: B('Tradition teaches that remembering ancestors with gratitude and feeding others in their name keeps the family line blessed. Amavasai, Mahalaya Paksham and month-start days are also for tharpanam.', 'நன்றியுடன் முன்னோரை நினைத்து அவர்கள் பெயரில் பிறருக்கு உணவளிப்பது குடும்ப வழியை ஆசீர்வதிக்கும் என்பது மரபு. அமாவாசை, மகாளய பட்சம், மாதப் பிறப்பும் தர்ப்பணத்துக்கு உரியவை.'),
    how: B(['Follow your family’s custom with a priest; if that is not possible, offer water and sesame with a prayer, and feed someone in need.'], ['புரோகிதருடன் குடும்ப வழக்கப்படி; முடியாவிட்டால் பிரார்த்தனையுடன் எள்-நீர் அளித்து, தேவையுள்ள ஒருவருக்கு உணவளியுங்கள்.']),
    see: ['amavasai', 'mahalaya-paksham'], sources: SRC,
  },
  {
    id: 'kula-deivam', kind: 'concept', needIntent: true,
    names: B('Kula Deivam (family deity)', 'குலதெய்வம்'),
    aliases: ['kula deivam', 'kuladeivam', 'kula theivam', 'family deity', 'kula deivam vazhipadu', 'குலதெய்வம்', 'குல தெய்வம்'],
    line: B('The family’s ancestral deity — known from family memory, not from a horoscope.', 'குடும்பத்தின் பரம்பரைத் தெய்வம் — கட்டத்தால் அல்ல, குடும்ப நினைவால் அறியப்படுவது.'),
    why: B('Each Tamil family traditionally has a Kula Deivam — often Ayyanar, Karuppasamy, Amman, Murugan or Perumal at the ancestral village. Visiting at least once a year, especially before family events, keeps the bond with one’s roots.', 'ஒவ்வொரு தமிழ்க் குடும்பத்துக்கும் பரம்பரைக் கிராமத்தில் குலதெய்வம் உண்டு — பெரும்பாலும் ஐயனார், கருப்பசாமி, அம்மன், முருகன் அல்லது பெருமாள். ஆண்டுக்கு ஒருமுறையாவது, குறிப்பாகக் குடும்ப விழாக்களுக்கு முன், செல்வது வேர்களுடன் பிணைப்பைக் காக்கும்.'),
    how: B(['Ask the eldest relatives or the native village temple; if it cannot be known, pray to Vinayagar or your favourite deity as Kula Deivam — tradition accepts that.', 'Panguni Uthiram and Maha Sivaratri are popular days for Kula Deivam visits.'], ['மூத்த உறவினர்களிடம் அல்லது சொந்த ஊர்க் கோவிலில் கேளுங்கள்; அறிய முடியாவிட்டால் விநாயகரையோ விருப்பத் தெய்வத்தையோ குலதெய்வமாக வழிபடலாம் — மரபு அதை ஏற்கிறது.', 'பங்குனி உத்திரம், மகா சிவராத்திரி குலதெய்வ வழிபாட்டுக்குப் பிரபலமான நாட்கள்.']),
    sources: SRC,
  },
  {
    id: 'brahma-muhurtham', kind: 'concept', needIntent: true,
    names: B('Brahma Muhurtham', 'பிரம்ம முகூர்த்தம்'),
    aliases: ['brahma muhurtham', 'brahma muhurta', 'bramma muhurtham', 'பிரம்ம முகூர்த்தம்'],
    line: B('The 48 minutes ending about 48 minutes before sunrise — best for prayer and study.', 'சூரிய உதயத்துக்குச் சுமார் 48 நிமிடம் முன் முடியும் 48 நிமிடம் — வழிபாடு, படிப்புக்குச் சிறந்தது.'),
    why: B('In the stillness before dawn the mind is fresh and calm; tradition calls this time ideal for meditation, prayer, kolam and study.', 'விடியலுக்கு முந்தைய அமைதியில் மனம் புத்துணர்வுடனும் நிதானத்துடனும் இருக்கும்; தியானம், பிரார்த்தனை, கோலம், படிப்புக்கு உகந்த நேரம் என்கிறது மரபு.'),
    how: B(['Wake about 1½ hours before sunrise, wash, light a lamp, sit quietly or chant for a few minutes.'], ['சூரிய உதயத்துக்குச் சுமார் 1½ மணி முன் எழுந்து, முகம் கழுவி, விளக்கேற்றி, சில நிமிடம் அமைதியாக அமருங்கள் அல்லது ஜபியுங்கள்.']),
    sources: SRC,
  },
  {
    id: 'vilakku', kind: 'concept', needIntent: true, mantra: 'lakshmi',
    names: B('Lighting the lamp (Vilakku)', 'விளக்கேற்றும் முறை'),
    aliases: ['vilakku', 'vilakketral', 'vilakku etrum murai', 'deepam etruvadhu', 'lamp lighting', 'kuthu vilakku', 'agal vilakku', 'விளக்கு', 'விளக்கேற்றும் முறை', 'குத்துவிளக்கு', 'விளக்கேற்றல்'],
    line: B('Lighting the home lamp morning and evening — the simplest daily worship.', 'காலை, மாலை வீட்டில் விளக்கேற்றுதல் — எளிய அன்றாட வழிபாடு.'),
    why: B('The lamp stands for knowledge driving away darkness. Lighting it at dawn and at dusk (sandhya time) is believed to welcome Lakshmi and peace into the home.', 'அறியாமை இருளை நீக்கும் அறிவின் அடையாளம் விளக்கு. விடியலிலும் அந்தியிலும் (சந்தியா நேரம்) ஏற்றுவது வீட்டுக்கு லட்சுமியையும் அமைதியையும் வரவேற்கும் என்பது நம்பிக்கை.'),
    how: B(['Use sesame oil or ghee; one wick is fine, two wicks facing east and north are common; avoid facing south.', 'Light at sunrise and around sunset; say a short prayer; never blow it out — let it go out on its own or gently close with a flower.', 'Keep the lamp stable and away from curtains and children.'],
      ['நல்லெண்ணெய் அல்லது நெய்; ஒரு திரி போதும், கிழக்கு-வடக்கு நோக்கி இரு திரி வழக்கம்; தெற்கு நோக்கித் தவிர்ப்பர்.', 'சூரிய உதயத்திலும் அஸ்தமனத்தை ஒட்டியும் ஏற்றி சிறு பிரார்த்தனை; ஊதி அணைக்க வேண்டாம் — தானாக அணையட்டும் அல்லது மலரால் மெதுவாக மூடுங்கள்.', 'விளக்கை உறுதியாக, திரைச்சீலை, குழந்தைகளிடமிருந்து விலக்கி வையுங்கள்.']),
    sources: SRC,
  },
  {
    id: 'tulasi', kind: 'concept', needIntent: true, mantra: 'narayana',
    names: B('Tulasi worship', 'துளசி வழிபாடு'),
    aliases: ['tulasi', 'thulasi', 'tulsi', 'tulasi pooja', 'tulasi kalyanam', 'துளசி', 'துளசி பூஜை', 'துளசி கல்யாணம்'],
    deity: B('Tulasi Devi, Lord Vishnu', 'துளசி தேவி, திருமால்'),
    line: B('The sacred basil, dear to Vishnu — watered and circled daily in many homes.', 'திருமாலுக்கு உகந்த புனிதத் துளசி — பல வீடுகளில் தினமும் நீர் ஊற்றி வலம் வருவர்.'),
    why: B('Tulasi is worshipped as a form of Lakshmi; no Vishnu pooja is complete without a tulasi leaf. Tulasi Kalyanam (her marriage to Vishnu) is celebrated after Prabodhini Ekadasi.', 'துளசி லட்சுமியின் வடிவமாக வழிபடப்படுகிறது; துளசியின்றித் திருமால் பூஜை முழுமையாகாது. பிரபோதினி ஏகாதசிக்குப் பின் துளசி கல்யாணம் கொண்டாடப்படுகிறது.'),
    how: B(['Water the plant in the morning, light a lamp near it in the evening, circle it three times.', 'Tradition avoids plucking tulasi on Dwadasi, Amavasai and Sundays — pluck the day before.'], ['காலையில் நீர் ஊற்றி, மாலையில் அருகில் விளக்கேற்றி, மூன்று முறை வலம் வருதல்.', 'துவாதசி, அமாவாசை, ஞாயிறு அன்று துளசி பறிப்பதை மரபு தவிர்க்கிறது — முந்தைய நாளே பறியுங்கள்.']),
    sources: SRC,
  },
  {
    id: 'chaturmasya', kind: 'concept', needIntent: true,
    names: B('Chaturmasya', 'சாதுர்மாஸ்யம்'),
    aliases: ['chaturmasya', 'chathurmasyam', 'chaturmas', 'சாதுர்மாஸ்யம்'],
    line: B('Four sacred months of Vishnu’s yoga-sleep, from Shayani to Prabodhini Ekadasi.', 'சயனி ஏகாதசி முதல் பிரபோதினி ஏகாதசி வரை திருமாலின் யோக நித்திரையின் நான்கு புனித மாதங்கள்.'),
    why: B('During the monsoon months sannyasis stay in one place and householders take small vows of simple living — a time for inner discipline.', 'மழைக்கால மாதங்களில் சன்னியாசிகள் ஓரிடத்தில் தங்குவர்; இல்லறத்தார் எளிய வாழ்க்கைக்குச் சிறு விரதங்கள் கொள்வர் — உள் ஒழுக்கத்துக்கான காலம்.'),
    how: B(['Pick one small vow — a daily prayer, giving up one food, reading a sacred text.'], ['ஒரு சிறு வாக்கு — தினசரிப் பிரார்த்தனை, ஒரு உணவைத் தவிர்த்தல், புனித நூல் படித்தல்.']),
    see: ['ekadasi-shayani', 'ekadasi-prabodhini'], sources: SRC,
  },
];
