// Annual festivals, Thai → Aani (January → July). Months: solar 0 = Chithirai … 9 = Thai; lunar 0 = Chaitra … 10 = Magha.
import { B, SRC } from './common.js';

export const FESTIVALS_A = [
  {
    id: 'bhogi', kind: 'festival',
    names: B('Bhogi', 'போகி'),
    aliases: ['bhogi', 'bogi', 'bhogi pongal', 'போகி', 'போகிப் பண்டிகை'],
    deity: B('Indra (giver of rain)', 'இந்திரன் (மழை தருபவர்)'),
    rule: { offset: 'thai-pongal', days: -1 },
    ruleText: B('the last day of Margazhi, the day before Thai Pongal.', 'மார்கழி கடைசி நாள், தைப் பொங்கலுக்கு முந்தைய நாள்.'),
    line: B('Out with the old — cleaning the home and welcoming Thai.', '"பழையன கழிதலும் புதியன புகுதலும்" — வீட்டைச் சுத்தம் செய்து தையை வரவேற்கும் நாள்.'),
    why: B('Bhogi thanks Indra for the rains that made the harvest possible and marks letting go of the old — old things and old grudges — before the new month. Homes are cleaned, painted and decorated with kolam and kaappu (neem, avaram, mango leaves).',
      'அறுவடைக்கு மழை தந்த இந்திரனுக்கு நன்றி செலுத்தும் நாள்; புதிய மாதத்துக்கு முன் பழைய பொருட்களையும் பழைய மனக்கசப்புகளையும் விட்டுவிடுவதைக் குறிக்கிறது. வீடுகள் சுத்தம் செய்யப்பட்டு, கோலமிட்டு, வேம்பு-ஆவாரம்-மாவிலைக் காப்பு கட்டப்படுகின்றன.'),
    how: B(['Clean the house and give away usable old things.', 'Tie kaappu (neem, avaram poo, mango leaves) at the entrance.', 'Avoid burning plastic or tyres — it harms health; a small symbolic fire of dry leaves is enough.'],
      ['வீட்டைச் சுத்தம் செய்து, பயன்படும் பழைய பொருட்களைத் தேவையுள்ளவர்களுக்குக் கொடுங்கள்.', 'வாசலில் வேம்பு, ஆவாரம்பூ, மாவிலைக் காப்பு கட்டுங்கள்.', 'பிளாஸ்டிக், டயர் எரிக்க வேண்டாம் — உடல்நலத்துக்குக் கேடு; காய்ந்த இலைகளில் சிறு அடையாள நெருப்பு போதும்.']),
    offer: B('Poli (sweet flatbread), vadai, payasam.', 'போளி, வடை, பாயசம்.'),
    regional: B('Called Lohri in Punjab (fire festival), Bhogi in Andhra Pradesh too.', 'பஞ்சாபில் லோஹ்ரி, ஆந்திராவிலும் போகி.'),
    see: ['thai-pongal'], sources: SRC,
  },
  {
    id: 'thai-pongal', kind: 'festival', mantra: 'gayatri',
    names: B('Thai Pongal', 'தைப் பொங்கல்'),
    aliases: ['pongal', 'thai pongal', 'thaipongal', 'surya pongal', 'makara sankranti', 'makar sankranti', 'sankranthi', 'tamizhar thirunal', 'பொங்கல்', 'தைப் பொங்கல்', 'தை பொங்கல்', 'தமிழர் திருநாள்', 'மகர சங்கராந்தி'],
    deity: B('Surya (the Sun)', 'சூரிய பகவான்'),
    rule: { solarDay: [9, 1] },
    ruleText: B('Thai 1 — the day the Sun enters Makara (Capricorn) rasi (next day if it enters after sunset).', 'தை 1 — சூரியன் மகர ராசியில் நுழையும் நாள் (அஸ்தமனத்துக்குப் பின் நுழைந்தால் மறுநாள்).'),
    line: B('Harvest thanksgiving to the Sun — the Tamil festival of the year.', 'சூரியனுக்கு அறுவடை நன்றி — தமிழர் திருநாள்.'),
    why: B('Pongal thanks the Sun, the earth, rain and cattle for the harvest. It marks Uttarayanam, the Sun’s northward journey, which tradition calls the devas’ daytime. “Thai pirandhal vazhi pirakkum” — with Thai, a way opens — expresses hope for the new season.',
      'அறுவடைக்காகச் சூரியன், நிலம், மழை, கால்நடைகளுக்கு நன்றி சொல்லும் திருநாள். சூரியனின் வடதிசைப் பயணமான உத்தராயணம் தொடங்குவதையும் குறிக்கிறது — இது தேவர்களின் பகல் என்பது மரபு. "தை பிறந்தால் வழி பிறக்கும்" — புதிய பருவத்தின் நம்பிக்கை.'),
    story: B('In the Sangam age the month of Thai was celebrated with “Thai neeradal” — bathing in rivers and praying for good rains and harvest. The new rice from the fields is cooked in a new pot until it boils over (pongal), a sign of abundance; everyone calls out “Pongalo Pongal!”.',
      'சங்க காலத்திலேயே தை மாதம் "தை நீராடல்" மூலம் கொண்டாடப்பட்டது — ஆறுகளில் நீராடி நல்ல மழை, விளைச்சலுக்கு வேண்டினர். வயலின் புது அரிசியைப் புதுப் பானையில் பொங்கி வழியும் வரை சமைப்பது செழிப்பின் அடையாளம்; அனைவரும் "பொங்கலோ பொங்கல்!" என்று முழங்குவர்.'),
    how: B(['Draw a kolam and set up the hearth facing the Sun in the courtyard if possible.', 'Tie turmeric and ginger plants around a new pot; cook sakkarai pongal with new rice, jaggery, milk and ghee.', 'When it boils over, call “Pongalo Pongal”; offer to the Sun with sugarcane, banana and turmeric.', 'Share with neighbours and family.'],
      ['கோலமிட்டு, முடிந்தால் முற்றத்தில் சூரியனை நோக்கி அடுப்பு அமையுங்கள்.', 'புதுப் பானையில் மஞ்சள், இஞ்சிக் கொத்து கட்டி, புது அரிசி, வெல்லம், பால், நெய் கொண்டு சர்க்கரைப் பொங்கல் சமையுங்கள்.', 'பொங்கி வழியும்போது "பொங்கலோ பொங்கல்" என்று சொல்லி, கரும்பு, வாழை, மஞ்சளுடன் சூரியனுக்குப் படையுங்கள்.', 'அக்கம்பக்கத்தாருடனும் குடும்பத்துடனும் பகிருங்கள்.']),
    offer: B('Sakkarai pongal, ven pongal, sugarcane, banana, turmeric plant, vegetables of the season.', 'சர்க்கரைப் பொங்கல், வெண் பொங்கல், கரும்பு, வாழை, மஞ்சள் கொத்து, பருவக் காய்கறிகள்.'),
    temples: ['suriyanar'],
    regional: B('Makar Sankranti across India (kites in Gujarat, til-gul in Maharashtra); Sabarimala Makaravilakku is the same evening.', 'இந்தியா முழுவதும் மகர சங்கராந்தி (குஜராத்தில் பட்டம், மகாராஷ்டிராவில் எள்-வெல்லம்); சபரிமலை மகரவிளக்கும் அதே மாலை.'),
    see: ['bhogi', 'mattu-pongal', 'kaanum-pongal'], sources: SRC,
  },
  {
    id: 'mattu-pongal', kind: 'festival',
    names: B('Mattu Pongal', 'மாட்டுப் பொங்கல்'),
    aliases: ['mattu pongal', 'maatu pongal', 'kanu pidi', 'kanu', 'மாட்டுப் பொங்கல்', 'மாட்டு பொங்கல்', 'கனு', 'கனுப் பிடி'],
    deity: B('Cattle (Gomatha), Nandi', 'பசுக்கள் (கோமாதா), நந்தி'),
    rule: { solarDay: [9, 2] },
    ruleText: B('Thai 2, the day after Pongal.', 'தை 2, பொங்கலுக்கு மறுநாள்.'),
    line: B('Thanking the cattle who work the fields; sisters pray for brothers (Kanu).', 'உழவுக்குத் துணையான மாடுகளுக்கு நன்றி; சகோதரிகள் சகோதரர்களுக்காக வேண்டும் கனு.'),
    why: B('Cattle are partners in farming; on Mattu Pongal they are bathed, horns painted, decorated with bells and garlands, and fed pongal. Women also observe Kanu Pidi, placing coloured rice balls for birds and praying for their brothers’ welfare.',
      'உழவில் மாடுகள் கூட்டாளிகள்; அன்று அவற்றை நீராட்டி, கொம்புகளுக்கு வண்ணம் பூசி, மணி, மாலை அணிவித்து, பொங்கல் ஊட்டுவர். பெண்கள் "கனுப் பிடி" வைத்து — பறவைகளுக்கு வண்ணச் சாத உருண்டைகள் வைத்து — சகோதரர் நலனுக்கு வேண்டுவர்.'),
    how: B(['Bathe and decorate cows and bulls; feed them pongal, bananas and sugarcane.', 'Kanu pidi: place small balls of turmeric/kumkum/curd rice on a leaf for crows and birds.', 'Treat animals gently — avoid any event that hurts them.'],
      ['பசு, காளைகளை நீராட்டி அலங்கரித்து பொங்கல், வாழை, கரும்பு ஊட்டுங்கள்.', 'கனுப் பிடி: மஞ்சள்/குங்கும/தயிர் சாத உருண்டைகளை இலையில் வைத்துக் காக்கை, பறவைகளுக்குப் படையுங்கள்.', 'விலங்குகளை அன்புடன் நடத்துங்கள் — அவற்றுக்குத் துன்பம் தரும் எதையும் தவிர்க்கவும்.']),
    offer: B('Pongal, banana, sugarcane, agathi keerai for cows.', 'பொங்கல், வாழை, கரும்பு, பசுவுக்கு அகத்திக் கீரை.'),
    regional: B('Jallikattu events are held in parts of Tamil Nadu around this day under state regulations.', 'தமிழ்நாட்டின் சில பகுதிகளில் இந்நாளை ஒட்டி அரசு விதிமுறைகளுடன் ஜல்லிக்கட்டு நடைபெறும்.'),
    sources: SRC,
  },
  {
    id: 'kaanum-pongal', kind: 'festival',
    names: B('Kaanum Pongal', 'காணும் பொங்கல்'),
    aliases: ['kaanum pongal', 'kanum pongal', 'kannu pongal', 'காணும் பொங்கல்'],
    rule: { solarDay: [9, 3] },
    ruleText: B('Thai 3.', 'தை 3.'),
    line: B('Visiting relatives and elders, outings with family.', 'உறவினர், பெரியவர்களைச் சந்தித்தல், குடும்பச் சுற்றுலா.'),
    why: B('“Kaanum” means to see: the day is for visiting relatives, taking elders’ blessings and spending time together outdoors, strengthening family bonds after the harvest.', '"காணும்" என்றால் சந்திப்பது: உறவினர்களைப் பார்த்து, பெரியவர்களிடம் ஆசி பெற்று, வெளியில் ஒன்றாக நேரம் செலவழித்து, அறுவடைக்குப் பின் குடும்பப் பிணைப்பை வலுப்படுத்தும் நாள்.'),
    how: B(['Visit elders and take their blessings; picnic with family; younger ones may receive small gifts.'], ['பெரியவர்களைச் சந்தித்து ஆசி பெறுங்கள்; குடும்பத்துடன் சுற்றுலா; சிறியவர்களுக்குச் சிறு பரிசுகள்.']),
    offer: B('Kalanda sadham (mixed rice varieties) carried for outings.', 'சுற்றுலாவுக்குக் கலந்த சாத வகைகள்.'), sources: SRC,
  },
  {
    id: 'thai-velli', kind: 'vratham', mantra: 'lakshmi',
    names: B('Thai Fridays', 'தை வெள்ளி'),
    aliases: ['thai velli', 'thai friday', 'தை வெள்ளி', 'தை வெள்ளிக்கிழமை'],
    deity: B('Amman, Mahalakshmi', 'அம்மன், மகாலட்சுமி'),
    rule: { weekly: 5, solar: [9] },
    ruleText: B('every Friday in the Tamil month of Thai.', 'தை மாதத்தின் ஒவ்வொரு வெள்ளிக்கிழமையும்.'),
    line: B('Fridays of Thai for Amman and Lakshmi worship.', 'அம்மன், லட்சுமி வழிபாட்டுக்கான தை வெள்ளிகள்.'),
    why: B('Like Aadi Fridays, Thai Fridays are considered auspicious for Amman temples and for married women praying for family welfare.', 'ஆடி வெள்ளி போலவே தை வெள்ளியும் அம்மன் கோவில் வழிபாட்டுக்கும் குடும்ப நலனுக்காக வேண்டும் சுமங்கலிகளுக்கும் உகந்தது.'),
    how: B(['Light a lamp, offer flowers and kumkum to Amman; visit an Amman temple.'], ['விளக்கேற்றி அம்மனுக்கு மலர், குங்குமம் சமர்ப்பியுங்கள்; அம்மன் கோவில் தரிசனம்.']),
    temples: ['samayapuram', 'mangadu_kamakshi', 'thiruverkadu'], sources: SRC,
  },
  {
    id: 'thai-poosam', kind: 'festival', fast: true, mantra: 'murugan',
    names: B('Thai Poosam', 'தைப்பூசம்'),
    aliases: ['thai poosam', 'thaipoosam', 'thaipusam', 'thai pusam', 'poosam', 'தைப்பூசம்', 'தை பூசம்'],
    deity: B('Lord Murugan', 'முருகப் பெருமான்'),
    rule: { star: 7, solar: [9], twice: 'pournami' },
    ruleText: B('Poosam (Pushya) star at sunrise in the Tamil month of Thai — usually near the full moon.', 'தை மாதத்தில் சூரிய உதயத்தில் பூச நட்சத்திரம் — பெரும்பாலும் பௌர்ணமி அருகே.'),
    line: B('Murugan’s festival of the Vel — kavadi and paal kudam to Palani.', 'வேலின் விழா — பழனிக்குக் காவடி, பால் குடம்.'),
    why: B('Thai Poosam celebrates the day Goddess Parvati gave the Vel (divine spear) to Murugan to defeat Soorapadman. Devotees carry kavadi or milk pots as a vow of gratitude, walking to Palani and other Murugan shrines. The Vel stands for sharp wisdom that cuts ignorance.',
      'சூரபத்மனை வெல்லப் பார்வதி தேவி முருகனுக்கு வேல் வழங்கிய நாள் தைப்பூசம். நன்றிக் கடனாகப் பக்தர்கள் காவடி, பால் குடம் ஏந்தி, பழனி போன்ற முருகன் தலங்களுக்குப் பாதயாத்திரை செல்வர். வேல் அறியாமையை அறுக்கும் கூர்மையான ஞானத்தின் அடையாளம்.'),
    story: B('The Kavadi tradition is traced to Idumban, a devotee of Agastya, who was asked to carry two hills on a pole to the south. At Palani the load would not move — young Murugan stood atop one hill. After Idumban yielded, Murugan blessed that anyone who brings a kavadi to Him in devotion would be blessed — hence the kavadi.',
      'அகத்தியரின் சீடன் இடும்பன் இரு மலைகளைத் தோளில் காவடியாகச் சுமந்து தெற்கே சென்றான். பழனியில் சுமை நகரவில்லை — ஒரு மலை மேல் சிறுவன் முருகன் நின்றிருந்தார். இடும்பன் பணிந்ததும், பக்தியுடன் காவடி கொண்டு வருவோருக்கு அருள்வதாக முருகன் வரம் தந்தார் — அதுவே காவடியின் தொடக்கம்.'),
    how: B(['Many keep a mandala (up to 48 days) of simple living before; even one day of prayer is enough.', 'Carry a small kavadi or paal kudam only as your health allows; walk with water and rest breaks.', 'Chant "Om Saravanabhava" or Kanda Sashti Kavasam; visit a Murugan temple.'],
      ['பலர் முன்கூட்டியே ஒரு மண்டலம் (48 நாள் வரை) எளிய வாழ்க்கை வாழ்வர்; ஒரு நாள் பிரார்த்தனையும் போதும்.', 'உடல்நிலைக்கு ஏற்ப மட்டும் சிறு காவடி அல்லது பால் குடம்; தண்ணீர், ஓய்வுடன் நடங்கள்.', '"ஓம் சரவணபவ" அல்லது கந்த சஷ்டி கவசம்; முருகன் கோவில் தரிசனம்.']),
    offer: B('Milk, panchamritam (Palani style), honey, fruits, yellow and red flowers.', 'பால், பஞ்சாமிர்தம் (பழனி), தேன், பழங்கள், மஞ்சள்-சிவப்பு மலர்கள்.'),
    temples: ['palani', 'tiruchendur', 'swamimalai', 'batu_caves', 'sg_thendayuthapani'],
    regional: B('Huge in Malaysia (Batu Caves), Singapore and Mauritius; at Vadalur the Jyothi darshan of Vallalar is held on this day.', 'மலேசியா (பத்துமலை), சிங்கப்பூர், மொரீஷியஸில் மிகப் பெரியது; வடலூரில் வள்ளலார் ஜோதி தரிசனம் இந்நாளில்.'),
    sources: SRC,
  },
  {
    id: 'thai-amavasai', kind: 'festival', mantra: 'shiva',
    names: B('Thai Amavasai', 'தை அமாவாசை'),
    aliases: ['thai amavasai', 'thai amavasya', 'தை அமாவாசை'],
    deity: B('Ancestors (pitrus)', 'முன்னோர்கள்'),
    rule: { tithi: 29, at: 'sunrise', solar: [9] },
    ruleText: B('the Amavasai that falls in the Tamil month of Thai.', 'தை மாதத்தில் வரும் அமாவாசை.'),
    line: B('One of the three great Amavasais for ancestors’ tharpanam.', 'முன்னோர் தர்ப்பணத்துக்கான மூன்று பெரிய அமாவாசைகளில் ஒன்று.'),
    why: B('Coming at the start of Uttarayanam, Thai Amavasai is considered especially fruitful for tharpanam; crowds gather at Rameswaram, Kanyakumari and river banks. At Thirukadaiyur, Abhirami Bhattar’s devotion made the new moon shine as a full moon on this day, according to the story.',
      'உத்தராயணத் தொடக்கத்தில் வருவதால் தை அமாவாசை தர்ப்பணத்துக்கு மிகுந்த பலன் தரும் என்பது நம்பிக்கை; ராமேஸ்வரம், கன்னியாகுமரி, நதிக்கரைகளில் மக்கள் கூடுவர். திருக்கடையூரில் அபிராமிப் பட்டரின் பக்திக்காக அன்னை இந்நாளில் அமாவாசையைப் பௌர்ணமியாக்கினாள் என்பது வரலாறு.'),
    how: B(['Holy bath; tharpanam with sesame and water for ancestors (with a priest or elder).', 'Feed the needy, crows and cows; light a lamp in the evening.'], ['புனித நீராடல்; புரோகிதர்/பெரியவர் வழிகாட்டலில் எள்-நீர் தர்ப்பணம்.', 'ஏழைகள், காக்கை, பசுவுக்கு உணவு; மாலையில் விளக்கேற்றல்.']),
    offer: B('Sesame, rice, vegetables given as dhanam.', 'எள், அரிசி, காய்கறி தானம்.'),
    temples: ['rameswaram', 'kanyakumari', 'thirukadaiyur'], see: ['amavasai'], sources: SRC,
  },
  {
    id: 'ratha-saptami', kind: 'festival', mantra: 'gayatri',
    names: B('Ratha Saptami', 'ரத சப்தமி'),
    aliases: ['ratha saptami', 'radha saptami', 'rathasapthami', 'ratha sapthami', 'surya jayanthi', 'ரத சப்தமி', 'ரதசப்தமி'],
    deity: B('Surya', 'சூரிய பகவான்'),
    rule: { tithi: 6, at: 'sunrise', lunar: [10] },
    ruleText: B('Shukla Saptami (7th) in the lunar month of Magha — about a week after Thai Amavasai.', 'மாக மாத வளர்பிறைச் சப்தமி — தை அமாவாசைக்குச் சுமார் ஒரு வாரம் பின்.'),
    line: B('The Sun’s birthday — he turns his seven-horse chariot north.', 'சூரியனின் பிறந்த நாள் — ஏழு குதிரைத் தேரை வடக்கு நோக்கித் திருப்பும் நாள்.'),
    why: B('Ratha Saptami is celebrated as Surya Jayanthi, when the Sun’s chariot of seven horses is said to turn fully north. Bathing at sunrise with seven erukku (calotropis) leaves on the head and offering arghya is believed to bring health.',
      'சூரிய ஜெயந்தியாகக் கொண்டாடப்படும் ரத சப்தமியில் சூரியனின் ஏழு குதிரைத் தேர் முழுமையாக வடக்கு நோக்கித் திரும்பும் என்பது நம்பிக்கை. சூரிய உதயத்தில் தலையில் ஏழு எருக்க இலைகள் வைத்து நீராடி அர்க்கியம் விடுவது ஆரோக்கியம் தரும் என்பது மரபு.'),
    how: B(['Bath at sunrise with erukku leaves (and a little rice and turmeric) on the head.', 'Offer water to the rising Sun; draw a chariot kolam; chant Aditya Hridayam or Gayatri.'], ['சூரிய உதயத்தில் தலையில் எருக்க இலை (சிறிது அரிசி, மஞ்சளுடன்) வைத்து நீராடல்.', 'உதய சூரியனுக்கு நீர் அர்க்கியம்; தேர்க் கோலம்; ஆதித்ய ஹ்ருதயம் அல்லது காயத்ரி.']),
    offer: B('Sweet pongal, wheat payasam.', 'சர்க்கரைப் பொங்கல், கோதுமைப் பாயசம்.'),
    temples: ['suriyanar', 'tirumala'],
    regional: B('Tirumala holds the one-day Brahmotsavam with seven vahanams on this day.', 'திருமலையில் அன்று ஏழு வாகனங்களுடன் ஒருநாள் பிரம்மோற்சவம்.'), sources: SRC,
  },
  {
    id: 'vasantha-panchami', kind: 'festival',
    names: B('Vasantha Panchami', 'வசந்த பஞ்சமி'),
    aliases: ['vasantha panchami', 'vasant panchami', 'basant panchami', 'saraswati puja north', 'வசந்த பஞ்சமி'],
    deity: B('Goddess Saraswathi', 'சரஸ்வதி தேவி'),
    rule: { tithi: 4, at: 'sunrise', lunar: [10] },
    ruleText: B('Shukla Panchami (5th) in the lunar month of Magha.', 'மாக மாத வளர்பிறைப் பஞ்சமி.'),
    line: B('Spring festival of Saraswathi, mainly in North and East India.', 'வட, கிழக்கு இந்தியாவில் முக்கியமான வசந்த கால சரஸ்வதி விழா.'),
    why: B('In North and East India, Saraswathi Puja is done on Vasantha Panchami, the start of spring; children begin learning letters (Vidyarambham). In Tamil Nadu, Saraswathi Pooja is on Navaratri Navami instead.', 'வட, கிழக்கு இந்தியாவில் வசந்தத் தொடக்கமான பஞ்சமியில் சரஸ்வதி பூஜை நடக்கும்; குழந்தைகளுக்கு எழுத்தறிவித்தல். தமிழ்நாட்டில் சரஸ்வதி பூஜை நவராத்திரி நவமியில்.'),
    how: B(['Wear yellow, place books before Saraswathi, offer yellow sweets.'], ['மஞ்சள் உடை, சரஸ்வதி முன் புத்தகங்கள், மஞ்சள் இனிப்பு படைத்தல்.']),
    chant: { text: 'ஓம் ஸ்ரீ சரஸ்வத்யை நமஹ', translit: 'Om Sri Saraswathyai Namaha', meaning: B('Salutations to Goddess Saraswathi, giver of learning.', 'கல்வி தரும் சரஸ்வதி தேவிக்கு வணக்கம்.') },
    see: ['saraswathi-pooja'], sources: SRC,
  },
  {
    id: 'maha-sivaratri', kind: 'festival', fast: true, mantra: 'shiva',
    names: B('Maha Sivaratri', 'மகா சிவராத்திரி'),
    aliases: ['maha sivaratri', 'maha shivratri', 'mahashivratri', 'sivarathri', 'sivaratri', 'shivaratri', 'shivratri', 'maha sivarathiri', 'மகா சிவராத்திரி', 'சிவராத்திரி', 'மகாசிவராத்திரி'],
    deity: B('Lord Shiva', 'சிவபெருமான்'),
    rule: { tithi: 28, at: 'midnight', lunar: [10] },
    ruleText: B('Krishna Chathurdasi prevailing at midnight in the lunar month of Magha (Tamil Maasi; sometimes late Thai/early Panguni by date).', 'மாக மாதத் தேய்பிறைச் சதுர்த்தசி நள்ளிரவில் இருக்கும் நாள் (தமிழ் மாசி மாதம்).'),
    line: B('The great night of Shiva — fasting, four-kala pooja and staying awake in prayer.', 'சிவனின் மகா இரவு — விரதம், நான்கு கால பூஜை, விழித்திருந்து வழிபாடு.'),
    why: B('Maha Sivaratri is believed to be the night Shiva appeared as an endless column of fire (Lingodbhava) and the night of His cosmic dance; Parvati is said to have worshipped Him through this night. Staying awake in prayer symbolises staying awake to the inner light.',
      'எல்லையற்ற அக்னி ஸ்தம்பமாகச் சிவன் தோன்றிய (லிங்கோத்பவம்) இரவும், அவரின் பிரபஞ்ச நடன இரவும் மகா சிவராத்திரி என்பது நம்பிக்கை; பார்வதி தேவி இந்த இரவு முழுவதும் வழிபட்டதாகச் சொல்லப்படுகிறது. விழித்திருப்பது உள் ஒளிக்கு விழித்திருப்பதைக் குறிக்கிறது.'),
    story: B('Brahma and Vishnu once argued over who was greater. A blazing pillar of fire appeared between them; Vishnu as a boar dug down and Brahma as a swan flew up, but neither found its end. Brahma falsely claimed he saw the top, citing the thazhampoo (screwpine) flower as witness. Shiva emerged from the pillar, and since then thazhampoo is not offered to Him. Tiruvannamalai is the place of this story; the Lingodbhava form is behind the sanctum in Shiva temples.',
      'யார் பெரியவர் என்று பிரம்மனும் விஷ்ணுவும் வாதிட்டனர். அவர்கள் நடுவே எரியும் அக்னித் தூண் தோன்றியது; விஷ்ணு வராகமாகக் கீழே தோண்டினார், பிரம்மன் அன்னமாக மேலே பறந்தார் — இருவரும் முடிவைக் காணவில்லை. உச்சியைக் கண்டதாகப் பிரம்மன் பொய் சொல்லித் தாழம்பூவைச் சாட்சியாக்கினான். தூணிலிருந்து சிவன் வெளிப்பட்டார்; அன்றிலிருந்து தாழம்பூ சிவனுக்குச் சாற்றப்படுவதில்லை. இது திருவண்ணாமலைத் தலக் கதை; சிவாலயங்களில் கருவறைக்குப் பின் லிங்கோத்பவர் உள்ளார்.'),
    how: B(['Fast through the day as health allows (fruit, milk or one light meal is fine).', 'Attend the four kala poojas at night, or pray at home in four sittings: milk, curd, ghee and honey abhishekam.', 'Chant "Om Namah Shivaya", read Thevaram/Thiruvasagam; stay awake if comfortable — sleep if you need to.', 'Break the fast next morning after bathing and prayer.'],
      ['உடல்நிலைக்கு ஏற்ப பகல் விரதம் (பழம், பால், ஒரு லேசான உணவு பரவாயில்லை).', 'இரவு நான்கு கால பூஜையில் கலந்துகொள்ளுங்கள், அல்லது வீட்டில் நான்கு முறை: பால், தயிர், நெய், தேன் அபிஷேகம்.', '"ஓம் நமசிவாய", தேவாரம்/திருவாசகம்; வசதியாக இருந்தால் விழித்திருங்கள் — தேவைப்பட்டால் உறங்குங்கள்.', 'மறுநாள் காலை நீராடி வழிபட்ட பின் விரதம் முடியுங்கள்.']),
    offer: B('Bilva leaves, milk, curd, ghee, honey, tender coconut, fruits. Thazhampoo is not offered.', 'வில்வம், பால், தயிர், நெய், தேன், இளநீர், பழங்கள். தாழம்பூ சாற்றுவதில்லை.'),
    temples: ['tiruvannamalai', 'chidambaram', 'kalahasti', 'rameswaram', 'thanjavur_big', 'mylapore'],
    regional: B('North Indian calendars name the month Phalguna (purnimanta) — the date is the same night.', 'வட இந்தியப் பஞ்சாங்கங்கள் இதை பால்குன மாதம் என்கின்றன (பௌர்ணமி முடிவு மாதக் கணக்கு) — இரவு அதேதான்.'),
    see: ['masa-sivaratri', 'pradosham'], sources: SRC,
  },
  {
    id: 'masi-magam', kind: 'festival', mantra: 'shiva',
    names: B('Masi Magam', 'மாசி மகம்'),
    aliases: ['masi magam', 'maasi magam', 'masi makam', 'mahamaham', 'mahamagam', 'மாசி மகம்', 'மகாமகம்'],
    deity: B('Shiva, Vishnu, Murugan — temple deities taken for theerthavari', 'சிவன், திருமால், முருகன் — தீர்த்தவாரி'),
    rule: { star: 9, solar: [10], twice: 'pournami' },
    ruleText: B('Magam (Magha) star in the Tamil month of Maasi, usually the full-moon day.', 'மாசி மாதத்தில் மக நட்சத்திரம் — பெரும்பாலும் பௌர்ணமி நாள்.'),
    line: B('Sacred bath day — deities are taken to the sea and tanks (theerthavari).', 'புனித நீராடல் நாள் — தெய்வங்கள் கடல், குளங்களுக்குத் தீர்த்தவாரிக்கு எழுந்தருளல்.'),
    why: B('On Masi Magam temple deities are carried to seashores and tanks for the holy dip, and devotees bathe with them. Every 12 years, when Jupiter is in Simha, it becomes the Mahamaham at Kumbakonam, where the holy rivers are believed to gather in the Mahamaham tank.',
      'மாசி மகத்தில் கோவில் தெய்வங்கள் கடற்கரை, குளங்களுக்குத் தீர்த்தவாரிக்கு எழுந்தருள, பக்தர்களும் உடன் நீராடுவர். 12 ஆண்டுக்கு ஒருமுறை குரு சிம்மத்தில் இருக்கும்போது கும்பகோணத்தில் மகாமகம் — புண்ணிய நதிகள் மகாமகக் குளத்தில் கூடும் என்பது நம்பிக்கை.'),
    how: B(['Take a holy bath (or a bath at home with prayer); join the theerthavari if nearby; give food or clothes as dhanam.'], ['புனித நீராடல் (அல்லது வீட்டில் பிரார்த்தனையுடன் நீராடல்); அருகில் இருந்தால் தீர்த்தவாரியில் கலந்துகொள்ளல்; அன்னம் அல்லது ஆடை தானம்.']),
    temples: ['kumbakonam_adi', 'kumbakonam_sarangapani', 'mylapore'],
    regional: B('Mahamaham was last held in 2016; the next is expected in 2028.', 'கடைசி மகாமகம் 2016-ல்; அடுத்தது 2028-ல் எதிர்பார்க்கப்படுகிறது.'), sources: SRC,
  },
  {
    id: 'karadaiyan-nombu', kind: 'vratham',
    names: B('Karadaiyan Nombu (Savitri Vratham)', 'காரடையான் நோன்பு'),
    aliases: ['karadaiyan nombu', 'karadayan nombu', 'karadai nombu', 'savitri vratham', 'savithri viratham', 'kaaradaiyaan nonbu', 'காரடையான் நோன்பு', 'சாவித்திரி விரதம்'],
    deity: B('Goddess Kamakshi / Savitri', 'காமாட்சி / சாவித்திரி'),
    rule: { solarDay: [11, 1] },
    ruleText: B('the moment Maasi ends and Panguni begins — the nombu thread is tied at the exact Sankranti time; listed on Panguni 1 (check the muhurtham in your almanac).', 'மாசி முடிந்து பங்குனி பிறக்கும் நேரத்தில் நோன்புக் கயிறு கட்டுவது; இங்கே பங்குனி 1-ல் காட்டப்படுகிறது (சரியான நேரம் பஞ்சாங்கத்தில் பாருங்கள்).'),
    line: B('Married women pray for their husbands’ long, healthy life, remembering Savitri.', 'சாவித்திரியை நினைத்துக் கணவரின் நீண்ட, நலமான வாழ்வுக்காகச் சுமங்கலிகள் நோற்கும் நோன்பு.'),
    why: B('Savitri’s steadfast love and wisdom won back her husband Satyavan from Yama. Remembering her, married women tie a yellow thread and offer karadai (rice-jaggery cakes) with butter, praying for a lasting, loving married life.',
      'சாவித்திரியின் உறுதியான அன்பும் அறிவும் கணவன் சத்தியவானை எமனிடமிருந்து மீட்டன. அவளை நினைத்துச் சுமங்கலிகள் மஞ்சள் சரடு கட்டி, வெண்ணெயுடன் காரடை படைத்து, நீடித்த அன்பான மண வாழ்வுக்கு வேண்டுவர்.'),
    story: B('Princess Savitri chose Satyavan, a forest-dwelling prince. When Yama came for Satyavan, Savitri followed Yama and answered him with such wisdom that he granted her boons — and by asking for children from Satyavan, she won back his life.',
      'இளவரசி சாவித்திரி காட்டில் வாழ்ந்த இளவரசன் சத்தியவானைத் தேர்ந்தாள். சத்தியவானை அழைத்துச் செல்ல எமன் வந்தபோது, சாவித்திரி பின்தொடர்ந்து தன் அறிவார்ந்த பதில்களால் வரங்கள் பெற்றாள் — சத்தியவான் மூலம் குழந்தைகள் வேண்டும் என்று கேட்டு, அவன் உயிரை மீட்டாள்.'),
    how: B(['Make vella karadai and uppu karadai; offer with unmelted butter.', 'At the Sankranti time, tie the yellow nombu saradu while saying “Urugadha vennaiyum oradaiyum naan nottren, orukkalum en kanavan ennai vittu pirigadha irukka vendum”.'],
      ['வெல்லக் காரடை, உப்புக் காரடை செய்து உருகாத வெண்ணெயுடன் படையுங்கள்.', 'சங்கராந்தி நேரத்தில் "உருகாத வெண்ணெயும் ஓரடையும் நான் நோற்றேன், ஒருக்காலும் என் கணவன் என்னை விட்டுப் பிரியாதிருக்க வேண்டும்" என்று சொல்லி மஞ்சள் நோன்புச் சரடு கட்டுங்கள்.']),
    offer: B('Karadai (sweet and salt), butter, fruits.', 'காரடை (இனிப்பு, உப்பு), வெண்ணெய், பழங்கள்.'),
    regional: B('Called Vat Savitri in North India, observed in Jyeshtha.', 'வட இந்தியாவில் வட சாவித்திரி — ஜ்யேஷ்ட மாதத்தில்.'), sources: SRC,
  },
  {
    id: 'holi', kind: 'festival',
    names: B('Holi', 'ஹோலி'),
    aliases: ['holi', 'holika', 'holika dahan', 'ஹோலி'],
    deity: B('Lord Krishna, Prahlada', 'கிருஷ்ணர், பிரகலாதன்'),
    rule: { tithi: 15, at: 'sunrise', lunar: [11] },
    ruleText: B('the day after Phalguna Pournami (Holika fire is lit on the full-moon night).', 'பால்குன பௌர்ணமிக்கு மறுநாள் (பௌர்ணமி இரவு ஹோலிகா தகனம்).'),
    line: B('Festival of colours, mainly in North India; good over evil (Prahlada).', 'வண்ணங்களின் விழா — பெரும்பாலும் வட இந்தியாவில்; பிரகலாதன் கதை.'),
    why: B('Holi recalls how devotee Prahlada was protected while Holika, who tried to harm him, was consumed by the fire — goodness winning over arrogance. It also celebrates Krishna’s playful love in Vrindavan.', 'தீங்கு செய்ய முயன்ற ஹோலிகா நெருப்பில் அழிய, பக்தன் பிரகலாதன் காக்கப்பட்டதை நினைவூட்டுகிறது — நன்மை ஆணவத்தை வெல்வது. பிருந்தாவனக் கிருஷ்ணரின் அன்பு விளையாட்டையும் கொண்டாடுகிறது.'),
    how: B(['Play with natural colours, gently and with consent; protect eyes and skin.'], ['இயற்கை வண்ணங்களுடன், மென்மையாக, விருப்பத்துடன் விளையாடுங்கள்; கண், தோலைப் பாதுகாக்கவும்.']),
    regional: B('In Tamil Nadu the same full moon is Panguni Uthiram / Kama Dahanam in some villages.', 'தமிழ்நாட்டில் அதே பௌர்ணமி அருகே பங்குனி உத்திரம்; சில கிராமங்களில் காம தகனம்.'), sources: SRC,
  },
  {
    id: 'panguni-uthiram', kind: 'festival', mantra: 'murugan',
    names: B('Panguni Uthiram', 'பங்குனி உத்திரம்'),
    aliases: ['panguni uthiram', 'panguni uthram', 'panguni uttiram', 'பங்குனி உத்திரம்'],
    deity: B('Divine weddings — Shiva-Parvati, Murugan-Deivanai, Rama-Sita, Andal-Ranganatha', 'தெய்வத் திருமணங்கள் — சிவ-பார்வதி, முருகன்-தெய்வானை, ராமர்-சீதை, ஆண்டாள்-ரங்கநாதர்'),
    rule: { star: 11, solar: [11], twice: 'pournami' },
    ruleText: B('Uthiram star in the Tamil month of Panguni, usually the full-moon day.', 'பங்குனி மாதத்தில் உத்திர நட்சத்திரம் — பெரும்பாலும் பௌர்ணமி.'),
    line: B('Day of divine weddings — prayers for a happy marriage; Kula Deivam worship.', 'தெய்வத் திருமண நாள் — நல்ல மண வாழ்வுக்கும் குலதெய்வ வழிபாட்டுக்கும் உகந்தது.'),
    why: B('Many divine marriages are said to have happened on Panguni Uthiram: Shiva and Parvati (Meenakshi Kalyanam tradition), Murugan and Deivanai, Rama and Sita, Andal and Ranganatha. Ayyappan’s birth is also linked to it. Families visit their Kula Deivam temple on this day.',
      'சிவ-பார்வதி, முருகன்-தெய்வானை, ராமர்-சீதை, ஆண்டாள்-ரங்கநாதர் ஆகிய தெய்வத் திருமணங்கள் பங்குனி உத்திரத்தில் நடந்ததாகச் சொல்லப்படுகிறது. ஐயப்பன் அவதாரமும் இந்நாளுடன் தொடர்புடையது. குடும்பங்கள் குலதெய்வக் கோவிலுக்குச் செல்லும் நாள்.'),
    how: B(['Visit your Kula Deivam or a Murugan/Shiva temple; attend the Thirukalyanam if held; unmarried people may pray for a good alliance.'], ['குலதெய்வம் அல்லது முருகன்/சிவன் கோவில் தரிசனம்; திருக்கல்யாணம் நடந்தால் கலந்துகொள்ளல்; திருமணம் ஆகாதவர்கள் நல்ல வரனுக்கு வேண்டலாம்.']),
    offer: B('Panakam, neer mor, sweet pongal; kavadi at Palani.', 'பானகம், நீர் மோர், சர்க்கரைப் பொங்கல்; பழனியில் காவடி.'),
    temples: ['palani', 'mylapore', 'srirangam', 'madurai_meenakshi'], sources: SRC,
  },
  {
    id: 'ugadi', kind: 'festival',
    names: B('Ugadi (Telugu/Kannada New Year)', 'யுகாதி'),
    aliases: ['ugadi', 'yugadi', 'gudi padwa', 'telugu new year', 'kannada new year', 'யுகாதி', 'உகாதி'],
    deity: B('Brahma (creation)', 'பிரம்மா (படைப்பு)'),
    rule: { tithi: 0, at: 'sunrise', lunar: [0] },
    ruleText: B('Chaitra Shukla Prathamai — the day after the new moon near the end of Panguni.', 'சைத்ர வளர்பிறைப் பிரதமை — பங்குனி இறுதி அமாவாசைக்கு மறுநாள்.'),
    line: B('Lunar New Year for Telugu and Kannada families (Gudi Padwa in Maharashtra).', 'தெலுங்கு, கன்னடக் குடும்பங்களின் சந்திர மானப் புத்தாண்டு (மகாராஷ்டிராவில் குடி பட்வா).'),
    why: B('Ugadi (yuga + adi, start of an age) is believed to be the day Brahma began creation. The Ugadi pachadi — neem flower, jaggery, tamarind, salt, chilli and raw mango — teaches accepting every taste of life in the year ahead.', 'யுகாதி (யுகம் + ஆதி) பிரம்மா படைப்பைத் தொடங்கிய நாள் என்பது நம்பிக்கை. வேப்பம்பூ, வெல்லம், புளி, உப்பு, மிளகாய், மாங்காய் சேர்ந்த பச்சடி, வரும் ஆண்டின் எல்லாச் சுவைகளையும் ஏற்கக் கற்றுத் தருகிறது.'),
    how: B(['Oil bath, new clothes, mango-leaf thoranam; Ugadi pachadi; listen to the Panchanga sravanam (new year almanac reading).'], ['எண்ணெய்க் குளியல், புத்தாடை, மாவிலைத் தோரணம்; யுகாதிப் பச்சடி; பஞ்சாங்க சிரவணம் கேட்டல்.']),
    offer: B('Ugadi pachadi, obbattu/poli, pulihora.', 'யுகாதிப் பச்சடி, போளி, புளியோதரை.'),
    regional: B('Tamil New Year is solar (Chithirai 1) and usually comes a week or two later.', 'தமிழ்ப் புத்தாண்டு சூரிய மானம் (சித்திரை 1) — பொதுவாக ஓரிரு வாரம் பின்.'),
    see: ['tamil-new-year'], sources: SRC,
  },
  {
    id: 'tamil-new-year', kind: 'festival', mantra: 'ganesha',
    names: B('Tamil New Year (Chithirai 1)', 'தமிழ்ப் புத்தாண்டு (சித்திரை 1)'),
    aliases: ['tamil new year', 'tamil puthandu', 'puthandu', 'chithirai 1', 'chithirai thirunal', 'varusha pirappu', 'vishu', 'தமிழ்ப் புத்தாண்டு', 'தமிழ் புத்தாண்டு', 'சித்திரை 1', 'புத்தாண்டு', 'வருடப் பிறப்பு', 'சித்திரைத் திருநாள்'],
    deity: B('Vinayagar, Surya; family deity', 'விநாயகர், சூரியன்; குலதெய்வம்'),
    rule: { solarDay: [0, 1] },
    ruleText: B('Chithirai 1 — the day the Sun enters Mesha (Aries) rasi (next day if after sunset).', 'சித்திரை 1 — சூரியன் மேஷ ராசியில் நுழையும் நாள் (அஸ்தமனத்துக்குப் பின் என்றால் மறுநாள்).'),
    line: B('Tamil New Year — new almanac, mango pachadi and kani (auspicious first sight).', 'தமிழ்ப் புத்தாண்டு — புதிய பஞ்சாங்கம், மாங்காய்ப் பச்சடி, கனி காணல்.'),
    why: B('When the Sun enters Mesha, the Tamil solar year begins — the year names run in a 60-year cycle. Families start the year with gratitude, visiting temples and reading the new panchangam.', 'சூரியன் மேஷத்தில் நுழையும்போது தமிழ் சூரிய ஆண்டு தொடங்குகிறது — ஆண்டுப் பெயர்கள் 60 ஆண்டுச் சுழற்சியில் வருகின்றன. நன்றியுடன் ஆண்டைத் தொடங்கி, கோவில் சென்று, புதுப் பஞ்சாங்கம் படிப்பர்.'),
    how: B(['Night before, arrange fruits, gold/coins, mirror and flowers to see first on waking (kani).', 'Oil bath, new clothes, kolam; mango pachadi with neem flower and jaggery; temple visit; Panchanga padanam.'], ['முந்தைய இரவே பழங்கள், தங்கம்/நாணயம், கண்ணாடி, மலர்களை அடுக்கி, காலையில் முதலில் காணுதல் (கனி).', 'எண்ணெய்க் குளியல், புத்தாடை, கோலம்; வேப்பம்பூ-வெல்லம் சேர்த்த மாங்காய்ப் பச்சடி; கோவில்; பஞ்சாங்கப் படனம்.']),
    offer: B('Mango pachadi, payasam, vadai.', 'மாங்காய்ப் பச்சடி, பாயசம், வடை.'),
    regional: B('Kerala celebrates Vishu the same day (Vishukkani); Punjab Baisakhi, Bengal Pohela Boishakh, Assam Bihu.', 'அதே நாளில் கேரளத்தில் விஷு (விஷுக்கனி); பஞ்சாபில் பைசாகி, வங்காளத்தில் பொய்லா போய்ஷாக், அசாமில் பிஹு.'),
    see: ['ugadi'], sources: SRC,
  },
  {
    id: 'rama-navami', kind: 'festival', fast: true, mantra: 'rama',
    names: B('Sri Rama Navami', 'ஸ்ரீ ராம நவமி'),
    aliases: ['rama navami', 'ram navami', 'sri rama navami', 'ramanavami', 'ராம நவமி', 'ஸ்ரீ ராம நவமி', 'ராமநவமி'],
    deity: B('Lord Rama', 'ஸ்ரீ ராமர்'),
    rule: { tithi: 8, at: 'midday', lunar: [0] },
    ruleText: B('Chaitra Shukla Navami prevailing at midday (Rama was born at noon) — 9 days after Ugadi.', 'சைத்ர வளர்பிறை நவமி நண்பகலில் இருக்கும் நாள் (ராமர் நண்பகலில் அவதரித்தார்) — யுகாதிக்கு 9 நாள் பின்.'),
    line: B('Birthday of Lord Rama — panakam, neer mor and Rama nama.', 'ஸ்ரீ ராமர் அவதார நாள் — பானகம், நீர் மோர், ராம நாமம்.'),
    why: B('Rama, the seventh avatar of Vishnu, was born to Kausalya and Dasaratha at Ayodhya at noon on Navami with Punarpoosam star. He is honoured as the ideal son, king and person of dharma; chanting His name is believed to bring peace and courage.', 'திருமாலின் ஏழாவது அவதாரமான ராமர், அயோத்தியில் தசரதர்-கௌசல்யைக்கு நவமி நண்பகல், புனர்பூச நட்சத்திரத்தில் அவதரித்தார். சிறந்த மகன், அரசன், தர்மவான் என்று போற்றப்படுகிறார்; ராம நாமம் அமைதியும் தைரியமும் தரும் என்பது நம்பிக்கை.'),
    how: B(['Fast till noon if healthy; read Ramayanam or the Sundara Kandam; chant "Sri Rama Jaya Rama Jaya Jaya Rama".', 'Offer panakam (jaggery-cardamom drink), neer mor and kosumalli at noon; share with passers-by in the summer heat.'], ['உடல்நலம் அனுமதித்தால் நண்பகல் வரை விரதம்; ராமாயணம் அல்லது சுந்தர காண்டம் படித்தல்; "ஸ்ரீ ராம ஜெய ராம ஜெய ஜெய ராம".', 'நண்பகலில் பானகம், நீர் மோர், கோசுமல்லி படைத்து, வெயிலில் போவோருக்கும் வழங்குங்கள்.']),
    offer: B('Panakam, neer mor, kosumalli, sundal.', 'பானகம், நீர் மோர், கோசுமல்லி, சுண்டல்.'),
    temples: ['rameswaram', 'kumbakonam_sarangapani'],
    regional: B('Many South Indian homes hold a 10-day Rama Navami utsavam with music (Thyagaraja kritis).', 'பல தென்னிந்திய இல்லங்களில் இசையுடன் (தியாகராஜ கீர்த்தனைகள்) 10 நாள் ராம நவமி உற்சவம்.'),
    see: ['hanuman-jayanthi'], sources: SRC,
  },
  {
    id: 'chithra-pournami', kind: 'festival', mantra: 'ambal',
    names: B('Chithra Pournami', 'சித்ரா பௌர்ணமி'),
    aliases: ['chithra pournami', 'chitra pournami', 'chitra purnima', 'chithirai pournami', 'chithragupta', 'சித்ரா பௌர்ணமி', 'சித்திரைப் பௌர்ணமி', 'சித்ரா பவுர்ணமி'],
    deity: B('Chitragupta; Meenakshi-Sundareswarar; Kallazhagar', 'சித்திரகுப்தர்; மீனாட்சி-சுந்தரேஸ்வரர்; கள்ளழகர்'),
    rule: { tithi: 14, at: 'sunrise', solar: [0] },
    ruleText: B('the Pournami in the Tamil month of Chithirai.', 'சித்திரை மாதப் பௌர்ணமி.'),
    line: B('Full moon of Chithirai — Chitragupta pooja and the Madurai Chithirai festival.', 'சித்திரை முழு நிலவு — சித்திரகுப்தர் பூஜை, மதுரை சித்திரைத் திருவிழா.'),
    why: B('Chithra Pournami honours Chitragupta, believed to record everyone’s good and bad deeds; people pray for the wisdom to do good. In Madurai, the Chithirai festival reaches its peak as Kallazhagar enters the Vaigai river; Girivalam at Tiruvannamalai is especially crowded.', 'அனைவரின் நன்மை-தீமைக் கணக்கை எழுதுபவர் என்று நம்பப்படும் சித்திரகுப்தரை வழிபடும் நாள்; நல்லது செய்யும் அறிவுக்கு வேண்டுவர். மதுரையில் கள்ளழகர் வைகையில் இறங்கும் சித்திரைத் திருவிழா உச்சம்; திருவண்ணாமலை கிரிவலம் மிகுந்த கூட்டம்.'),
    how: B(['Light a lamp and pray to Chitragupta; give a notebook, pen, salt or food as dhanam.', 'Many have the evening meal outdoors under the full moon (nila choru) with family.'], ['விளக்கேற்றி சித்திரகுப்தரை வழிபடுங்கள்; நோட்டு, பேனா, உப்பு அல்லது உணவு தானம்.', 'மாலையில் குடும்பத்துடன் நிலவொளியில் உணவு (நிலாச் சோறு).']),
    offer: B('Chitrannam (variety rice), payasam, sweet pongal.', 'சித்திரான்னம், பாயசம், சர்க்கரைப் பொங்கல்.'),
    temples: ['madurai_meenakshi', 'alagar_kovil', 'tiruvannamalai'], see: ['chithirai-thiruvizha'], sources: SRC,
  },
  {
    id: 'chithirai-thiruvizha', kind: 'festival',
    names: B('Kallazhagar Vaigai entry (Madurai Chithirai festival)', 'கள்ளழகர் வைகை எழுந்தருளல் (சித்திரைத் திருவிழா)'),
    aliases: ['chithirai thiruvizha', 'chithirai festival', 'kallazhagar', 'azhagar vaigai', 'meenakshi kalyanam', 'meenakshi thirukalyanam', 'சித்திரைத் திருவிழா', 'கள்ளழகர்', 'மீனாட்சி திருக்கல்யாணம்'],
    deity: B('Meenakshi-Sundareswarar, Kallazhagar', 'மீனாட்சி-சுந்தரேஸ்வரர், கள்ளழகர்'),
    rule: { offset: 'chithra-pournami', days: 0 },
    ruleText: B('Kallazhagar enters the Vaigai on Chithra Pournami; Meenakshi Thirukalyanam is a few days earlier in the same festival (temple announces exact dates).', 'சித்ரா பௌர்ணமியில் கள்ளழகர் வைகையில் இறங்குதல்; மீனாட்சி திருக்கல்யாணம் அதே திருவிழாவில் சில நாள் முன் (கோவில் அறிவிக்கும்).'),
    line: B('Madurai’s grand festival — Meenakshi’s wedding and Azhagar’s river entry.', 'மதுரையின் பெருவிழா — மீனாட்சி திருமணம், அழகர் ஆற்றில் இறங்குதல்.'),
    why: B('Tradition says Kallazhagar (Vishnu) set out from Alagar Kovil to give His sister Meenakshi in marriage to Sundareswarar, but arrived after the wedding and stayed on the Vaigai bank. The story joins Shaiva and Vaishnava devotees in one festival.', 'தங்கை மீனாட்சியைச் சுந்தரேஸ்வரருக்கு மணமுடித்துக் கொடுக்க அழகர்கோவிலிலிருந்து கள்ளழகர் (திருமால்) புறப்பட்டார்; திருமணம் முடிந்த பின் வந்ததால் வைகைக் கரையிலேயே தங்கினார் என்பது மரபு. சைவ, வைணவ பக்தர்களை ஒரே விழாவில் இணைக்கும் கதை.'),
    how: B(['Join the procession or watch the live telecast; carry water in the heat; follow police crowd guidance.'], ['ஊர்வலத்தில் கலந்துகொள்ளுங்கள் அல்லது நேரலை பாருங்கள்; வெயிலில் தண்ணீர் எடுத்துச் செல்லுங்கள்; காவல்துறை வழிகாட்டலைப் பின்பற்றுங்கள்.']),
    temples: ['madurai_meenakshi', 'alagar_kovil'], sources: SRC,
  },
  {
    id: 'ramanuja-jayanthi', kind: 'festival', mantra: 'narayana',
    names: B('Sri Ramanuja Jayanthi', 'ஸ்ரீ ராமானுஜர் ஜெயந்தி'),
    aliases: ['ramanuja jayanthi', 'ramanujar jayanthi', 'udayavar', 'ramanujar', 'ராமானுஜர் ஜெயந்தி', 'உடையவர்', 'ராமானுஜர்'],
    deity: B('Sri Ramanujacharya', 'ஸ்ரீ ராமானுஜர்'),
    rule: { star: 5, solar: [0] },
    ruleText: B('Thiruvathirai star in Chithirai.', 'சித்திரை மாதத் திருவாதிரை நட்சத்திரம்.'),
    line: B('Birth star of Sri Ramanuja, the great Vaishnava teacher (born 1017 at Sriperumbudur).', 'பெரும் வைணவ ஆசாரியர் ஸ்ரீ ராமானுஜர் அவதார நட்சத்திரம் (1017, ஸ்ரீபெரும்புதூர்).'),
    why: B('Ramanuja taught Vishishtadvaita and opened the path of devotion to all — he is remembered for sharing the sacred mantra from the temple tower at Thirukoshtiyur so everyone could benefit.', 'விசிஷ்டாத்வைதத்தை உபதேசித்து அனைவருக்கும் பக்தி வழியைத் திறந்தவர் ராமானுஜர் — திருக்கோஷ்டியூர் கோபுரத்திலிருந்து அனைவருக்கும் மந்திரத்தை அருளியவர் என்று போற்றப்படுகிறார்.'),
    how: B(['Visit a Perumal temple; recite Ramanuja Nootrandhadhi or simply "Om Namo Narayanaya".'], ['பெருமாள் கோவில் தரிசனம்; ராமானுஜ நூற்றந்தாதி அல்லது "ஓம் நமோ நாராயணாய".']),
    temples: ['srirangam', 'kanchi_varadaraja', 'tirumala'], sources: SRC,
  },
  {
    id: 'akshaya-tritiya', kind: 'festival', mantra: 'lakshmi',
    names: B('Akshaya Tritiya', 'அட்சய திருதியை'),
    aliases: ['akshaya tritiya', 'akshaya thiruthiyai', 'atchaya thiruthiyai', 'akshaya trithiya', 'akha teej', 'அட்சய திருதியை', 'அக்ஷய திருதியை'],
    deity: B('Mahalakshmi, Kubera, Lord Vishnu', 'மகாலட்சுமி, குபேரன், திருமால்'),
    rule: { tithi: 2, at: 'sunrise', lunar: [1] },
    ruleText: B('Vaisakha Shukla Tritiya (3rd day after the Chithirai new moon).', 'வைகாச வளர்பிறைத் திருதியை (சித்திரை அமாவாசைக்குப் பின் 3-ஆம் நாள்).'),
    line: B('“Never-diminishing” day — good deeds and charity are believed to multiply.', '"குறையாத" நாள் — நற்செயல், தானம் பெருகும் என்பது நம்பிக்கை.'),
    why: B('Akshaya means never diminishing. Tradition links this day to Krishna giving Draupadi the Akshaya Patra, Kubera receiving his wealth and the descent of the Ganga. Its spirit is giving — food, water, clothes — rather than buying.', '"அட்சயம்" என்றால் குறையாதது. திரௌபதிக்குக் கிருஷ்ணர் அட்சய பாத்திரம் தந்தது, குபேரன் செல்வம் பெற்றது, கங்கை இறங்கியது ஆகியவை இந்நாளுடன் தொடர்புடையவை என்பது மரபு. இதன் உண்மையான பொருள் கொடுப்பது — உணவு, நீர், ஆடை — வாங்குவது அல்ல.'),
    how: B(['Give water, buttermilk, food or clothes to those in need; pray to Lakshmi-Narayana.', 'Buying gold is a modern custom and is not required — a small grain of rice or salt bought with devotion is equally traditional.'], ['தேவையுள்ளோருக்குத் தண்ணீர், மோர், உணவு, ஆடை வழங்குங்கள்; லட்சுமி-நாராயணரை வழிபடுங்கள்.', 'தங்கம் வாங்குவது தற்கால வழக்கம், கட்டாயம் இல்லை — பக்தியுடன் சிறிது அரிசி அல்லது உப்பு வாங்குவதும் மரபே.']),
    offer: B('Curd rice, panakam, kheer.', 'தயிர் சாதம், பானகம், பாயசம்.'), sources: SRC,
  },
  {
    id: 'sankara-jayanthi', kind: 'festival', mantra: 'shiva',
    names: B('Adi Sankara Jayanthi', 'ஆதி சங்கரர் ஜெயந்தி'),
    aliases: ['sankara jayanthi', 'shankara jayanthi', 'adi sankara', 'adi shankaracharya', 'சங்கர ஜெயந்தி', 'ஆதி சங்கரர்'],
    deity: B('Adi Sankaracharya', 'ஆதி சங்கரர்'),
    rule: { tithi: 4, at: 'sunrise', lunar: [1] },
    ruleText: B('Vaisakha Shukla Panchami.', 'வைகாச வளர்பிறைப் பஞ்சமி.'),
    line: B('Birthday of Adi Sankara, teacher of Advaita (born at Kalady, Kerala).', 'அத்வைத ஆசாரியர் ஆதி சங்கரர் அவதார நாள் (கேரளம், காலடி).'),
    why: B('Adi Sankara travelled across India, wrote commentaries and hymns like Bhaja Govindam and Kanakadhara Stotram, and established the mathas.', 'இந்தியா முழுவதும் பயணித்து, உரைகளும் பஜ கோவிந்தம், கனகதாரா ஸ்தோத்திரம் போன்ற துதிகளும் இயற்றி, மடங்களை நிறுவியவர்.'),
    how: B(['Recite Bhaja Govindam or Kanakadhara Stotram.'], ['பஜ கோவிந்தம் அல்லது கனகதாரா ஸ்தோத்திரம் படியுங்கள்.']), sources: SRC,
  },
  {
    id: 'narasimha-jayanthi', kind: 'festival', fast: true, mantra: 'narayana',
    names: B('Narasimha Jayanthi', 'நரசிம்ம ஜெயந்தி'),
    aliases: ['narasimha jayanthi', 'nrusimha jayanthi', 'narasimhar jayanthi', 'நரசிம்ம ஜெயந்தி', 'நரசிம்மர் ஜெயந்தி'],
    deity: B('Lord Narasimha', 'நரசிம்மர்'),
    rule: { tithi: 13, at: 'sunset', lunar: [1] },
    ruleText: B('Vaisakha Shukla Chathurdasi at sunset (Narasimha appeared at twilight).', 'வைகாச வளர்பிறைச் சதுர்த்தசி அஸ்தமனத்தில் (அந்தியில் நரசிம்மர் தோன்றினார்).'),
    line: B('Vishnu’s man-lion avatar who protected the child devotee Prahlada.', 'பக்தச் சிறுவன் பிரகலாதனைக் காத்த நரசிம்ம அவதாரம்.'),
    why: B('Hiranyakasipu, proud of a boon that no man or beast could harm him by day or night, inside or outside, persecuted his son Prahlada for worshipping Vishnu. Vishnu came out of a pillar as Narasimha — neither man nor beast — at twilight, on the threshold, and ended his tyranny, showing that the Lord protects a sincere devotee.', 'பகலிலும் இரவிலும், உள்ளேயும் வெளியேயும், மனிதனாலும் விலங்காலும் அழியாத வரம் பெற்ற இரணியன், திருமாலை வழிபட்ட மகன் பிரகலாதனைத் துன்புறுத்தினான். திருமால் தூணிலிருந்து மனிதனும் அல்லாத விலங்கும் அல்லாத நரசிம்மராக, அந்தியில், வாசற்படியில் தோன்றி அவன் கொடுங்கோன்மையை முடித்தார் — உண்மையான பக்தனை இறைவன் காப்பான் என்பதைக் காட்டினார்.'),
    how: B(['Fast till evening if healthy; pray at twilight; offer panakam.'], ['உடல்நலம் அனுமதித்தால் மாலை வரை விரதம்; அந்தியில் வழிபாடு; பானகம் படைத்தல்.']),
    offer: B('Panakam, neer mor.', 'பானகம், நீர் மோர்.'), sources: SRC,
  },
  {
    id: 'vaikasi-visakam', kind: 'festival', fast: true, mantra: 'murugan',
    names: B('Vaikasi Visakam', 'வைகாசி விசாகம்'),
    aliases: ['vaikasi visakam', 'vaikasi vishakam', 'visakam', 'vaikasi visagam', 'murugan birthday', 'வைகாசி விசாகம்', 'விசாகம்'],
    deity: B('Lord Murugan', 'முருகப் பெருமான்'),
    rule: { star: 15, solar: [1], twice: 'pournami' },
    ruleText: B('Visakam star in the Tamil month of Vaikasi, usually the full moon.', 'வைகாசி மாதத்தில் விசாக நட்சத்திரம் — பெரும்பாலும் பௌர்ணமி.'),
    line: B('Lord Murugan’s birth star — the day He appeared at Saravana Poigai.', 'முருகப் பெருமான் சரவணப் பொய்கையில் அவதரித்த நட்சத்திரம்.'),
    why: B('Murugan, born of the sparks of Shiva’s third eye, is believed to have appeared on Vaikasi Visakam. Devotees carry paal kudam and kavadi; Tiruchendur and all six Padai Veedu celebrate grandly.', 'சிவனின் நெற்றிக்கண் தீப்பொறியிலிருந்து தோன்றிய முருகன் வைகாசி விசாகத்தில் அவதரித்தார் என்பது நம்பிக்கை. பால் குடம், காவடி எடுப்பர்; திருச்செந்தூர், ஆறுபடை வீடுகளிலும் பெருவிழா.'),
    how: B(['Fast or eat simply; abhishekam with milk to Murugan; chant Kanda Sashti Kavasam; give water and buttermilk in the summer heat.'], ['விரதம் அல்லது எளிய உணவு; முருகனுக்குப் பால் அபிஷேகம்; கந்த சஷ்டி கவசம்; வெயிலில் தண்ணீர், மோர் வழங்குதல்.']),
    offer: B('Milk, panchamritam, neer mor, panakam.', 'பால், பஞ்சாமிர்தம், நீர் மோர், பானகம்.'),
    temples: ['tiruchendur', 'palani', 'thiruparankundram', 'swamimalai', 'thiruthani', 'pazhamudircholai'],
    regional: B('The same full moon is Buddha Purnima in North India.', 'அதே பௌர்ணமி வட இந்தியாவில் புத்த பூர்ணிமா.'), sources: SRC,
  },
  {
    id: 'aani-thirumanjanam', kind: 'festival', mantra: 'shiva',
    names: B('Aani Thirumanjanam', 'ஆனித் திருமஞ்சனம்'),
    aliases: ['aani thirumanjanam', 'ani thirumanjanam', 'aani uthiram', 'natarajar abhishekam', 'ஆனித் திருமஞ்சனம்', 'ஆனி திருமஞ்சனம்', 'ஆனி உத்திரம்'],
    deity: B('Lord Nataraja', 'நடராஜர்'),
    rule: { star: 11, solar: [2] },
    ruleText: B('Uthiram star in the Tamil month of Aani.', 'ஆனி மாதத்தில் உத்திர நட்சத்திரம்.'),
    line: B('Grand abhishekam of Nataraja at Chidambaram — one of His six yearly abhishekams.', 'சிதம்பரத்தில் நடராஜருக்கு மகா அபிஷேகம் — ஆண்டின் ஆறு அபிஷேகங்களில் ஒன்று.'),
    why: B('Nataraja receives only six great abhishekams a year; Aani Thirumanjanam and Margazhi Arudra are the biggest, when He comes out for the Ananda Thandavam darshan. Devotees believe seeing it removes sorrow.', 'நடராஜருக்கு ஆண்டுக்கு ஆறு மகா அபிஷேகங்களே; அவற்றுள் ஆனித் திருமஞ்சனமும் மார்கழி ஆருத்ராவும் மிகப் பெரியவை — அன்று ஆனந்தத் தாண்டவ தரிசனம். அதைக் காண்பது துயர் நீக்கும் என்பது நம்பிக்கை.'),
    how: B(['Visit Chidambaram or any Nataraja shrine; chant Thiruvasagam; offer milk for abhishekam.'], ['சிதம்பரம் அல்லது நடராஜர் சன்னதி தரிசனம்; திருவாசகம்; அபிஷேகத்துக்குப் பால்.']),
    temples: ['chidambaram'], see: ['arudra-darisanam'], sources: SRC,
  },
  {
    id: 'guru-purnima', kind: 'festival', mantra: 'guru',
    names: B('Guru Purnima (Vyasa Pournami)', 'குரு பூர்ணிமா (வியாச பௌர்ணமி)'),
    aliases: ['guru purnima', 'guru pournami', 'vyasa pournami', 'vyasa purnima', 'குரு பூர்ணிமா', 'வியாச பௌர்ணமி', 'குரு பௌர்ணமி'],
    deity: B('Sage Vyasa and one’s own teachers', 'வியாச முனிவர், நம் ஆசிரியர்கள்'),
    rule: { tithi: 14, at: 'sunrise', lunar: [3] },
    ruleText: B('Ashadha Pournami (full moon around Aani/Aadi).', 'ஆஷாட பௌர்ணமி (ஆனி/ஆடி அருகே முழு நிலவு).'),
    line: B('Day to thank teachers — Vyasa, who arranged the Vedas and wrote the Mahabharatham.', 'ஆசிரியர்களுக்கு நன்றி சொல்லும் நாள் — வேதங்களைத் தொகுத்து மகாபாரதம் எழுதிய வியாசர்.'),
    why: B('Vyasa is honoured as the Adi Guru; sannyasis begin their Chaturmasya on this day. Everyone can thank parents and teachers who guided them.', 'வியாசர் ஆதி குருவாகப் போற்றப்படுகிறார்; சன்னியாசிகள் இந்நாளில் சாதுர்மாஸ்யம் தொடங்குவர். பெற்றோருக்கும் வழிகாட்டிய ஆசிரியர்களுக்கும் நன்றி சொல்லலாம்.'),
    how: B(['Visit or call your teachers and elders; take their blessings; read a few verses of the Gita.'], ['ஆசிரியர்கள், பெரியவர்களைச் சந்தித்து அல்லது அழைத்து ஆசி பெறுங்கள்; கீதையில் சில சுலோகங்கள் படியுங்கள்.']),
    sources: SRC,
  },
];
