// Annual festivals, Aadi → Margazhi (July → January). Solar 3 = Aadi … 8 = Margazhi; lunar 4 = Shravana … 8 = Margashirsha.
import { B, SRC } from './common.js';

const NAVARATRI_DAYS = [
  ['Shailaputri / Maheswari', 'சைலபுத்ரி / மகேஸ்வரி', 'Durga as daughter of the mountain — strength and steadiness.', 'மலைமகளாகத் துர்க்கை — வலிமையும் உறுதியும்.', 'Ven pongal', 'வெண் பொங்கல்'],
  ['Brahmacharini / Kaumari', 'பிரம்மசாரிணி / கௌமாரி', 'The Goddess in penance — discipline and devotion.', 'தவக்கோல அன்னை — கட்டுப்பாடு, பக்தி.', 'Puliyodharai', 'புளியோதரை'],
  ['Chandraghanta / Varahi', 'சந்திரகண்டா / வாராஹி', 'Fierce protector with the crescent bell — courage.', 'பிறைமணி ஏந்திய காவல் அன்னை — தைரியம்.', 'Sakkarai pongal', 'சர்க்கரைப் பொங்கல்'],
  ['Kushmanda / Mahalakshmi', 'கூஷ்மாண்டா / மகாலட்சுமி', 'Lakshmi days begin — prosperity and well-being.', 'லட்சுமி நாட்கள் தொடக்கம் — செல்வம், நலம்.', 'Kadamba sadham', 'கதம்ப சாதம்'],
  ['Skandamata / Vaishnavi', 'ஸ்கந்தமாதா / வைஷ்ணவி', 'Mother of Murugan — love and care.', 'முருகனின் அன்னை — அன்பு, அரவணைப்பு.', 'Thayir sadham', 'தயிர் சாதம்'],
  ['Katyayani / Indrani', 'காத்யாயனி / இந்திராணி', 'Warrior Goddess who fought Mahishasura.', 'மகிஷாசுரனுடன் போரிட்ட வீர அன்னை.', 'Thengai sadham', 'தேங்காய் சாதம்'],
  ['Kalaratri / Saraswathi begins', 'காளராத்ரி / சரஸ்வதி தொடக்கம்', 'Saraswathi days begin — the dark night that removes fear.', 'சரஸ்வதி நாட்கள் தொடக்கம் — பயம் நீக்கும் காளராத்ரி.', 'Elumichai sadham', 'எலுமிச்சை சாதம்'],
  ['Mahagauri / Durgashtami', 'மகாகௌரி / துர்காஷ்டமி', 'Pure, peaceful form; Durgashtami pooja.', 'தூய, அமைதியான வடிவம்; துர்காஷ்டமி பூஜை.', 'Sundal & payasam', 'சுண்டல், பாயசம்'],
  ['Siddhidatri / Saraswathi', 'சித்திதாத்ரி / சரஸ்வதி', 'Giver of wisdom — Saraswathi and Ayudha Pooja.', 'ஞானம் அருளும் அன்னை — சரஸ்வதி, ஆயுத பூஜை.', 'Sakkarai pongal, sundal', 'சர்க்கரைப் பொங்கல், சுண்டல்'],
];

const navDay = (n) => {
  const [en, ta, lineEn, lineTa, foodEn, foodTa] = NAVARATRI_DAYS[n - 1];
  return {
    id: `navaratri-day-${n}`, kind: 'festival', mantra: n <= 3 ? 'durga' : n <= 6 ? 'lakshmi' : 'ambal',
    names: B(`Navaratri Day ${n} — ${en}`, `நவராத்திரி ${n}-ஆம் நாள் — ${ta}`),
    aliases: [`navaratri day ${n}`, `navaratri ${n} day`, `நவராத்திரி ${n}-ஆம் நாள்`, `நவராத்திரி ${n}ம் நாள்`],
    deity: B(en, ta),
    rule: { navaratriDay: n },
    ruleText: B(`day ${n} counted from Navaratri day 1 (the Prathamai after Mahalaya Amavasai).`, `மகாளய அமாவாசைக்கு மறுநாள் பிரதமையிலிருந்து ${n}-ஆம் நாள்.`),
    line: B(lineEn, lineTa),
    offer: B(`${foodEn}; sundal for golu visitors.`, `${foodTa}; கொலு பார்க்க வருவோருக்குச் சுண்டல்.`),
    see: ['navaratri'], sources: SRC,
  };
};

export const FESTIVALS_B = [
  {
    id: 'aadi-month', kind: 'festival', listed: false,
    names: B('Aadi month', 'ஆடி மாதம்'),
    aliases: ['aadi month', 'aadi masam', 'aadi maasam', 'adi masam', 'ஆடி மாதம்', 'ஆடி மாசம்'],
    deity: B('Amman (the Divine Mother)', 'அம்மன்'),
    rule: { solarMonth: 3 },
    ruleText: B('the Tamil month when the Sun is in Kataka (Cancer), mid-July to mid-August.', 'சூரியன் கடக ராசியில் இருக்கும் தமிழ் மாதம், ஜூலை நடுவிலிருந்து ஆகஸ்ட் நடு வரை.'),
    line: B('The month of Amman — Aadi Velli, Aadi Perukku, Aadi Pooram, Aadi Amavasai.', 'அம்மனின் மாதம் — ஆடி வெள்ளி, ஆடிப் பெருக்கு, ஆடிப் பூரம், ஆடி அமாவாசை.'),
    why: B('Aadi begins Dakshinayanam, the Sun’s southward half, traditionally devoted to worship. Amman temples hold festivals all month with koozh and pongal. Families traditionally avoid weddings and house-warming in Aadi, preferring to give the month to prayer and to farming (“Aadi pattam thedi vidhai” — sow seeds in Aadi). This is a custom, not a danger — follow your family’s practice.',
      'ஆடியில் தட்சிணாயனம் தொடங்குகிறது — வழிபாட்டுக்கு உரிய காலம் என்பது மரபு. மாதம் முழுவதும் அம்மன் கோவில்களில் கூழ், பொங்கலுடன் திருவிழா. இம்மாதத்தை வழிபாட்டுக்கும் விவசாயத்துக்கும் ("ஆடிப் பட்டம் தேடி விதை") ஒதுக்கி, திருமணம், புதுமனை புகுதல் போன்றவற்றைத் தவிர்ப்பது குடும்ப வழக்கம். இது வழக்கமே, ஆபத்து அல்ல — உங்கள் குடும்ப முறையைப் பின்பற்றுங்கள்.'),
    how: B(['Visit Amman temples on Tuesdays and Fridays; offer koozh (ragi porridge) and pongal; light lamps.'], ['செவ்வாய், வெள்ளிக்கிழமைகளில் அம்மன் கோவில்; கூழ், பொங்கல் படைத்தல்; விளக்கேற்றல்.']),
    offer: B('Ragi koozh, mavilakku (rice-flour lamp), pongal.', 'கேழ்வரகுக் கூழ், மாவிளக்கு, பொங்கல்.'),
    temples: ['samayapuram', 'mangadu_kamakshi', 'thiruverkadu', 'kanchi_kamakshi'],
    see: ['aadi-velli', 'aadi-perukku', 'aadi-pooram', 'aadi-amavasai'], sources: SRC,
  },
  {
    id: 'aadi-velli', kind: 'vratham', mantra: 'ambal',
    names: B('Aadi Fridays (Aadi Velli)', 'ஆடி வெள்ளி'),
    aliases: ['aadi velli', 'adi velli', 'aadi friday', 'aadi vellikizhamai', 'ஆடி வெள்ளி', 'ஆடி வெள்ளிக்கிழமை'],
    deity: B('Amman, Mahalakshmi', 'அம்மன், மகாலட்சுமி'),
    rule: { weekly: 5, solar: [3] },
    ruleText: B('every Friday in the Tamil month of Aadi.', 'ஆடி மாதத்தின் ஒவ்வொரு வெள்ளிக்கிழமையும்.'),
    line: B('Fridays of Aadi for Amman — mavilakku, koozh and kumkum archanai.', 'அம்மனுக்கான ஆடி வெள்ளி — மாவிளக்கு, கூழ், குங்கும அர்ச்சனை.'),
    why: B('Aadi Fridays are the most popular days for Amman worship; married women pray for family welfare and girls for a good life. Mavilakku (rice-flour and jaggery lamp) is offered as thanksgiving.', 'அம்மன் வழிபாட்டுக்கு மிகப் பிரபலமான நாட்கள் ஆடி வெள்ளிகள்; சுமங்கலிகள் குடும்ப நலனுக்கும் பெண்கள் நல்வாழ்வுக்கும் வேண்டுவர். நன்றியாக மாவிளக்கு ஏற்றுவர்.'),
    how: B(['Light a lamp at home; make mavilakku or koozh; visit an Amman temple; offer kumkum archanai.'], ['வீட்டில் விளக்கேற்றல்; மாவிளக்கு அல்லது கூழ்; அம்மன் கோவில்; குங்கும அர்ச்சனை.']),
    offer: B('Mavilakku, koozh, sakkarai pongal, bangles and kumkum.', 'மாவிளக்கு, கூழ், சர்க்கரைப் பொங்கல், வளையல், குங்குமம்.'),
    temples: ['samayapuram', 'mangadu_kamakshi', 'thiruverkadu', 'melmaruvathur'], see: ['aadi-month'], sources: SRC,
  },
  {
    id: 'aadi-sevvai', kind: 'vratham', mantra: 'durga',
    names: B('Aadi Tuesdays (Aadi Sevvai)', 'ஆடி செவ்வாய்'),
    aliases: ['aadi sevvai', 'adi sevvai', 'aadi tuesday', 'aadi sevvai viratham', 'avvaiyar nombu', 'ஆடி செவ்வாய்', 'அவ்வையார் நோன்பு'],
    deity: B('Amman, Durga; Avvaiyar', 'அம்மன், துர்க்கை; அவ்வையார்'),
    rule: { weekly: 2, solar: [3] },
    ruleText: B('every Tuesday in Aadi.', 'ஆடி மாதத்தின் ஒவ்வொரு செவ்வாய்க்கிழமையும்.'),
    line: B('Tuesdays of Aadi for Amman; women’s Avvaiyar nombu in some homes.', 'அம்மனுக்கான ஆடி செவ்வாய்; சில வீடுகளில் பெண்களின் அவ்வையார் நோன்பு.'),
    why: B('Tuesday belongs to Shakti and Murugan; Aadi Tuesdays are kept with Amman worship. In some families women observe Avvaiyar nombu late at night with salt-free kozhukattai, praying for family welfare.', 'செவ்வாய் சக்திக்கும் முருகனுக்கும் உரியது; ஆடி செவ்வாயில் அம்மன் வழிபாடு. சில குடும்பங்களில் பெண்கள் இரவில் உப்பில்லாக் கொழுக்கட்டையுடன் அவ்வையார் நோன்பு நோற்று குடும்ப நலனுக்கு வேண்டுவர்.'),
    how: B(['Visit an Amman or Durga temple; offer lemon lamp or koozh as per local custom.'], ['அம்மன் அல்லது துர்க்கை கோவில்; உள்ளூர் வழக்கப்படி எலுமிச்சை விளக்கு அல்லது கூழ்.']),
    temples: ['samayapuram', 'patteeswaram_durgai'], sources: SRC,
  },
  {
    id: 'aadi-krithigai', kind: 'festival', fast: true, mantra: 'murugan',
    names: B('Aadi Krithigai', 'ஆடிக் கிருத்திகை'),
    aliases: ['aadi krithigai', 'aadi kiruthigai', 'aadi karthigai', 'adi krithigai', 'ஆடிக் கிருத்திகை', 'ஆடி கிருத்திகை', 'ஆடி கார்த்திகை'],
    deity: B('Lord Murugan', 'முருகப் பெருமான்'),
    rule: { star: 2, solar: [3] },
    ruleText: B('Karthigai (Krittika) star at sunrise in the month of Aadi.', 'ஆடி மாதத்தில் சூரிய உதயத்தில் கார்த்திகை நட்சத்திரம்.'),
    line: B('The biggest monthly Karthigai — kavadi and teppam at Thiruthani.', 'ஆண்டின் மிகப் பெரிய கிருத்திகை — திருத்தணியில் காவடி, தெப்பம்.'),
    why: B('Among the monthly Karthigai days, Aadi Krithigai is the grandest for Murugan; Thiruthani holds a three-day float festival and devotees bring flower kavadis.', 'மாதாந்திரக் கிருத்திகைகளில் முருகனுக்கு மிகப் பெரியது ஆடிக் கிருத்திகை; திருத்தணியில் மூன்று நாள் தெப்பத் திருவிழா, மலர்க் காவடிகள்.'),
    how: B(['Fast or eat simply; visit a Murugan temple; chant "Om Saravanabhava".'], ['விரதம் அல்லது எளிய உணவு; முருகன் கோவில்; "ஓம் சரவணபவ".']),
    temples: ['thiruthani', 'palani', 'tiruchendur', 'vadapalani'], see: ['karthigai'], sources: SRC,
  },
  {
    id: 'aadi-perukku', kind: 'festival', mantra: 'ambal',
    names: B('Aadi Perukku (Aadi 18)', 'ஆடிப் பெருக்கு (ஆடி 18)'),
    aliases: ['aadi perukku', 'adi perukku', 'aadi 18', 'pathinettam perukku', 'aadi padinettu', 'ஆடிப் பெருக்கு', 'ஆடி பெருக்கு', 'ஆடி 18', 'பதினெட்டாம் பெருக்கு'],
    deity: B('River Kaveri as Mother; Amman', 'காவிரி அன்னை; அம்மன்'),
    rule: { solarDay: [3, 18] },
    ruleText: B('the 18th day of the Tamil month of Aadi.', 'ஆடி மாதம் 18-ஆம் நாள்.'),
    line: B('Thanking the rivers (Kaveri) as monsoon waters rise — for prosperity and new beginnings.', 'பருவமழையால் நதிகள் (காவிரி) பெருகும்போது நன்றி — வளமும் புதுத் தொடக்கமும்.'),
    why: B('In Aadi the Kaveri swells with monsoon water that feeds the fields. On the 18th, families — especially women and newly-weds — gather at river banks to worship the river as a Mother, float lamps and tie the yellow thread, praying for prosperity. It is also considered good for starting farming.',
      'ஆடியில் பருவமழை நீரால் காவிரி பெருகி வயல்களுக்கு உயிர் தருகிறது. 18-ஆம் நாள் குடும்பங்கள் — குறிப்பாகப் பெண்களும் புதுமணத் தம்பதிகளும் — நதிக்கரையில் கூடி, நதியை அன்னையாக வழிபட்டு, விளக்கு மிதக்கவிட்டு, மஞ்சள் கயிறு கட்டி வளம் வேண்டுவர். விவசாயத் தொடக்கத்துக்கும் உகந்த நாள்.'),
    how: B(['At a river bank (or at home with a pot of water), offer turmeric, kumkum, flowers, fruits and lamps to the river.', 'Women tie new yellow threads (manjal kayiru); newly-weds offer the wedding garlands to the river.', 'Share kalanda sadham (variety rice) with family; take care near fast-flowing water.'],
      ['நதிக்கரையில் (அல்லது வீட்டில் ஒரு பாத்திர நீருக்கு) மஞ்சள், குங்குமம், மலர், பழம், விளக்கு படைத்தல்.', 'பெண்கள் புது மஞ்சள் கயிறு கட்டுதல்; புதுமணத் தம்பதிகள் திருமண மாலைகளை ஆற்றில் விடுதல்.', 'கலந்த சாதங்களைக் குடும்பத்துடன் பகிர்தல்; வேகமாக ஓடும் நீரருகில் கவனம்.']),
    offer: B('Chitrannam — lemon, tamarind, coconut, curd and sweet rice.', 'சித்திரான்னம் — எலுமிச்சை, புளி, தேங்காய், தயிர், இனிப்புச் சாதம்.'),
    temples: ['srirangam', 'thiruvanaikaval'],
    regional: B('Biggest along the Kaveri delta — Srirangam Amma Mandapam, Thiruvaiyaru, Mettur.', 'காவிரிக் கரையில் மிகப் பெரியது — ஸ்ரீரங்கம் அம்மா மண்டபம், திருவையாறு, மேட்டூர்.'),
    sources: SRC,
  },
  {
    id: 'aadi-amavasai', kind: 'festival', mantra: 'shiva',
    names: B('Aadi Amavasai', 'ஆடி அமாவாசை'),
    aliases: ['aadi amavasai', 'adi amavasai', 'aadi amavasya', 'ஆடி அமாவாசை'],
    deity: B('Ancestors (pitrus)', 'முன்னோர்கள்'),
    rule: { tithi: 29, at: 'sunrise', solar: [3] },
    ruleText: B('the Amavasai in the Tamil month of Aadi.', 'ஆடி மாதத்தில் வரும் அமாவாசை.'),
    line: B('The most important new moon for ancestors’ tharpanam, at the start of Dakshinayanam.', 'தட்சிணாயனத் தொடக்கத்தில் முன்னோர் தர்ப்பணத்துக்கு மிக முக்கிய அமாவாசை.'),
    why: B('Aadi Amavasai begins the pitru season of Dakshinayanam; tradition holds that ancestors come closest to earth then. Tharpanam at Rameswaram, Kanyakumari, Thiruvallur and river banks is believed to bring their blessings.', 'தட்சிணாயனத்தின் பித்ரு காலம் ஆடி அமாவாசையில் தொடங்குகிறது; அப்போது முன்னோர் பூமிக்கு மிக அருகில் வருவர் என்பது மரபு. ராமேஸ்வரம், கன்னியாகுமரி, நதிக்கரைகளில் தர்ப்பணம் அவர்கள் ஆசி தரும் என்பது நம்பிக்கை.'),
    how: B(['Holy bath and tharpanam with sesame and water; feed the needy and crows; light a lamp in the evening.'], ['புனித நீராடல், எள்-நீர் தர்ப்பணம்; ஏழைகளுக்கும் காக்கைக்கும் உணவு; மாலையில் விளக்கு.']),
    temples: ['rameswaram', 'kanyakumari'], see: ['amavasai'], sources: SRC,
  },
  {
    id: 'aadi-pooram', kind: 'festival', mantra: 'ambal',
    names: B('Aadi Pooram', 'ஆடிப் பூரம்'),
    aliases: ['aadi pooram', 'adi pooram', 'aadi puram', 'andal jayanthi', 'ஆடிப் பூரம்', 'ஆடி பூரம்', 'ஆண்டாள் ஜெயந்தி'],
    deity: B('Andal; Amman (valaikappu)', 'ஆண்டாள்; அம்மன் (வளைகாப்பு)'),
    rule: { star: 10, solar: [3] },
    ruleText: B('Pooram star in the month of Aadi.', 'ஆடி மாதத்தில் பூர நட்சத்திரம்.'),
    line: B('Birth star of Andal; bangle ceremony (valaikappu) for Amman.', 'ஆண்டாள் அவதார நட்சத்திரம்; அம்மனுக்கு வளைகாப்பு.'),
    why: B('Andal, found as a baby under a tulasi plant by Periyazhvar at Srivilliputhur, sang Thiruppavai and Nachiyar Thirumozhi and is believed to have merged with Lord Ranganatha. On Aadi Pooram, Amman is honoured with a valaikappu (bangle ceremony) as the Mother of the world, and the bangles are given to women as blessing.',
      'ஸ்ரீவில்லிபுத்தூரில் பெரியாழ்வார் துளசிச் செடியடியில் கண்டெடுத்த குழந்தை ஆண்டாள், திருப்பாவை, நாச்சியார் திருமொழி பாடி, அரங்கனோடு கலந்தாள் என்பது நம்பிக்கை. ஆடிப் பூரத்தில் உலக அன்னையான அம்மனுக்கு வளைகாப்பு நடத்தி, அந்த வளையல்களைப் பெண்களுக்கு ஆசியாக வழங்குவர்.'),
    how: B(['Visit an Andal or Amman temple; offer glass bangles; recite a few Thiruppavai pasurams.'], ['ஆண்டாள் அல்லது அம்மன் கோவில்; கண்ணாடி வளையல் சமர்ப்பித்தல்; சில திருப்பாவைப் பாசுரங்கள்.']),
    offer: B('Bangles, sakkarai pongal, akkaravadisal.', 'வளையல்கள், சர்க்கரைப் பொங்கல், அக்காரவடிசல்.'),
    temples: ['srivilliputhur', 'srirangam', 'samayapuram'], sources: SRC,
  },
  {
    id: 'varalakshmi', kind: 'vratham', fast: true, mantra: 'lakshmi',
    names: B('Varalakshmi Viratham', 'வரலட்சுமி விரதம்'),
    aliases: ['varalakshmi', 'varalakshmi viratham', 'varalakshmi vratham', 'varamahalakshmi', 'vara lakshmi', 'வரலட்சுமி', 'வரலட்சுமி விரதம்', 'வரலக்ஷ்மி'],
    deity: B('Goddess Varalakshmi (Mahalakshmi who grants boons)', 'வரலட்சுமி (வரம் தரும் மகாலட்சுமி)'),
    rule: { range: [7, 14], weekday: 5, lunar: [4], pick: 'last' },
    ruleText: B('the Friday just before (or on) the Shravana full moon — the full moon of Aadi/Aavani.', 'ச்ராவண பௌர்ணமிக்கு (ஆடி/ஆவணி பௌர்ணமி) முந்தைய அல்லது அன்றைய வெள்ளிக்கிழமை.'),
    line: B('Married women worship Lakshmi in a kalasam for the family’s welfare.', 'குடும்ப நலனுக்காகச் சுமங்கலிகள் கலசத்தில் லட்சுமியை வழிபடும் விரதம்.'),
    why: B('Tradition says Lakshmi appeared in a dream to Charumathi, a devoted wife, and taught her this vratham; worshipping Varalakshmi is believed to equal worshipping the eight Lakshmis — wealth, health, courage, knowledge, children and more.', 'பக்தியுள்ள சாருமதிக்குக் கனவில் தோன்றிய லட்சுமி இந்த விரதத்தைக் கற்றுக் கொடுத்தாள் என்பது மரபு; வரலட்சுமியை வழிபடுவது செல்வம், ஆரோக்கியம், தைரியம், கல்வி, மக்கட்பேறு என அஷ்டலட்சுமியையும் வழிபடுவதற்குச் சமம் என்பது நம்பிக்கை.'),
    how: B(['Thursday: clean the house, prepare the kalasam with rice, coins, turmeric, lemon and a decorated Amman face.', 'Friday morning: invite Lakshmi at the threshold, do pooja with flowers and lamps; tie the yellow nombu saradu on the right wrist.', 'Offer sweets; give vettrilai-paakku with blouse piece to other women.'],
      ['வியாழன்: வீட்டைச் சுத்தம் செய்து, அரிசி, நாணயம், மஞ்சள், எலுமிச்சை, அம்மன் முகத்துடன் கலசம் தயாரித்தல்.', 'வெள்ளி காலை: வாசலில் லட்சுமியை அழைத்து, மலர், விளக்குடன் பூஜை; வலது மணிக்கட்டில் மஞ்சள் நோன்புச் சரடு.', 'இனிப்புகள் படைத்தல்; பிற பெண்களுக்கு வெற்றிலை-பாக்கு, ரவிக்கைத் துணி வழங்குதல்.']),
    offer: B('Kozhukattai, payasam, sundal, vadai.', 'கொழுக்கட்டை, பாயசம், சுண்டல், வடை.'),
    regional: B('Widely observed in Tamil Nadu, Karnataka and Andhra Pradesh; less common in the North.', 'தமிழ்நாடு, கர்நாடகம், ஆந்திராவில் பரவலாக; வட இந்தியாவில் குறைவு.'), sources: SRC,
  },
  {
    id: 'avani-avittam', kind: 'festival', mantra: 'gayatri',
    names: B('Avani Avittam (Upakarma)', 'ஆவணி அவிட்டம் (உபாகர்மா)'),
    aliases: ['avani avittam', 'aavani avittam', 'upakarma', 'upakarmam', 'poonal', 'poonool', 'gayatri japam', 'ஆவணி அவிட்டம்', 'உபாகர்மா', 'பூணூல்'],
    deity: B('Vedic sages; Hayagriva', 'வேத ரிஷிகள்; ஹயக்ரீவர்'),
    rule: { tithi: 14, at: 'sunrise', lunar: [4] },
    ruleText: B('Shravana Pournami (Yajur Veda Upakarma); Gayatri japam is the next day.', 'ச்ராவண பௌர்ணமி (யஜுர் வேத உபாகர்மா); மறுநாள் காயத்ரி ஜபம்.'),
    line: B('Renewal of the sacred thread and of Vedic study.', 'பூணூல் மாற்றுதல், வேதக் கல்வியைப் புதுப்பித்தல்.'),
    why: B('Upakarma means a new beginning of Vedic study. Those who wear the sacred thread (poonal) change it with prayers, asking pardon for lapses of the past year; Hayagriva, the Lord of learning, is believed to have restored the Vedas on this day.', 'உபாகர்மா என்றால் வேதக் கல்வியின் புதுத் தொடக்கம். பூணூல் அணிவோர் கடந்த ஆண்டின் குறைகளுக்கு மன்னிப்பு வேண்டி, மந்திரங்களுடன் புதுப் பூணூல் அணிவர்; கல்விக் கடவுள் ஹயக்ரீவர் இந்நாளில் வேதங்களை மீட்டார் என்பது நம்பிக்கை.'),
    how: B(['Families follow their own Veda shakha with a priest; next day chant Gayatri 1008 times if possible.'], ['குடும்ப வேத சாகைப்படி புரோகிதருடன்; மறுநாள் முடிந்தால் 1008 காயத்ரி ஜபம்.']),
    regional: B('Rig and Sama Veda Upakarma may fall on other days. North India celebrates Raksha Bandhan on the same full moon.', 'ரிக், சாம வேத உபாகர்மா வேறு நாட்களில் வரலாம். அதே பௌர்ணமியில் வட இந்தியாவில் ரக்ஷா பந்தன்.'),
    see: ['raksha-bandhan'], sources: SRC,
  },
  {
    id: 'raksha-bandhan', kind: 'festival',
    names: B('Raksha Bandhan', 'ரக்ஷா பந்தன்'),
    aliases: ['raksha bandhan', 'rakhi', 'rakshabandhan', 'ரக்ஷா பந்தன்', 'ராக்கி'],
    rule: { sameAs: 'avani-avittam' },
    ruleText: B('Shravana Pournami (same day as Avani Avittam).', 'ச்ராவண பௌர்ணமி (ஆவணி அவிட்டம் அன்று).'),
    line: B('Sisters tie a rakhi; brothers promise protection — mainly North India.', 'சகோதரிகள் ராக்கி கட்டுதல்; சகோதரர்கள் பாதுகாப்பு வாக்கு — பெரும்பாலும் வட இந்தியா.'),
    why: B('A thread of love and protection between siblings; stories include Draupadi tying cloth to Krishna’s wounded finger.', 'உடன்பிறப்புகளிடையே அன்பும் பாதுகாப்பும் கொண்ட நூல்; கிருஷ்ணரின் காயம்பட்ட விரலில் திரௌபதி துணி கட்டிய கதை பிரபலம்.'),
    how: B(['Tie a rakhi, share sweets, give gifts.'], ['ராக்கி கட்டி, இனிப்பு பகிர்ந்து, பரிசு அளித்தல்.']), sources: SRC,
  },
  {
    id: 'onam', kind: 'festival',
    names: B('Onam (Thiruvonam)', 'ஓணம் (திருவோணம்)'),
    aliases: ['onam', 'thiruvonam festival', 'onam festival', 'ஓணம்', 'ஓணம் பண்டிகை'],
    deity: B('Mahabali, Vamana', 'மகாபலி, வாமனர்'),
    rule: { star: 21, solar: [4] },
    ruleText: B('Thiruvonam star in the month of Aavani (Chingam in Kerala).', 'ஆவணி (கேரளத்தில் சிங்கம்) மாதத் திருவோண நட்சத்திரம்.'),
    line: B('Kerala’s harvest festival welcoming King Mahabali home.', 'மகாபலி மன்னனை வரவேற்கும் கேரள அறுவடைத் திருவிழா.'),
    why: B('Mahabali, a generous asura king, gave Vamana three steps of land; Vamana grew and covered the worlds, and Bali offered his own head. Pleased with his humility, Vishnu allowed him to visit his people once a year — on Onam.', 'வள்ளல் அசுர மன்னன் மகாபலி வாமனருக்கு மூன்றடி நிலம் தந்தான்; வாமனர் விஸ்வரூபம் எடுத்து உலகங்களை அளக்க, பலி தன் தலையையே தந்தான். அவன் பணிவில் மகிழ்ந்த திருமால், ஆண்டுக்கு ஒருமுறை — ஓணத்தன்று — மக்களைக் காண வர அனுமதித்தார்.'),
    how: B(['Pookalam (flower rangoli), Onam sadhya on a banana leaf, new clothes.'], ['பூக்கோலம், வாழையிலையில் ஓண சத்யா, புத்தாடை.']),
    temples: ['guruvayur'], sources: SRC,
  },
  {
    id: 'krishna-jayanthi', kind: 'festival', fast: true, mantra: 'narayana',
    names: B('Krishna Jayanthi (Gokulashtami)', 'கிருஷ்ண ஜெயந்தி (கோகுலாஷ்டமி)'),
    aliases: ['krishna jayanthi', 'gokulashtami', 'janmashtami', 'krishna janmashtami', 'sri jayanthi', 'gokulastami', 'கிருஷ்ண ஜெயந்தி', 'கோகுலாஷ்டமி', 'ஜன்மாஷ்டமி', 'ஸ்ரீ ஜெயந்தி'],
    deity: B('Lord Krishna', 'ஸ்ரீ கிருஷ்ணர்'),
    rule: { tithi: 22, at: 'midnight', lunar: [4] },
    ruleText: B('Krishna Ashtami prevailing at midnight in Shravana (amanta) — Aavani month. Vaishnava temples that follow Rohini star (Sri Jayanthi) may keep a different day.', 'ச்ராவண (அமாந்த) தேய்பிறை அஷ்டமி நள்ளிரவில் இருக்கும் நாள் — ஆவணி மாதம். ரோகிணி நட்சத்திரத்தைப் பின்பற்றும் வைணவக் கோவில்கள் (ஸ்ரீ ஜெயந்தி) வேறு நாள் கொண்டாடலாம்.'),
    line: B('Birth of Lord Krishna at midnight — little footprints, butter and seedai.', 'நள்ளிரவில் கண்ணன் பிறப்பு — குட்டிப் பாதச்சுவடு, வெண்ணெய், சீடை.'),
    why: B('Krishna, the eighth avatar of Vishnu, was born at midnight in Kamsa’s prison at Mathura and carried across the Yamuna to Gokulam. His life teaches love (Gokulam), courage (Kamsa) and wisdom (the Bhagavad Gita).',
      'திருமாலின் எட்டாவது அவதாரமான கிருஷ்ணர் மதுராவில் கம்சனின் சிறையில் நள்ளிரவில் பிறந்து, யமுனையைக் கடந்து கோகுலத்துக்குக் கொண்டு செல்லப்பட்டார். அவர் வாழ்க்கை அன்பையும் (கோகுலம்), தைரியத்தையும் (கம்சன்), ஞானத்தையும் (பகவத் கீதை) கற்றுத் தருகிறது.'),
    story: B('Kamsa had been told that Devaki’s eighth child would end his rule, so he imprisoned Devaki and Vasudeva. When Krishna was born at midnight, the chains fell open and the guards slept; Vasudeva carried the baby through the stormy Yamuna, which parted for him, sheltered by the serpent Adisesha, and exchanged him with Yashoda’s newborn daughter at Gokulam.',
      'தேவகியின் எட்டாவது குழந்தை தன் ஆட்சியை முடிக்கும் என்று அறிந்த கம்சன், தேவகியையும் வசுதேவரையும் சிறையிலடைத்தான். நள்ளிரவில் கிருஷ்ணர் பிறந்ததும் சங்கிலிகள் விலகின, காவலர்கள் உறங்கினர்; ஆதிசேஷன் குடை பிடிக்க, வழிவிட்ட புயல் யமுனையைக் கடந்து, வசுதேவர் குழந்தையைக் கோகுலத்தில் யசோதையின் பெண் குழந்தையுடன் மாற்றி வைத்தார்.'),
    how: B(['Draw little feet with rice-flour paste from the door to the pooja room.', 'Fast till midnight if healthy (children and elders eat normally); decorate a cradle for baby Krishna.', 'Offer butter, milk, seedai, murukku, aval; read the Bhagavatam birth chapter or sing Krishna songs.'],
      ['வாசலிலிருந்து பூஜை அறை வரை அரிசி மாவில் குட்டிப் பாதங்கள் வரையுங்கள்.', 'உடல்நலம் அனுமதித்தால் நள்ளிரவு வரை விரதம் (குழந்தைகள், முதியவர்கள் வழக்கம்போல் உண்ணலாம்); குழந்தைக் கண்ணனுக்குத் தொட்டில் அலங்காரம்.', 'வெண்ணெய், பால், சீடை, முறுக்கு, அவல் படைத்து, பாகவதக் கண்ணன் பிறப்புப் பகுதி படியுங்கள் அல்லது கண்ணன் பாடல்கள் பாடுங்கள்.']),
    offer: B('Butter, aval (poha) with jaggery, uppu seedai, vella seedai, murukku, milk sweets.', 'வெண்ணெய், வெல்ல அவல், உப்புச் சீடை, வெல்லச் சீடை, முறுக்கு, பால் இனிப்புகள்.'),
    temples: ['guruvayur', 'triplicane', 'kumbakonam_sarangapani'],
    regional: B('North India celebrates Janmashtami with midnight puja and Dahi Handi the next day.', 'வட இந்தியாவில் நள்ளிரவுப் பூஜை, மறுநாள் தஹி ஹண்டி.'), sources: SRC,
  },
  {
    id: 'vinayagar-chathurthi', kind: 'festival', mantra: 'ganesha',
    names: B('Vinayagar Chathurthi', 'விநாயகர் சதுர்த்தி'),
    aliases: ['vinayagar chathurthi', 'vinayaka chaturthi', 'ganesh chaturthi', 'ganesha chaturthi', 'pillaiyar chathurthi', 'vinayagar sathurthi', 'ganapathi chathurthi', 'விநாயகர் சதுர்த்தி', 'பிள்ளையார் சதுர்த்தி', 'கணேஷ் சதுர்த்தி'],
    deity: B('Lord Vinayagar (Pillaiyar, Ganesha)', 'விநாயகர் (பிள்ளையார்)'),
    rule: { tithi: 3, at: 'midday', lunar: [5] },
    ruleText: B('Bhadrapada Shukla Chathurthi prevailing at midday — in Aavani (sometimes early Purattasi).', 'பாத்ரபத வளர்பிறைச் சதுர்த்தி நண்பகலில் இருக்கும் நாள் — ஆவணி மாதம் (சில ஆண்டுகள் புரட்டாசித் தொடக்கம்).'),
    line: B('Birthday of Pillaiyar — clay idol, kozhukattai and arugampul.', 'பிள்ளையார் பிறந்த நாள் — களிமண் சிலை, கொழுக்கட்டை, அருகம்புல்.'),
    why: B('Vinayagar, remover of obstacles and lord of beginnings, is worshipped first in every pooja. On His birthday, a clay idol is welcomed home, worshipped and later returned to water — reminding us that form comes from the earth and returns to it.',
      'தடைகளை நீக்குபவரும் தொடக்கங்களின் அதிபதியுமான விநாயகர் எல்லாப் பூஜையிலும் முதலில் வழிபடப்படுகிறார். அவர் பிறந்த நாளில் களிமண் சிலையை வீட்டுக்கு அழைத்து வழிபட்டு, பின் நீரில் கரைப்பது — வடிவம் மண்ணிலிருந்து வந்து மண்ணுக்கே திரும்புவதை நினைவூட்டுகிறது.'),
    story: B('Parvati shaped a child from turmeric paste and asked him to guard her door. Shiva, not knowing him, was stopped and in the struggle the boy lost his head. To console Parvati, Shiva placed an elephant’s head on him and made him Ganapathi, leader of the ganas, to be worshipped before all others.',
      'பார்வதி மஞ்சள் விழுதில் ஒரு குழந்தையை உருவாக்கி வாசலைக் காக்கச் சொன்னாள். அவனை அறியாத சிவனைத் தடுத்தபோது நடந்த போரில் சிறுவன் தலையை இழந்தான். பார்வதியைத் தேற்ற, சிவன் யானைத் தலையைப் பொருத்தி, கணங்களின் தலைவனான கணபதியாக்கி, அனைவருக்கும் முன் வழிபடப்பட வரம் தந்தார்.'),
    how: B(['Bring a small clay (eco-friendly) idol; place on a plank with a kolam and an umbrella.', 'Offer arugampul, erukku flower garland, kozhukattai, sundal; chant "Om Gam Ganapataye Namaha" or Vinayagar Agaval.', 'On the 1st, 3rd or 5th day, immerse the idol in a bucket or nearby water body respectfully.', 'Avoid looking at the Moon this night, as tradition says.'],
      ['சிறிய களிமண் (சுற்றுச்சூழலுக்கு உகந்த) சிலை; கோலமிட்ட பலகை மேல் குடையுடன் வையுங்கள்.', 'அருகம்புல், எருக்கம்பூ மாலை, கொழுக்கட்டை, சுண்டல் படைத்து, "ஓம் கம் கணபதயே நமஹ" அல்லது விநாயகர் அகவல் சொல்லுங்கள்.', '1, 3 அல்லது 5-ஆம் நாளில் சிலையை வாளி நீரில் அல்லது அருகிலுள்ள நீர்நிலையில் மரியாதையுடன் கரையுங்கள்.', 'மரபுப்படி இந்த இரவு சந்திரனைப் பார்ப்பதைத் தவிர்க்கவும்.']),
    offer: B('Modakam/kozhukattai (sweet and salt), sundal, appam, aval, fruits, arugampul.', 'மோதகம்/கொழுக்கட்டை (இனிப்பு, உப்பு), சுண்டல், அப்பம், அவல், பழங்கள், அருகம்புல்.'),
    temples: ['pillaiyarpatti', 'trichy_rockfort'],
    regional: B('Maharashtra celebrates with 10-day public pandals ending on Anant Chaturdashi.', 'மகாராஷ்டிராவில் 10 நாள் பொதுப் பந்தல்கள், அனந்த சதுர்த்தசியில் நிறைவு.'),
    see: ['sankatahara'], sources: SRC,
  },
  {
    id: 'purattasi-month', kind: 'festival', listed: false, mantra: 'narayana',
    names: B('Purattasi month', 'புரட்டாசி மாதம்'),
    aliases: ['purattasi month', 'purattasi masam', 'purattasi maasam', 'purattasi', 'புரட்டாசி மாதம்', 'புரட்டாசி'],
    deity: B('Lord Venkatesa (Perumal)', 'வெங்கடேசப் பெருமாள்'),
    rule: { solarMonth: 5 },
    ruleText: B('the Tamil month when the Sun is in Kanya (Virgo), mid-September to mid-October.', 'சூரியன் கன்னி ராசியில் இருக்கும் மாதம், செப்டம்பர் நடுவிலிருந்து அக்டோபர் நடு வரை.'),
    line: B('Perumal’s month — Saturdays, vegetarian food, Tirupati Brahmotsavam, Navaratri.', 'பெருமாள் மாதம் — சனிக்கிழமைகள், சைவ உணவு, திருப்பதி பிரம்மோற்சவம், நவராத்திரி.'),
    why: B('Purattasi is dedicated to Lord Venkatesa; many families eat only vegetarian food for the month and worship Perumal on Saturdays. The season change (end of monsoon heat) also makes light food sensible, elders say.', 'புரட்டாசி வெங்கடேசப் பெருமாளுக்கு உரியது; பல குடும்பங்கள் மாதம் முழுவதும் சைவ உணவு உண்டு சனிக்கிழமைகளில் பெருமாளை வழிபடுவர். பருவ மாற்றக் காலத்தில் லேசான உணவு நல்லது என்றும் பெரியவர்கள் சொல்வர்.'),
    how: B(['Keep Saturdays for Perumal; light a mavilakku; offer tulasi; visit a Perumal temple.'], ['சனிக்கிழமைகளில் பெருமாள் வழிபாடு; மாவிளக்கு; துளசி; பெருமாள் கோவில்.']),
    temples: ['tirumala', 'srirangam', 'triplicane'], see: ['purattasi-sani', 'navaratri', 'mahalaya-paksham'], sources: SRC,
  },
  {
    id: 'purattasi-sani', kind: 'vratham', fast: true, mantra: 'narayana',
    names: B('Purattasi Saturdays', 'புரட்டாசி சனிக்கிழமை'),
    aliases: ['purattasi sani', 'purattasi saturday', 'purattasi sanikizhamai', 'purattasi sanikilamai', 'புரட்டாசி சனி', 'புரட்டாசி சனிக்கிழமை'],
    deity: B('Lord Venkatesa', 'வெங்கடேசப் பெருமாள்'),
    rule: { weekly: 6, solar: [5] },
    ruleText: B('every Saturday in Purattasi.', 'புரட்டாசி மாதத்தின் ஒவ்வொரு சனிக்கிழமையும்.'),
    line: B('Saturdays for Perumal — mavilakku and thaligai.', 'பெருமாளுக்கான சனிக்கிழமைகள் — மாவிளக்கு, தளிகை.'),
    why: B('Saturday is dear to Lord Venkatesa; tradition says Saturn’s effects are eased by worshipping Perumal on Purattasi Saturdays.', 'சனிக்கிழமை வெங்கடேசருக்கு உகந்தது; புரட்டாசி சனிக்கிழமைகளில் பெருமாள் வழிபாடு சனியின் தாக்கத்தைக் குறைக்கும் என்பது மரபு.'),
    how: B(['Fast or eat simply till evening; light a mavilakku before Perumal; offer thaligai (rice, dal, vadai, payasam); visit a Perumal temple.'], ['மாலை வரை விரதம் அல்லது எளிய உணவு; பெருமாள் முன் மாவிளக்கு; தளிகை (சாதம், பருப்பு, வடை, பாயசம்); பெருமாள் கோவில்.']),
    offer: B('Mavilakku, thaligai, tulasi, sweet pongal.', 'மாவிளக்கு, தளிகை, துளசி, சர்க்கரைப் பொங்கல்.'),
    temples: ['tirumala', 'srinivasa_mangapuram', 'triplicane'], sources: SRC,
  },
  {
    id: 'mahalaya-paksham', kind: 'vratham', mantra: 'shiva',
    names: B('Mahalaya Paksham', 'மகாளய பட்சம்'),
    aliases: ['mahalaya paksham', 'mahalaya paksha', 'pitru paksha', 'pitru paksham', 'mahalayam', 'மகாளய பட்சம்', 'பித்ரு பட்சம்', 'மகாளயம்'],
    deity: B('Ancestors (pitrus)', 'முன்னோர்கள்'),
    rule: { span: { start: { tithi: 15, at: 'sunrise', lunar: [5] }, end: 'mahalaya-amavasai' } },
    ruleText: B('the 15 days of the waning Moon ending with Mahalaya Amavasai (Bhadrapada Krishna paksha).', 'மகாளய அமாவாசையில் முடியும் 15 நாள் தேய்பிறை (பாத்ரபத கிருஷ்ண பட்சம்).'),
    line: B('Fortnight for remembering ancestors with tharpanam and annadhanam.', 'தர்ப்பணம், அன்னதானம் மூலம் முன்னோரை நினைக்கும் பட்சம்.'),
    why: B('Tradition says that during Mahalaya Paksham ancestors come to their families’ homes. Even those who do not know a parent’s death tithi can offer tharpanam on any of these days, especially Mahalaya Amavasai. Karna’s story is linked to this fortnight.', 'மகாளய பட்சத்தில் முன்னோர்கள் தங்கள் குடும்பத்தினர் இல்லம் வருவர் என்பது மரபு. இறந்த திதி தெரியாதவர்களும் இந்நாட்களில், குறிப்பாக மகாளய அமாவாசையில், தர்ப்பணம் செய்யலாம். கர்ணன் கதை இந்தப் பட்சத்துடன் தொடர்புடையது.'),
    story: B('Karna, famous for giving gold all his life, found only gold to eat in heaven, because he had never given food. He was allowed to return to earth for fifteen days to feed people and offer water to his ancestors — those days became Mahalaya Paksham.', 'வாழ்நாள் முழுவதும் பொன் கொடுத்த கர்ணனுக்குச் சொர்க்கத்தில் உண்ண பொன்னே கிடைத்தது — அவன் அன்னதானம் செய்யவில்லை. பதினைந்து நாள் பூமிக்குத் திரும்பி உணவளித்து முன்னோருக்கு நீர் அளிக்க அனுமதி பெற்றான் — அந்த நாட்களே மகாளய பட்சம்.'),
    how: B(['Offer tharpanam on the parent’s tithi within the fortnight (or on Amavasai); feed the needy; avoid wasting food.'], ['பெற்றோரின் திதியில் (அல்லது அமாவாசையில்) தர்ப்பணம்; ஏழைகளுக்கு அன்னம்; உணவை வீணாக்காமல் இருத்தல்.']),
    regional: B('Called Pitru Paksha in North India; Bengal’s Durga Puja begins right after (Mahalaya).', 'வட இந்தியாவில் பித்ரு பட்சம்; அதன் பின் வங்காளத்தில் துர்கா பூஜை தொடக்கம் (மகாளயா).'),
    see: ['mahalaya-amavasai'], sources: SRC,
  },
  {
    id: 'mahalaya-amavasai', kind: 'festival', mantra: 'shiva',
    names: B('Mahalaya Amavasai', 'மகாளய அமாவாசை'),
    aliases: ['mahalaya amavasai', 'mahalaya amavasya', 'purattasi amavasai', 'mahalaya', 'மகாளய அமாவாசை', 'புரட்டாசி அமாவாசை'],
    deity: B('Ancestors (pitrus)', 'முன்னோர்கள்'),
    rule: { tithi: 29, at: 'sunrise', lunar: [5] },
    ruleText: B('the Amavasai of Bhadrapada (usually in Purattasi), just before Navaratri.', 'பாத்ரபத அமாவாசை (பெரும்பாலும் புரட்டாசியில்), நவராத்திரிக்கு முந்தைய நாள்.'),
    line: B('The greatest day of the year for ancestors’ tharpanam; Navaratri starts next day.', 'முன்னோர் தர்ப்பணத்துக்கு ஆண்டின் மிகப் பெரிய நாள்; மறுநாள் நவராத்திரி.'),
    why: B('Mahalaya Amavasai closes Mahalaya Paksham; tharpanam on this day is believed to reach all ancestors, even those whose dates are not known.', 'மகாளய பட்சத்தின் நிறைவு நாள்; இன்று செய்யும் தர்ப்பணம் தேதி தெரியாத முன்னோர் அனைவரையும் சேரும் என்பது நம்பிக்கை.'),
    how: B(['Holy bath and tharpanam with sesame and water; feed the needy, crows and cows; light a lamp.'], ['புனித நீராடல், எள்-நீர் தர்ப்பணம்; ஏழைகள், காக்கை, பசுவுக்கு உணவு; விளக்கேற்றல்.']),
    temples: ['rameswaram', 'kanyakumari'], see: ['mahalaya-paksham', 'navaratri'], sources: SRC,
  },
  {
    id: 'navaratri', kind: 'festival', listed: false, fast: true, mantra: 'durga',
    names: B('Navaratri', 'நவராத்திரி'),
    aliases: ['navaratri', 'navarathri', 'navratri', 'navarathiri', 'golu', 'kolu', 'bommai kolu', 'dasara', 'dussehra', 'durga puja', 'நவராத்திரி', 'கொலு', 'பொம்மைக் கொலு', 'தசரா'],
    deity: B('Durga, Lakshmi, Saraswathi — the Divine Mother', 'துர்க்கை, லட்சுமி, சரஸ்வதி — அன்னை பராசக்தி'),
    rule: { span: { start: { tithi: 0, at: 'sunrise', lunar: [6], kshaya: 'next' }, end: 'saraswathi-pooja' } },
    ruleText: B('from the Prathamai after Mahalaya Amavasai to Navami (Saraswathi Pooja); Vijayadasami is the 10th day.', 'மகாளய அமாவாசைக்குப் பின் பிரதமை முதல் நவமி (சரஸ்வதி பூஜை) வரை; 10-ஆம் நாள் விஜயதசமி.'),
    line: B('Nine nights of the Divine Mother — golu, sundal, and visiting homes.', 'அன்னையின் ஒன்பது இரவுகள் — கொலு, சுண்டல், இல்லங்களுக்குச் சென்று வருதல்.'),
    why: B('Navaratri celebrates the Goddess defeating Mahishasura after nine nights of battle. The first three days honour Durga (courage), the next three Lakshmi (prosperity) and the last three Saraswathi (knowledge). In Tamil homes, golu — steps of dolls showing gods, saints and daily life — welcomes guests, and women exchange thamboolam.',
      'ஒன்பது இரவுப் போருக்குப் பின் அன்னை மகிஷாசுரனை வென்றதைக் கொண்டாடுவது நவராத்திரி. முதல் மூன்று நாள் துர்க்கை (தைரியம்), அடுத்த மூன்று லட்சுமி (செல்வம்), கடைசி மூன்று சரஸ்வதி (கல்வி). தமிழ் இல்லங்களில் தெய்வங்கள், மகான்கள், அன்றாட வாழ்க்கையைக் காட்டும் படிக்கட்டுப் பொம்மைக் கொலு விருந்தினரை வரவேற்க, பெண்கள் தாம்பூலம் பரிமாறிக்கொள்வர்.'),
    story: B('Mahishasura, granted a boon that no man or god could defeat him, conquered the three worlds. The combined power of all the gods took form as Durga, riding a lion. She fought him for nine days as he kept changing shapes, and on the tenth (Vijayadasami) she overcame him in his buffalo form — hence Mahishasuramardini.',
      'எந்த ஆணாலும் தேவனாலும் தன்னை வெல்ல முடியாது என்ற வரம் பெற்ற மகிஷாசுரன் மூவுலகையும் வென்றான். தேவர்கள் அனைவரின் சக்தியும் சேர்ந்து சிங்க வாகனத் துர்க்கையாக உருவெடுத்தது. உருவம் மாற்றி மாற்றிப் போரிட்ட அவனுடன் ஒன்பது நாள் போரிட்டு, பத்தாம் நாள் (விஜயதசமி) எருமை வடிவில் அவனை வென்றாள் — மகிஷாசுரமர்த்தினி.'),
    extra: [{ key: 'days', title: B('Each day’s Goddess (Tamil tradition)', 'ஒவ்வொரு நாளின் அன்னை (தமிழ் மரபு)'), lines: B(NAVARATRI_DAYS.map((d, i) => `Day ${i + 1}: ${d[0]} — ${d[2]} Neivedyam: ${d[4]}.`), NAVARATRI_DAYS.map((d, i) => `${i + 1}-ஆம் நாள்: ${d[1]} — ${d[3]} நைவேத்தியம்: ${d[5]}.`)) }],
    how: B(['Set up golu on an odd number of steps (3, 5, 7, 9) with a kalasam; add one new doll each year if you like.', 'Light lamps morning and evening; offer the day’s neivedyam; sing or chant Lalitha Sahasranamam or Abhirami Anthathi.', 'Invite friends and neighbours; give thamboolam (betel, turmeric-kumkum, a small gift) and sundal.', 'Fasting is optional — many keep one meal a day; children and elders eat normally.'],
      ['ஒற்றைப்படைப் படிகளில் (3, 5, 7, 9) கலசத்துடன் கொலு; விரும்பினால் ஆண்டுதோறும் ஒரு புதுப் பொம்மை.', 'காலை, மாலை விளக்கேற்றி அன்றைய நைவேத்தியம் படைத்து, லலிதா சகஸ்ரநாமம் அல்லது அபிராமி அந்தாதி பாடுங்கள்.', 'நண்பர்கள், அக்கம்பக்கத்தாரை அழைத்து, தாம்பூலம் (வெற்றிலை, மஞ்சள்-குங்குமம், சிறு பரிசு), சுண்டல் வழங்குங்கள்.', 'விரதம் விருப்பம் சார்ந்தது — பலர் ஒருவேளை உணவு; குழந்தைகள், முதியவர்கள் வழக்கம்போல் உண்ணலாம்.']),
    offer: B('A different sundal each day (chickpea, green gram, peanut, rajma), sweet pongal, payasam.', 'நாள்தோறும் வெவ்வேறு சுண்டல் (கொண்டைக்கடலை, பாசிப்பயறு, வேர்க்கடலை, ராஜ்மா), சர்க்கரைப் பொங்கல், பாயசம்.'),
    temples: ['madurai_meenakshi', 'kanchi_kamakshi', 'mangadu_kamakshi', 'kanyakumari', 'samayapuram'],
    regional: B('Tamil Nadu: golu and Saraswathi/Ayudha Pooja on Navami. North India: Ram Lila and burning Ravana’s effigy on Dussehra. Bengal: Durga Puja pandals. Gujarat: garba dance. Mysuru: royal Dasara procession.', 'தமிழ்நாடு: கொலு, நவமியில் சரஸ்வதி/ஆயுத பூஜை. வட இந்தியா: ராம லீலா, தசராவில் ராவணன் உருவ எரிப்பு. வங்காளம்: துர்கா பூஜை பந்தல்கள். குஜராத்: கர்பா நடனம். மைசூரு: அரச தசரா ஊர்வலம்.'),
    see: ['saraswathi-pooja', 'vijayadasami', 'ayudha-pooja'], sources: SRC,
  },
  ...[1, 2, 3, 4, 5, 6, 7, 8, 9].map(navDay),
  {
    id: 'durgashtami', kind: 'festival', listed: false, mantra: 'durga',
    names: B('Durgashtami', 'துர்காஷ்டமி'),
    aliases: ['durgashtami', 'durga ashtami', 'maha ashtami', 'துர்காஷ்டமி', 'துர்கா அஷ்டமி'],
    deity: B('Goddess Durga', 'துர்க்கை'),
    rule: { tithi: 7, at: 'sunrise', lunar: [6] },
    ruleText: B('Ashvayuja Shukla Ashtami (Navaratri 8th tithi).', 'ஆச்வயுஜ வளர்பிறை அஷ்டமி (நவராத்திரி 8-ஆம் திதி).'),
    line: B('The Durga day of Navaratri.', 'நவராத்திரியின் துர்க்கை நாள்.'),
    why: B('Ashtami is when Durga’s battle reached its peak; in Bengal it is the main puja day.', 'அன்னையின் போர் உச்சம் அடைந்த அஷ்டமி; வங்காளத்தில் முக்கியப் பூஜை நாள்.'),
    how: B(['Lemon or ghee lamp to Durga; Durga Saptashati or Durga mantra.'], ['துர்க்கைக்கு எலுமிச்சை அல்லது நெய் விளக்கு; துர்கா சப்தசதி அல்லது துர்க்கை மந்திரம்.']),
    temples: ['patteeswaram_durgai'], sources: SRC,
  },
  {
    id: 'saraswathi-pooja', kind: 'festival',
    names: B('Saraswathi Pooja', 'சரஸ்வதி பூஜை'),
    aliases: ['saraswathi pooja', 'saraswathi puja', 'saraswati puja', 'saraswati pooja', 'sarasvathi pujai', 'saraswathy pooja', 'saraswathi poojai', 'saraswathi', 'navami pooja', 'mahanavami', 'maha navami', 'சரஸ்வதி பூஜை', 'சரஸ்வதி பூசை', 'சரஸ்வதி', 'மகா நவமி'],
    deity: B('Goddess Saraswathi', 'சரஸ்வதி தேவி'),
    rule: { tithi: 8, at: 'sunrise', lunar: [6] },
    ruleText: B('Mahanavami — Ashvayuja Shukla Navami prevailing at sunrise, the 9th day of Navaratri (late Purattasi / early Aippasi).', 'மகா நவமி — சூரிய உதயத்தில் இருக்கும் ஆச்வயுஜ வளர்பிறை நவமி, நவராத்திரி 9-ஆம் நாள் (புரட்டாசி இறுதி / ஐப்பசித் தொடக்கம்).'),
    line: B('Worship of Saraswathi, Goddess of learning — books and instruments are placed before Her.', 'கல்விக் கடவுள் சரஸ்வதி வழிபாடு — புத்தகங்கள், இசைக்கருவிகள் அன்னை முன் வைக்கப்படும்.'),
    why: B('Saraswathi is the Goddess of knowledge, music and the arts. On Navami of Navaratri, books, pens, instruments and tools of learning are placed before Her and not used for the day, as a thanksgiving for the knowledge we have and a prayer for clear understanding. The next morning (Vijayadasami) they are taken back with prayer to begin learning afresh.',
      'சரஸ்வதி கல்வி, இசை, கலைகளின் தெய்வம். நவராத்திரி நவமியில் புத்தகங்கள், பேனா, இசைக்கருவிகள் போன்ற கல்விக் கருவிகளை அன்னை முன் வைத்து, அன்று பயன்படுத்தாமல், பெற்ற அறிவுக்கு நன்றியும் தெளிவான புரிதலுக்கு வேண்டுதலும் செய்வர். மறுநாள் காலை (விஜயதசமி) வழிபாட்டுடன் எடுத்து மீண்டும் கற்கத் தொடங்குவர்.'),
    story: B('The Puranas describe Saraswathi as emerging from Brahma’s wisdom, holding the veena, a book and a rosary, seated on a white lotus with a swan — which tradition says can separate milk from water, as wisdom separates truth from falsehood. Kambar, it is said, received the grace to write his Ramayanam by worshipping Saraswathi at Koothanur.',
      'பிரம்மனின் ஞானத்திலிருந்து தோன்றிய சரஸ்வதி வீணை, புத்தகம், ஜபமாலை ஏந்தி, வெண்தாமரையில் அன்ன வாகனத்துடன் வீற்றிருப்பவள் என்று புராணங்கள் சொல்கின்றன. பாலையும் நீரையும் பிரிக்கும் அன்னம் போல, ஞானம் உண்மையையும் பொய்யையும் பிரிக்கும் என்பது மரபு. கூத்தனூரில் சரஸ்வதியை வழிபட்டே கம்பர் ராமாயணம் இயற்றும் அருள் பெற்றார் என்று சொல்லப்படுகிறது.'),
    how: B(['Clean the pooja space; place Saraswathi’s picture with books, notebooks, pens, instruments and children’s school bags.', 'Apply sandal and kumkum, decorate with flowers; light a lamp; offer the neivedyam.', 'Chant "Om Sri Saraswathyai Namaha" or Saraswathi Sthothram; children may write "ஓம்" or "அ" in rice.', 'Keep the books untouched until Vijayadasami morning, then read a few lines with prayer.'],
      ['பூஜை இடத்தைச் சுத்தம் செய்து, சரஸ்வதி படத்துடன் புத்தகங்கள், நோட்டுகள், பேனா, இசைக்கருவிகள், குழந்தைகளின் பள்ளிப் பைகள் வையுங்கள்.', 'சந்தனம், குங்குமம் இட்டு, மலர்களால் அலங்கரித்து, விளக்கேற்றி நைவேத்தியம் படையுங்கள்.', '"ஓம் ஸ்ரீ சரஸ்வத்யை நமஹ" அல்லது சரஸ்வதி ஸ்தோத்திரம் சொல்லுங்கள்; குழந்தைகள் அரிசியில் "ஓம்" அல்லது "அ" எழுதலாம்.', 'விஜயதசமி காலை வரை புத்தகங்களைத் தொடாமல் வைத்து, பின் வழிபாட்டுடன் சில வரிகள் படியுங்கள்.']),
    offer: B('Sakkarai pongal, sundal, aval, puffed rice (pori) with jaggery, fruits, white flowers.', 'சர்க்கரைப் பொங்கல், சுண்டல், அவல், பொரி-வெல்லம், பழங்கள், வெண்மலர்கள்.'),
    chant: { text: 'ஓம் ஸ்ரீ சரஸ்வத்யை நமஹ', translit: 'Om Sri Saraswathyai Namaha', meaning: B('Salutations to Goddess Saraswathi, giver of learning.', 'கல்வி தரும் சரஸ்வதி தேவிக்கு வணக்கம்.') },
    temples: ['kanchi_kamakshi', 'madurai_meenakshi'],
    regional: B('Tamil Nadu and Kerala keep Saraswathi Pooja on Navami together with Ayudha Pooja; in Kerala books are placed from Ashtami (Pooja Veppu). North and East India worship Saraswathi on Vasantha Panchami instead.', 'தமிழ்நாடு, கேரளத்தில் நவமியில் ஆயுத பூஜையுடன் சரஸ்வதி பூஜை; கேரளத்தில் அஷ்டமியிலிருந்தே புத்தகம் வைப்பர் (பூஜை வெப்பு). வட, கிழக்கு இந்தியாவில் வசந்த பஞ்சமியில் சரஸ்வதி வழிபாடு.'),
    see: ['ayudha-pooja', 'vijayadasami', 'navaratri'], sources: SRC,
  },
  {
    id: 'ayudha-pooja', kind: 'festival',
    names: B('Ayudha Pooja', 'ஆயுத பூஜை'),
    aliases: ['ayudha pooja', 'ayutha pooja', 'ayudha puja', 'ayudha poojai', 'vahana pooja', 'ஆயுத பூஜை', 'ஆயுத பூசை'],
    deity: B('The Divine Mother as the power in every tool', 'ஒவ்வொரு கருவியிலும் உள்ள அன்னை சக்தி'),
    rule: { sameAs: 'saraswathi-pooja' },
    ruleText: B('Mahanavami — the same day as Saraswathi Pooja.', 'மகா நவமி — சரஸ்வதி பூஜை அன்றே.'),
    line: B('Thanking our tools, machines and vehicles — the work that feeds us.', 'நம்மை வாழவைக்கும் கருவிகள், இயந்திரங்கள், வாகனங்களுக்கு நன்றி.'),
    why: B('After defeating Mahishasura, the Goddess’s weapons were honoured. In the same spirit, every worker honours the tools of their trade — a farmer’s plough, a driver’s vehicle, a tailor’s machine, a computer — thanking them as instruments of the Divine. Arjuna is also said to have taken back his weapons from the vanni tree on this day.',
      'மகிஷாசுரனை வென்ற பின் அன்னையின் ஆயுதங்கள் போற்றப்பட்டன. அதே உணர்வில் ஒவ்வொரு தொழிலாளியும் தம் கருவிகளை — விவசாயியின் கலப்பை, ஓட்டுநரின் வாகனம், தையல்காரரின் இயந்திரம், கணினி — இறைவனின் கருவிகளாக நன்றியுடன் வணங்குவர். அர்ஜுனன் வன்னி மரத்திலிருந்து தன் ஆயுதங்களை மீட்டதும் இந்நாளில் என்பது மரபு.'),
    how: B(['Clean and paint tools, machines, vehicles and the workplace; apply sandal-kumkum and tie flowers.', 'Do pooja with camphor; break an ash gourd (poosanikai) with kumkum for the vehicle if that is your custom — clear the pieces from the road afterwards for safety.', 'Rest the tools for the day.'],
      ['கருவிகள், இயந்திரங்கள், வாகனங்கள், பணியிடத்தைச் சுத்தம் செய்து, சந்தனம்-குங்குமம் இட்டு, மலர் கட்டுங்கள்.', 'கற்பூரத்துடன் பூஜை; வழக்கம் இருந்தால் வாகனத்துக்குக் குங்குமம் தடவிய பூசணிக்காய் உடைத்தல் — பின் பாதுகாப்புக்காகச் சாலையிலிருந்து துண்டுகளை அகற்றுங்கள்.', 'அன்று கருவிகளுக்கு ஓய்வு.']),
    offer: B('Pori-kadalai, sundal, sakkarai pongal, banana, sugarcane.', 'பொரி-கடலை, சுண்டல், சர்க்கரைப் பொங்கல், வாழை, கரும்பு.'),
    regional: B('Called Shastra Puja in parts of North India; Vishwakarma Puja in the East is a separate day.', 'வட இந்தியாவின் சில பகுதிகளில் சஸ்திர பூஜை; கிழக்கில் விஸ்வகர்மா பூஜை தனி நாள்.'),
    see: ['saraswathi-pooja', 'vijayadasami'], sources: SRC,
  },
  {
    id: 'vijayadasami', kind: 'festival', mantra: 'ambal',
    names: B('Vijayadasami', 'விஜயதசமி'),
    aliases: ['vijayadasami', 'vijaya dasami', 'vijayadashami', 'vidyarambham', 'aksharabhyasam', 'dussehra day', 'விஜயதசமி', 'விஜய தசமி', 'வித்யாரம்பம்'],
    deity: B('Goddess Durga (victory), Saraswathi', 'துர்க்கை (வெற்றி), சரஸ்வதி'),
    rule: { tithi: 9, at: 'sunrise', lunar: [6] },
    ruleText: B('Ashvayuja Shukla Dasami prevailing at sunrise — the day after Saraswathi Pooja.', 'சூரிய உதயத்தில் இருக்கும் ஆச்வயுஜ வளர்பிறைத் தசமி — சரஸ்வதி பூஜைக்கு மறுநாள்.'),
    line: B('Day of victory — children begin learning (Vidyarambham); new ventures start.', 'வெற்றியின் நாள் — குழந்தைகளுக்கு எழுத்தறிவித்தல் (வித்யாரம்பம்); புதுத் தொடக்கங்கள்.'),
    why: B('Vijayadasami marks the Goddess’s victory over Mahishasura, and in the Ramayanam tradition Rama’s victory over Ravana. It is considered auspicious for any new beginning, especially Vidyarambham — a child writing the first letters in rice.', 'மகிஷாசுரனை அன்னை வென்ற நாள்; ராமாயண மரபில் ராவணனை ராமர் வென்ற நாள். எந்தப் புதுத் தொடக்கத்துக்கும், குறிப்பாகக் குழந்தை அரிசியில் முதல் எழுத்து எழுதும் வித்யாரம்பத்துக்கு உகந்த நாள்.'),
    how: B(['Morning pooja; take back the books and tools from Saraswathi Pooja and use them first.', 'Vidyarambham: an elder or teacher guides the child to write "ஓம்" / "அ" in rice; begin music or dance lessons.', 'Visit temples; in the evening, golu dolls are gently laid to rest (bommai thoongavaithal).'],
      ['காலைப் பூஜை; சரஸ்வதி பூஜைக்கு வைத்த புத்தகங்கள், கருவிகளை எடுத்து முதலில் பயன்படுத்துங்கள்.', 'வித்யாரம்பம்: பெரியவர் அல்லது ஆசிரியர் குழந்தையின் கையைப் பிடித்து அரிசியில் "ஓம்" / "அ" எழுதச் செய்தல்; இசை, நடன வகுப்புத் தொடக்கம்.', 'கோவில் தரிசனம்; மாலையில் கொலு பொம்மைகளைப் படுக்க வைத்தல்.']),
    offer: B('Payasam, sundal, sweet pongal.', 'பாயசம், சுண்டல், சர்க்கரைப் பொங்கல்.'),
    temples: ['madurai_meenakshi', 'mangadu_kamakshi', 'chottanikkara'],
    regional: B('North India: Dussehra with Ravana effigy burning; Bengal: Durga idol immersion (Bijoya); Mysuru: Jamboo Savari.', 'வட இந்தியா: ராவணன் உருவ எரிப்புடன் தசரா; வங்காளம்: துர்க்கை விசர்ஜனம் (பிஜோயா); மைசூரு: ஜம்பூ சவாரி.'),
    see: ['saraswathi-pooja', 'navaratri'], sources: SRC,
  },
  {
    id: 'deepavali', kind: 'festival', mantra: 'lakshmi',
    names: B('Deepavali', 'தீபாவளி'),
    aliases: ['deepavali', 'diwali', 'deepawali', 'dipavali', 'thipavali', 'naraka chaturdashi', 'naraka chathurdasi', 'ganga snanam', 'தீபாவளி', 'நரக சதுர்த்தசி', 'கங்கா ஸ்நானம்'],
    deity: B('Lord Krishna, Satyabhama; Mahalakshmi', 'கிருஷ்ணர், சத்யபாமா; மகாலட்சுமி'),
    rule: { tithi: 28, at: 'sunrise', lunar: [6] },
    ruleText: B('Naraka Chathurdasi — Ashvayuja Krishna Chathurdasi prevailing at dawn/sunrise (Tamil tradition); usually in Aippasi.', 'நரக சதுர்த்தசி — விடியல்/சூரிய உதயத்தில் இருக்கும் ஆச்வயுஜ தேய்பிறைச் சதுர்த்தசி (தமிழ் மரபு); பெரும்பாலும் ஐப்பசியில்.'),
    line: B('Festival of lights — oil bath before dawn (Ganga snanam), new clothes, sweets.', 'ஒளியின் திருவிழா — விடியற்காலை எண்ணெய்க் குளியல் (கங்கா ஸ்நானம்), புத்தாடை, இனிப்பு.'),
    why: B('In Tamil Nadu Deepavali celebrates Krishna’s victory over Narakasura, who had imprisoned many and troubled the worlds. Narakasura’s last wish was that people celebrate the day with lights and joy. The pre-dawn oil bath is called Ganga snanam because tradition says the Ganga is present in all water at that hour.',
      'தமிழ்நாட்டில் தீபாவளி, பலரைச் சிறைப்படுத்தி உலகங்களைத் துன்புறுத்திய நரகாசுரனைக் கிருஷ்ணர் வென்றதைக் கொண்டாடுகிறது. மக்கள் அந்நாளை விளக்கேற்றி மகிழ்ச்சியுடன் கொண்டாட வேண்டும் என்பதே நரகாசுரனின் கடைசி வேண்டுகோள். அந்நேரத்தில் எல்லா நீரிலும் கங்கை இருப்பாள் என்பதால் விடியற்காலை எண்ணெய்க் குளியல் "கங்கா ஸ்நானம்" எனப்படுகிறது.'),
    story: B('Narakasura, son of Bhudevi, became arrogant with a boon and held 16,000 women captive. Krishna went to battle with Satyabhama — an incarnation of Bhudevi — as His charioteer. When Krishna was struck and fell, Satyabhama took up the bow and defeated Naraka. Realising his mistakes, Naraka asked that his end be remembered with lamps and happiness.',
      'பூமாதேவியின் மகன் நரகாசுரன் வரத்தால் கர்வம் கொண்டு 16,000 பெண்களைச் சிறைப்படுத்தினான். பூமாதேவியின் அவதாரமான சத்யபாமா தேரோட்ட, கிருஷ்ணர் போருக்குச் சென்றார். கிருஷ்ணர் அம்பு பட்டு வீழ்ந்ததுபோல் நடிக்க, சத்யபாமா வில்லேந்தி நரகனை வென்றாள். தவறை உணர்ந்த நரகன், தன் முடிவை விளக்குகளோடும் மகிழ்ச்சியோடும் நினைவுகூர வேண்டும் என்று வேண்டினான்.'),
    how: B(['Before sunrise: elders apply sesame oil on everyone’s head; bath with shikakai; Deepavali lehiyam (marundhu) after the bath.', 'Wear new clothes after offering them at the pooja; take blessings of elders.', 'Light lamps in the evening; share sweets with neighbours; if you burst crackers, do it with adults, water nearby, and within local time limits — be kind to animals and elders.', 'Many do Lakshmi-Kubera pooja on the Amavasai evening.'],
      ['சூரிய உதயத்துக்கு முன்: பெரியவர்கள் அனைவர் தலையிலும் நல்லெண்ணெய் வைத்தல்; சீயக்காய்க் குளியல்; பின் தீபாவளி லேகியம் (மருந்து).', 'பூஜையில் வைத்த புத்தாடை அணிந்து பெரியவர்களிடம் ஆசி பெறுதல்.', 'மாலையில் விளக்கேற்றல்; அக்கம்பக்கத்தாருடன் இனிப்பு பகிர்தல்; பட்டாசு வெடித்தால் பெரியவர் துணையுடன், அருகில் தண்ணீருடன், உள்ளூர் நேரக் கட்டுப்பாட்டுக்குள் — விலங்குகள், முதியவர்கள் மீது கருணை.', 'பலர் அமாவாசை மாலையில் லட்சுமி-குபேர பூஜை செய்வர்.']),
    offer: B('Deepavali lehiyam, adhirasam, murukku, mysore pak, laddu, gulab jamun.', 'தீபாவளி லேகியம், அதிரசம், முறுக்கு, மைசூர் பாக், லட்டு, குலாப் ஜாமூன்.'),
    regional: B('North India celebrates Lakshmi Puja on the Amavasai night (often the next day) and Rama’s return to Ayodhya; Gujarat starts the new year the day after.', 'வட இந்தியாவில் அமாவாசை இரவு (பெரும்பாலும் மறுநாள்) லட்சுமி பூஜை, ராமர் அயோத்தி திரும்பியதைக் கொண்டாடுவர்; குஜராத்தில் மறுநாள் புத்தாண்டு.'),
    see: ['kedara-gowri', 'skanda-sashti'], sources: SRC,
  },
  {
    id: 'kedara-gowri', kind: 'vratham', fast: true, mantra: 'shiva',
    names: B('Kedara Gowri Vratham', 'கேதார கௌரி விரதம்'),
    aliases: ['kedara gowri', 'kedara gowri vratham', 'kedara gauri', 'kedaram', 'nonbu kedaram', 'கேதார கௌரி', 'கேதார கௌரி விரதம்', 'கேதார நோன்பு'],
    deity: B('Shiva and Parvati (Ardhanareeswarar)', 'சிவன்-பார்வதி (அர்த்தநாரீஸ்வரர்)'),
    rule: { tithi: 29, at: 'sunrise', lunar: [6] },
    ruleText: B('Deepavali Amavasai (Ashvayuja Amavasai).', 'தீபாவளி அமாவாசை (ஆச்வயுஜ அமாவாசை).'),
    line: B('Couples’ vratham recalling Parvati’s penance to become one with Shiva.', 'சிவனுடன் ஒன்றாக அன்னை செய்த தவத்தை நினைக்கும் தம்பதிகளின் விரதம்.'),
    why: B('Parvati observed the Kedara vratham to become one half of Shiva — Ardhanareeswarar. Families observe it for unity and harmony between husband and wife, tying the 21-knot nonbu saradu.', 'சிவனின் பாதியாக — அர்த்தநாரீஸ்வரராக — ஆக அன்னை பார்வதி கேதார விரதம் நோற்றாள். கணவன்-மனைவி ஒற்றுமைக்காகக் குடும்பங்கள் இதைக் கடைப்பிடித்து, 21 முடிச்சு நோன்புச் சரடு கட்டுவர்.'),
    how: B(['Fast till the evening pooja if healthy; offer 21 items (adhirasam, fruits, betel) to Kedareswarar; tie the sacred thread.'], ['உடல்நலம் அனுமதித்தால் மாலைப் பூஜை வரை விரதம்; கேதாரேஸ்வரருக்கு 21 வகை (அதிரசம், பழம், வெற்றிலை) படைத்தல்; நோன்புச் சரடு கட்டுதல்.']),
    offer: B('Adhirasam, 21 betel leaves and areca nuts, fruits.', 'அதிரசம், 21 வெற்றிலை-பாக்கு, பழங்கள்.'), sources: SRC,
  },
  {
    id: 'skanda-sashti', kind: 'festival', fast: true, mantra: 'murugan', listed: false,
    names: B('Kanda Sashti (6 days)', 'கந்த சஷ்டி (6 நாள்)'),
    aliases: ['kanda sashti', 'kanda sashti viratham', 'skanda sashti vratham', 'kandha sashti viratham', 'கந்த சஷ்டி விரதம்', 'skanda sashti', 'kandha sashti', 'kanda shasti', 'skanda shashti', 'kanda sasti', 'கந்த சஷ்டி', 'ஸ்கந்த சஷ்டி', 'கந்தசஷ்டி'],
    deity: B('Lord Murugan', 'முருகப் பெருமான்'),
    rule: { span: { start: { tithi: 0, at: 'sunrise', lunar: [7], kshaya: 'next' }, end: 'soorasamharam' } },
    ruleText: B('six days from the Prathamai after Deepavali Amavasai to Shukla Sashti (Soorasamharam) in Aippasi; Thirukalyanam is the 7th day.', 'தீபாவளி அமாவாசைக்குப் பின் பிரதமை முதல் வளர்பிறைச் சஷ்டி (சூரசம்ஹாரம்) வரை ஆறு நாள் — ஐப்பசியில்; 7-ஆம் நாள் திருக்கல்யாணம்.'),
    line: B('Six-day fast for Murugan ending with Soorasamharam at Tiruchendur.', 'திருச்செந்தூர் சூரசம்ஹாரத்தில் முடியும் ஆறு நாள் முருகன் விரதம்.'),
    why: B('Kanda Sashti recalls Murugan’s six-day battle with Soorapadman and his brothers, which ended in victory on Sashti. Devotees fast for six days, read Kanda Sashti Kavasam (composed by Devaraya Swamigal) and gather at Tiruchendur, where the battle is enacted on the seashore.',
      'சூரபத்மன், அவன் சகோதரர்களுடன் முருகன் ஆறு நாள் போரிட்டு சஷ்டியில் வென்றதை நினைவூட்டுவது கந்த சஷ்டி. பக்தர்கள் ஆறு நாள் விரதமிருந்து, தேவராய சுவாமிகள் இயற்றிய கந்த சஷ்டி கவசம் படித்து, கடற்கரையில் போர் நிகழ்த்திக் காட்டப்படும் திருச்செந்தூரில் கூடுவர்.'),
    how: B(['Choose a level that suits your health: one meal a day, fruits and milk, or simply prayer each day.', 'Read Kanda Sashti Kavasam morning and evening; many stay at Tiruchendur for the six days.', 'On Sashti evening watch the Soorasamharam; break the fast after the next day’s Thirukalyanam or that night, as your family does.', 'Children, the elderly, pregnant women and anyone unwell should not fast — prayer is enough.'],
      ['உடல்நிலைக்கு ஏற்ற நிலை தேர்ந்தெடுங்கள்: ஒருவேளை உணவு, பழம்-பால், அல்லது தினமும் பிரார்த்தனை மட்டும்.', 'காலை, மாலை கந்த சஷ்டி கவசம்; பலர் ஆறு நாளும் திருச்செந்தூரில் தங்குவர்.', 'சஷ்டி மாலை சூரசம்ஹாரம் தரிசனம்; குடும்ப வழக்கப்படி அன்றிரவு அல்லது மறுநாள் திருக்கல்யாணத்துக்குப் பின் விரதம் முடித்தல்.', 'குழந்தைகள், முதியவர்கள், கர்ப்பிணிகள், உடல்நலம் இல்லாதவர்கள் விரதம் வேண்டாம் — பிரார்த்தனையே போதும்.']),
    offer: B('Panchamritam, milk, fruits, red flowers; vel-shaped lamp.', 'பஞ்சாமிர்தம், பால், பழங்கள், சிவப்பு மலர்கள்.'),
    temples: ['tiruchendur', 'thiruparankundram', 'palani', 'swamimalai', 'thiruthani', 'pazhamudircholai'],
    see: ['soorasamharam', 'sashti'], sources: SRC,
  },
  {
    id: 'soorasamharam', kind: 'festival', fast: true, mantra: 'murugan',
    names: B('Soorasamharam (Kanda Sashti)', 'சூரசம்ஹாரம் (கந்த சஷ்டி)'),
    aliases: ['soorasamharam', 'soora samharam', 'surasamharam', 'soorasamhaaram', 'சூரசம்ஹாரம்', 'சூர சம்ஹாரம்'],
    deity: B('Lord Murugan', 'முருகப் பெருமான்'),
    rule: { tithi: 5, at: 'sunrise', lunar: [7] },
    ruleText: B('Kartika Shukla Sashti — the 6th day after Deepavali Amavasai (Aippasi).', 'கார்த்திக வளர்பிறைச் சஷ்டி — தீபாவளி அமாவாசைக்குப் பின் 6-ஆம் நாள் (ஐப்பசி).'),
    line: B('Murugan’s victory over Soorapadman, enacted on the Tiruchendur shore.', 'சூரபத்மனை முருகன் வென்றது — திருச்செந்தூர் கடற்கரையில் நிகழ்த்தல்.'),
    why: B('On the sixth day Murugan’s Vel split Soorapadman, who turned into a mango tree in the sea; the halves became the peacock and the rooster. Tradition sees it as the victory of wisdom over ego — and even the defeated is given a place near the Lord.', 'ஆறாம் நாள் கடலில் மாமரமாக நின்ற சூரபத்மனை முருகனின் வேல் பிளக்க, இரு பாதிகளும் மயிலும் சேவலும் ஆயின. ஆணவத்தின் மேல் ஞானத்தின் வெற்றி — வெல்லப்பட்டவனுக்கும் இறைவன் அருகே இடம் — என்பது மரபின் பொருள்.'),
    how: B(['Watch the Soorasamharam (in person or live); Thirukalyanam of Murugan and Deivanai is next day.'], ['சூரசம்ஹாரம் தரிசனம் (நேரில் அல்லது நேரலை); மறுநாள் முருகன்-தெய்வானை திருக்கல்யாணம்.']),
    temples: ['tiruchendur', 'thiruparankundram'], see: ['skanda-sashti'], sources: SRC,
  },
  {
    id: 'ayyappa-mandala', kind: 'vratham', fast: true,
    names: B('Sabarimala Mandala season (Ayyappan viratham)', 'சபரிமலை மண்டல காலம் (ஐயப்ப விரதம்)'),
    aliases: ['ayyappan viratham', 'ayyappa viratham', 'sabarimala viratham', 'mandala viratham', 'malai podu', 'maalai podu', 'ayyappan malai', 'sabarimala season', 'ஐயப்ப விரதம்', 'ஐயப்பன் மாலை', 'சபரிமலை விரதம்', 'மண்டல விரதம்', 'மாலை போடுதல்'],
    deity: B('Lord Ayyappan (Dharma Sastha)', 'ஐயப்பன் (தர்ம சாஸ்தா)'),
    rule: { solarDay: [7, 1] },
    ruleText: B('Karthigai 1 — devotees wear the mala and keep a 41-day mandala viratham; the season peaks at Mandala Pooja and Makaravilakku (Thai 1).', 'கார்த்திகை 1 — மாலை அணிந்து 41 நாள் மண்டல விரதம்; மண்டல பூஜை, மகரவிளக்கு (தை 1) உச்சம்.'),
    line: B('41-day disciplined vratham before the Sabarimala pilgrimage.', 'சபரிமலை யாத்திரைக்கு முன் 41 நாள் ஒழுக்க விரதம்.'),
    why: B('Devotees (called Swami) wear a tulasi or rudraksha mala, wear black or blue, sleep simply, eat vegetarian food and see the Lord in everyone — every devotee is called "Swami". The discipline is meant to prepare body and mind for the climb to Sabarimala.', 'பக்தர்கள் துளசி/ருத்திராட்ச மாலை அணிந்து, கருப்பு அல்லது நீல ஆடை, எளிய படுக்கை, சைவ உணவுடன், அனைவரிலும் இறைவனைக் காண்பர் — ஒவ்வொருவரையும் "சாமி" என்றழைப்பர். சபரிமலை ஏற்றத்துக்கு உடலையும் மனத்தையும் தயார் செய்வதே இந்த ஒழுக்கம்.'),
    how: B(['Wear the mala from a guru swami; keep simple food, no alcohol or tobacco, kind speech.', 'Carry the irumudi on the journey; walk at your own pace and take medical advice if you have heart or knee conditions.'], ['குருசாமியிடம் மாலை அணிதல்; எளிய உணவு, மது-புகையிலை தவிர்ப்பு, இனிய பேச்சு.', 'யாத்திரையில் இருமுடி; உங்கள் வேகத்தில் நடங்கள்; இதயம், முழங்கால் பிரச்சினை இருந்தால் மருத்துவ ஆலோசனை.']),
    temples: ['sabarimala'], see: ['makara-vilakku'], sources: SRC,
  },
  {
    id: 'makara-vilakku', kind: 'festival',
    names: B('Makaravilakku (Sabarimala)', 'மகரவிளக்கு (சபரிமலை)'),
    aliases: ['makaravilakku', 'makara vilakku', 'makara jyothi', 'makara jyoti', 'மகரவிளக்கு', 'மகர ஜோதி'],
    deity: B('Lord Ayyappan', 'ஐயப்பன்'),
    rule: { sameAs: 'thai-pongal' },
    ruleText: B('Makara Sankranti (Thai 1) evening.', 'மகர சங்கராந்தி (தை 1) மாலை.'),
    line: B('The sacred lamp seen at Ponnambalamedu on Makara Sankranti evening.', 'மகர சங்கராந்தி மாலை பொன்னம்பலமேட்டில் காணும் தீப ஒளி.'),
    why: B('After the Thiruvabharanam (sacred ornaments) are adorned on Ayyappan, the Makaravilakku is shown at Ponnambalamedu; devotees chant “Swamiye Saranam Ayyappa”.', 'திருவாபரணம் அணிவிக்கப்பட்ட பின் பொன்னம்பலமேட்டில் மகரவிளக்கு காட்டப்படுகிறது; பக்தர்கள் "சுவாமியே சரணம் ஐயப்பா" என்று முழங்குவர்.'),
    how: B(['Pray at home or a Sastha temple if you cannot travel; follow crowd-safety guidance at the hills.'], ['பயணிக்க முடியாவிட்டால் வீட்டில் அல்லது சாஸ்தா கோவிலில் வழிபாடு; மலையில் கூட்டப் பாதுகாப்பு வழிகாட்டலைப் பின்பற்றுங்கள்.']),
    temples: ['sabarimala'], sources: SRC,
  },
  {
    id: 'karthigai-somavaram', kind: 'vratham', fast: true, mantra: 'shiva',
    names: B('Karthigai Mondays (Somavaram)', 'கார்த்திகை சோமவாரம்'),
    aliases: ['karthigai somavaram', 'karthikai somavaram', 'kartika somavaram', 'karthigai monday', 'சோமவாரம்', 'கார்த்திகை சோமவாரம்', 'கார்த்திகை திங்கள்'],
    deity: B('Lord Shiva', 'சிவபெருமான்'),
    rule: { weekly: 1, solar: [7] },
    ruleText: B('every Monday in the Tamil month of Karthigai.', 'கார்த்திகை மாதத்தின் ஒவ்வொரு திங்கள்கிழமையும்.'),
    line: B('Mondays of Karthigai — 108 or 1008 conch (sangabhishekam) for Shiva.', 'கார்த்திகைத் திங்கள் — சிவனுக்கு 108/1008 சங்காபிஷேகம்.'),
    why: B('Monday is the Moon’s day and Karthigai is Shiva’s month of light; together they are believed to be especially dear to Shiva. The Moon (Soma) is said to have been freed from a curse by worshipping Shiva on Karthigai Mondays.', 'திங்கள் சந்திரனின் நாள்; கார்த்திகை சிவனின் ஒளி மாதம் — இரண்டும் சேர்வது சிவனுக்கு மிக உகந்தது. கார்த்திகைத் திங்களில் சிவனை வழிபட்டுச் சந்திரன் சாபம் நீங்கப் பெற்றான் என்பது கதை.'),
    how: B(['Fast lightly till evening; visit a Shiva temple for sangabhishekam; chant "Om Namah Shivaya".'], ['மாலை வரை லேசான விரதம்; சிவன் கோவிலில் சங்காபிஷேக தரிசனம்; "ஓம் நமசிவாய".']),
    temples: ['tiruvannamalai', 'mylapore', 'thanjavur_big'], sources: SRC,
  },
  {
    id: 'karthigai-deepam', kind: 'festival', mantra: 'shiva',
    names: B('Karthigai Deepam', 'கார்த்திகை தீபம்'),
    aliases: ['karthigai deepam', 'karthikai deepam', 'karthigai deebam', 'thiru karthigai', 'kartika deepam', 'annamalai deepam', 'tiruvannamalai deepam', 'maha deepam', 'bharani deepam', 'கார்த்திகை தீபம்', 'திருக்கார்த்திகை', 'கார்த்திகை தீப', 'மகா தீபம்', 'பரணி தீபம்'],
    deity: B('Lord Shiva as Annamalaiyar (column of light); Murugan', 'அண்ணாமலையார் (ஒளிப்பிழம்பு); முருகன்'),
    rule: { star: 2, solar: [7], twice: 'pournami' },
    ruleText: B('Karthigai (Krittika) star at sunrise in the Tamil month of Karthigai, usually with the full moon. At Tiruvannamalai, Bharani Deepam is lit at 4 AM and the Maha Deepam on the hill at about 6 PM the same day.', 'கார்த்திகை மாதத்தில் சூரிய உதயத்தில் கார்த்திகை நட்சத்திரம் — பெரும்பாலும் பௌர்ணமியுடன். திருவண்ணாமலையில் அதிகாலை 4 மணிக்குப் பரணி தீபம், அன்று மாலை சுமார் 6 மணிக்கு மலை மேல் மகா தீபம்.'),
    line: B('Rows of lamps in every home; the Maha Deepam on Tiruvannamalai hill.', 'ஒவ்வொரு வீட்டிலும் அகல் விளக்கு வரிசை; திருவண்ணாமலை மலை மேல் மகா தீபம்.'),
    why: B('Karthigai Deepam celebrates Shiva appearing as an endless column of light at Tiruvannamalai, humbling Brahma and Vishnu — the light that has no beginning or end. Lamps in every home symbolise driving away the darkness of ignorance. It is one of the oldest Tamil festivals, mentioned in Sangam poetry as "Karthigai vilakkeedu".',
      'பிரம்மனும் விஷ்ணுவும் அடிமுடி காண முடியாத எல்லையற்ற ஒளிப்பிழம்பாகச் சிவன் திருவண்ணாமலையில் தோன்றியதைக் கொண்டாடுவது கார்த்திகை தீபம். ஒவ்வொரு வீட்டு விளக்கும் அறியாமை இருளை அகற்றுவதைக் குறிக்கிறது. சங்க இலக்கியத்தில் "கார்த்திகை விளக்கீடு" என்று குறிப்பிடப்படும் மிகப் பழைய தமிழ்த் திருவிழா.'),
    story: B('When Brahma and Vishnu argued who was supreme, Shiva rose as a pillar of fire. Neither could find its end, and Brahma’s false claim was exposed. At their prayer, the fire settled as the Arunachala hill, and Shiva promised to appear as a flame atop it every year on Karthigai star — the Maha Deepam.',
      'யார் பெரியவர் என்று பிரம்மனும் விஷ்ணுவும் வாதிட்டபோது சிவன் அக்னித் தூணாக எழுந்தார். இருவரும் முடிவு காணவில்லை; பிரம்மனின் பொய் வெளிப்பட்டது. அவர்கள் வேண்டுதலால் அக்னி அருணாசல மலையாக அடங்கியது; ஆண்டுதோறும் கார்த்திகை நட்சத்திரத்தில் மலை மேல் ஜோதியாகத் தோன்றுவதாகச் சிவன் வாக்களித்தார் — அதுவே மகா தீபம்.'),
    how: B(['Clean the house; draw kolam; in the evening light rows of agal (clay) lamps at the entrance, windows and steps — 27 or more if you wish.', 'Pray to Shiva and Murugan; watch the Maha Deepam (in person or live).', 'Keep lamps away from curtains and children’s reach.'],
      ['வீட்டைச் சுத்தம் செய்து கோலமிடுங்கள்; மாலையில் வாசல், சன்னல், படிகளில் அகல் விளக்கு வரிசை — விரும்பினால் 27 அல்லது அதிகம்.', 'சிவன், முருகனை வழிபடுங்கள்; மகா தீபம் தரிசனம் (நேரில் அல்லது நேரலை).', 'விளக்குகளைத் திரைச்சீலை, குழந்தைகள் கைக்கு எட்டாமல் வையுங்கள்.']),
    offer: B('Pori urundai (puffed-rice balls), appam, adai, vella sheedai, nei appam.', 'பொரி உருண்டை, அப்பம், அடை, வெல்லச் சீடை, நெய் அப்பம்.'),
    temples: ['tiruvannamalai', 'palani', 'thiruparankundram'],
    regional: B('Kerala celebrates Thrikarthika; Andhra Pradesh Karthika Pournami with lamps floated on water.', 'கேரளத்தில் திருக்கார்த்திகை; ஆந்திராவில் கார்த்திக பௌர்ணமி — நீரில் விளக்கு மிதக்கவிடுதல்.'),
    see: ['karthigai', 'girivalam'], sources: SRC,
  },
  {
    id: 'margazhi', kind: 'festival',
    names: B('Margazhi month (Thiruppavai, Thiruvempavai)', 'மார்கழி மாதம் (திருப்பாவை, திருவெம்பாவை)'),
    aliases: ['margazhi', 'margali', 'marghazhi', 'margazhi month', 'margazhi masam', 'dhanur masam', 'thiruppavai', 'thirupavai', 'thiruvempavai', 'margazhi kolam', 'மார்கழி', 'மார்கழி மாதம்', 'திருப்பாவை', 'திருவெம்பாவை', 'தனுர் மாதம்'],
    deity: B('Lord Krishna/Perumal (Thiruppavai); Lord Shiva (Thiruvempavai)', 'கண்ணன்/பெருமாள் (திருப்பாவை); சிவன் (திருவெம்பாவை)'),
    rule: { solarMonth: 8 },
    ruleText: B('the Tamil month when the Sun is in Dhanus (Sagittarius), mid-December to mid-January.', 'சூரியன் தனுசு ராசியில் இருக்கும் மாதம், டிசம்பர் நடுவிலிருந்து ஜனவரி நடு வரை.'),
    line: B('Holy month of early-morning prayer — kolam, bhajans, Thiruppavai and Thiruvempavai.', 'அதிகாலை வழிபாட்டின் புனித மாதம் — கோலம், பஜனை, திருப்பாவை, திருவெம்பாவை.'),
    why: B('In the Gita Krishna says, "Among months I am Margashirsha." Margazhi is the dawn of the devas’ day, so the hours before sunrise (Brahma muhurtham) are given to prayer. Andal sang the 30 pasurams of Thiruppavai and Manikkavasagar the 20 of Thiruvempavai — one for each morning. Homes wake early to draw big kolams and the streets fill with bhajans.',
      '"மாதங்களில் நான் மார்கழி" என்று கீதையில் கண்ணன் சொல்கிறார். மார்கழி தேவர்களின் விடியற்காலம் என்பதால் சூரிய உதயத்துக்கு முந்தைய பிரம்ம முகூர்த்தம் வழிபாட்டுக்கு உரியது. ஆண்டாள் 30 திருப்பாவைப் பாசுரங்களையும் மாணிக்கவாசகர் 20 திருவெம்பாவைப் பாடல்களையும் பாடினர் — ஒவ்வொரு காலைக்கும் ஒன்று. வீடுகள் அதிகாலையில் எழுந்து பெரிய கோலமிட, வீதிகளில் பஜனை முழங்கும்.'),
    how: B(['Wake early, bathe, draw a kolam (often with a pumpkin flower on cow-dung).', 'Recite the day’s Thiruppavai pasuram (“Margazhi thingal madhi niraindha nannalal…”) or Thiruvempavai.', 'Join temple bhajans; offer ven pongal at dawn.', 'Families usually avoid weddings in Margazhi, keeping it for worship.'],
      ['அதிகாலை எழுந்து நீராடி கோலமிடுதல் (பசுஞ்சாணத்தில் பூசணிப் பூவுடன்).', 'அன்றைய திருப்பாவைப் பாசுரம் ("மார்கழித் திங்கள் மதிநிறைந்த நன்னாளால்…") அல்லது திருவெம்பாவை.', 'கோவில் பஜனையில் கலந்துகொள்ளுதல்; விடியலில் வெண் பொங்கல் படைத்தல்.', 'மார்கழியை வழிபாட்டுக்காக வைத்து, திருமணங்களைக் குடும்பங்கள் பொதுவாகத் தவிர்க்கின்றன.']),
    offer: B('Ven pongal, sakkarai pongal, sundal; akkaravadisal on Koodaravalli (Margazhi 27).', 'வெண் பொங்கல், சர்க்கரைப் பொங்கல், சுண்டல்; கூடாரவல்லி (மார்கழி 27) அன்று அக்காரவடிசல்.'),
    temples: ['srivilliputhur', 'srirangam', 'chidambaram', 'triplicane'],
    regional: B('Chennai’s December music season (Margazhi Utsavam) grew around this month.', 'சென்னையின் டிசம்பர் இசைப் பருவம் (மார்கழி உற்சவம்) இம்மாதத்தை ஒட்டி வளர்ந்தது.'),
    see: ['vaikunta-ekadasi', 'arudra-darisanam', 'hanuman-jayanthi'], sources: SRC,
  },
  {
    id: 'vaikunta-ekadasi', kind: 'festival', fast: true, mantra: 'narayana',
    names: B('Vaikunta Ekadasi', 'வைகுண்ட ஏகாதசி'),
    aliases: ['vaikunta ekadasi', 'vaikuntha ekadashi', 'vaikunda ekadasi', 'vaigunda ekadasi', 'vaikunta ekathasi', 'paramapada vasal', 'sorga vasal', 'sorgavasal', 'mukkoti ekadasi', 'வைகுண்ட ஏகாதசி', 'சொர்க்க வாசல்', 'சொர்க்கவாசல்', 'பரமபத வாசல்'],
    deity: B('Lord Vishnu (Ranganatha, Perumal)', 'திருமால் (ரங்கநாதர், பெருமாள்)'),
    rule: { tithi: 10, at: 'sunrise', solar: [8] },
    ruleText: B('the Shukla Ekadasi in the Tamil month of Margazhi (prevailing at sunrise).', 'மார்கழி மாத வளர்பிறை ஏகாதசி (சூரிய உதயத்தில்).'),
    line: B('The holiest Ekadasi — Paramapada Vasal (Sorgavasal) opens in Perumal temples.', 'மிகப் புனிதமான ஏகாதசி — பெருமாள் கோவில்களில் பரமபத வாசல் (சொர்க்கவாசல்) திறப்பு.'),
    why: B('On Vaikunta Ekadasi the gates of Vaikuntam are believed to open. Perumal temples open the northern Paramapada Vasal at dawn and devotees pass through it, praying for moksha. Fasting this one Ekadasi is said to equal all the Ekadasis of the year.',
      'வைகுண்ட ஏகாதசியில் வைகுண்ட வாசல் திறக்கும் என்பது நம்பிக்கை. பெருமாள் கோவில்களில் விடியற்காலையில் வடக்கு பரமபத வாசல் திறக்கப்பட, மோட்சம் வேண்டிப் பக்தர்கள் அதன் வழியே செல்வர். இந்த ஒரு ஏகாதசி விரதம் ஆண்டின் எல்லா ஏகாதசிகளுக்கும் சமம் என்று சொல்லப்படுகிறது.'),
    story: B('The Vishnu Purana tradition tells of two asuras, Madhu and Kaitabha, who after being defeated asked Vishnu to let anyone who sees Him passing through the northern gate on this day reach Vaikuntam — and Vishnu granted it. At Srirangam the festival runs 21 days (Pagal Pathu and Ra Pathu) with the Nammazhvar moksham enactment.',
      'தோல்வியுற்ற மது, கைடபர் என்ற அசுரர்கள், இந்நாளில் வடக்கு வாசல் வழியே எழுந்தருளும் தம்மைக் காண்பவருக்கு வைகுண்டம் அருள வேண்டும் என்று திருமாலிடம் வேண்ட, அவர் அருளினார் என்பது மரபு. ஸ்ரீரங்கத்தில் பகல் பத்து, ராப் பத்து என 21 நாள் விழா; நம்மாழ்வார் மோட்ச நிகழ்வுடன் நிறைவு.'),
    how: B(['Previous day one simple meal; on Ekadasi fast as health allows (fruits/milk are fine), avoiding rice.', 'Stay awake at night with Vishnu Sahasranamam or Divya Prabandham if comfortable; go through the Paramapada Vasal at dawn.', 'Dwadasi morning: break the fast with agathi keerai, sundakkai and nellikkai.'],
      ['முந்தைய நாள் ஒருவேளை எளிய உணவு; ஏகாதசி அன்று உடல்நிலைக்கு ஏற்ப விரதம் (பழம்/பால் பரவாயில்லை), அரிசி தவிர்ப்பு.', 'வசதியாக இருந்தால் இரவு விஷ்ணு சகஸ்ரநாமம், திவ்ய பிரபந்தத்துடன் விழித்திருத்தல்; விடியலில் பரமபத வாசல் தரிசனம்.', 'துவாதசி காலை அகத்திக் கீரை, சுண்டைக்காய், நெல்லிக்காயுடன் விரதம் முடித்தல்.']),
    offer: B('Tulasi, fruits; for parana — agathi keerai, sundakkai, nellikkai.', 'துளசி, பழங்கள்; பாரணைக்கு அகத்திக் கீரை, சுண்டைக்காய், நெல்லிக்காய்.'),
    temples: ['srirangam', 'tirumala', 'triplicane', 'kanchi_varadaraja', 'srivilliputhur'],
    regional: B('North India observes the same day as Mokshada Ekadasi / Gita Jayanthi; dates can differ when the Ekadasi falls just outside Margazhi.', 'வட இந்தியாவில் அதே நாள் மோக்ஷதா ஏகாதசி / கீதா ஜெயந்தி; ஏகாதசி மார்கழிக்குச் சற்று வெளியே வந்தால் தேதி வேறுபடலாம்.'),
    see: ['ekadasi', 'margazhi', 'gita-jayanthi'], sources: SRC,
  },
  {
    id: 'gita-jayanthi', kind: 'festival', listed: false, mantra: 'narayana',
    names: B('Gita Jayanthi', 'கீதா ஜெயந்தி'),
    aliases: ['gita jayanthi', 'geetha jayanthi', 'gita jayanti', 'bhagavad gita day', 'கீதா ஜெயந்தி', 'கீதை ஜெயந்தி'],
    deity: B('Lord Krishna', 'ஸ்ரீ கிருஷ்ணர்'),
    rule: { tithi: 10, at: 'sunrise', lunar: [8] },
    ruleText: B('Margashirsha Shukla Ekadasi (Mokshada Ekadasi).', 'மார்கசீர்ஷ வளர்பிறை ஏகாதசி (மோக்ஷதா ஏகாதசி).'),
    line: B('The day Krishna taught the Bhagavad Gita to Arjuna at Kurukshetra.', 'குருக்ஷேத்திரத்தில் அர்ஜுனனுக்குக் கண்ணன் கீதை உபதேசித்த நாள்.'),
    why: B('Tradition holds the Gita was spoken on this Ekadasi. Reading even one chapter — or the 12th (Bhakti Yoga) — is a simple way to mark the day.', 'இந்த ஏகாதசியில் கீதை உபதேசிக்கப்பட்டது என்பது மரபு. ஒரு அத்தியாயம் — அல்லது 12-ஆம் (பக்தி யோகம்) — படிப்பது எளிய வழிபாடு.'),
    how: B(['Read or listen to a chapter of the Gita; reflect on one verse.'], ['கீதையின் ஓர் அத்தியாயம் படியுங்கள் அல்லது கேளுங்கள்; ஒரு சுலோகத்தைச் சிந்தியுங்கள்.']), sources: SRC,
  },
  {
    id: 'arudra-darisanam', kind: 'festival', fast: true, mantra: 'shiva',
    names: B('Arudra Darisanam (Thiruvathirai)', 'ஆருத்ரா தரிசனம் (திருவாதிரை)'),
    aliases: ['arudra darisanam', 'arudra darshan', 'arudra', 'aarudhra', 'thiruvathirai', 'thiruvadhirai', 'margazhi thiruvathirai', 'thiruvathirai kali', 'ஆருத்ரா தரிசனம்', 'ஆருத்ரா', 'திருவாதிரை', 'மார்கழி திருவாதிரை', 'திருவாதிரைக் களி'],
    deity: B('Lord Nataraja', 'நடராஜர்'),
    rule: { star: 5, solar: [8], twice: 'pournami' },
    ruleText: B('Thiruvathirai (Ardra) star at sunrise in Margazhi, usually around the full moon.', 'மார்கழியில் சூரிய உதயத்தில் திருவாதிரை நட்சத்திரம் — பெரும்பாலும் பௌர்ணமி அருகே.'),
    line: B('Darshan of Nataraja’s cosmic dance; Thiruvathirai kali and seven-vegetable kootu.', 'நடராஜரின் ஆனந்தத் தாண்டவ தரிசனம்; திருவாதிரைக் களி, ஏழுகறிக் கூட்டு.'),
    why: B('Thiruvathirai is Shiva’s star. In Margazhi, Nataraja at Chidambaram receives the great abhishekam and comes out to give darshan of the Ananda Thandavam — the dance of creation, preservation, dissolution, concealment and grace. Seeing it is believed to remove sorrow.',
      'திருவாதிரை சிவனின் நட்சத்திரம். மார்கழித் திருவாதிரையில் சிதம்பர நடராஜருக்கு மகா அபிஷேகம் நடந்து, படைத்தல், காத்தல், அழித்தல், மறைத்தல், அருளல் என்ற ஐந்தொழில் நடனமான ஆனந்தத் தாண்டவ தரிசனம் தருவார். அதைக் காண்பது துயர் நீக்கும் என்பது நம்பிக்கை.'),
    story: B('Sendanar, a poor firewood seller and Shiva devotee at Chidambaram, could offer only a simple kali (rice-jaggery pudding) to a guest who was Shiva in disguise. Next morning the temple priests found kali scattered in the sanctum — the Lord had accepted it. Since then Thiruvathirai kali is the special offering.',
      'சிதம்பரத்தில் விறகு விற்ற ஏழைச் சிவபக்தர் சேந்தனார், விருந்தினராக வந்த சிவனுக்கு எளிய களியை மட்டுமே படைக்க முடிந்தது. மறுநாள் காலை கருவறையில் களி சிதறிக் கிடந்தது — இறைவன் ஏற்றுக்கொண்டார். அன்றிலிருந்து திருவாதிரைக் களி சிறப்பு நைவேத்தியம்.'),
    how: B(['Wake early; offer Thiruvathirai kali and ezhukari kootu (seven vegetables) to Nataraja.', 'Women in many homes keep a fast for family welfare; visit a Shiva temple for the Arudra darshan; sing Thiruvempavai.'], ['அதிகாலை எழுந்து நடராஜருக்குத் திருவாதிரைக் களி, ஏழுகறிக் கூட்டு படைத்தல்.', 'பல வீடுகளில் பெண்கள் குடும்ப நலனுக்கு விரதம்; சிவன் கோவிலில் ஆருத்ரா தரிசனம்; திருவெம்பாவை பாடுதல்.']),
    offer: B('Thiruvathirai kali, ezhukari kootu.', 'திருவாதிரைக் களி, ஏழுகறிக் கூட்டு.'),
    temples: ['chidambaram', 'madurai_meenakshi', 'thiruvalangadu', 'mylapore'], see: ['aani-thirumanjanam', 'margazhi'], sources: SRC,
  },
  {
    id: 'hanuman-jayanthi', kind: 'festival', mantra: 'rama',
    names: B('Hanuman Jayanthi', 'அனுமன் ஜெயந்தி'),
    aliases: ['hanuman jayanthi', 'hanuman jayanti', 'anjaneya jayanthi', 'anjaneyar jayanthi', 'hanumath jayanthi', 'அனுமன் ஜெயந்தி', 'ஆஞ்சநேயர் ஜெயந்தி', 'அனுமத் ஜெயந்தி'],
    deity: B('Lord Hanuman (Anjaneyar)', 'ஆஞ்சநேயர் (அனுமன்)'),
    rule: { tithi: 29, at: 'sunrise', solar: [8] },
    ruleText: B('Tamil tradition: Amavasai in Margazhi (with Moolam star). North India celebrates on Chaitra Pournami instead.', 'தமிழ் மரபு: மார்கழி அமாவாசை (மூல நட்சத்திரத்துடன்). வட இந்தியாவில் சைத்ர பௌர்ணமியில்.'),
    line: B('Birthday of Anjaneyar — vadai malai, butter and Rama nama.', 'ஆஞ்சநேயர் அவதார நாள் — வடை மாலை, வெண்ணெய், ராம நாமம்.'),
    why: B('Hanuman, son of Anjana and Vayu, is honoured for strength with humility and complete devotion to Rama. Praying to Him is believed to give courage, good health and freedom from fear.', 'அஞ்சனை, வாயுவின் மகனான அனுமன், பணிவுடன் கூடிய வலிமைக்கும் ராமர் மீதான முழுமையான பக்திக்கும் போற்றப்படுகிறார். அவரை வழிபடுவது தைரியம், ஆரோக்கியம், பயமின்மை தரும் என்பது நம்பிக்கை.'),
    how: B(['Visit an Anjaneyar temple; offer vadai malai, vettrilai malai or butter; chant "Sri Rama Jaya Rama Jaya Jaya Rama" or Hanuman Chalisa; read Sundara Kandam.'], ['ஆஞ்சநேயர் கோவில் தரிசனம்; வடை மாலை, வெற்றிலை மாலை அல்லது வெண்ணெய் சாற்றுதல்; "ஸ்ரீ ராம ஜெய ராம ஜெய ஜெய ராம" அல்லது ஹனுமான் சாலிசா; சுந்தர காண்டம் படித்தல்.']),
    offer: B('Vadai malai, butter, betel-leaf garland, sweet pongal.', 'வடை மாலை, வெண்ணெய், வெற்றிலை மாலை, சர்க்கரைப் பொங்கல்.'),
    temples: ['suchindram'],
    regional: B('Namakkal, Suchindram and Nanganallur Anjaneyar temples celebrate grandly; Andhra observes it in Vaisakha.', 'நாமக்கல், சுசீந்திரம், நங்கநல்லூர் ஆஞ்சநேயர் கோவில்களில் பெருவிழா; ஆந்திராவில் வைகாசத்தில்.'),
    sources: SRC,
  },
];
