// Monthly observances (every lunar fortnight / month). Rule fields are read by shared/spiritual-kb.js.
import { B, SRC } from './common.js';

export const MONTHLY = [
  {
    id: 'ekadasi', kind: 'monthly', fast: true, mantra: 'narayana',
    names: B('Ekadasi', 'ஏகாதசி'),
    aliases: ['ekadasi', 'ekadashi', 'ekathasi', 'egadasi', 'ekadesi', 'ekadasi viratham', 'ஏகாதசி விரதம்', 'ஏகாதசி', 'ekadasi fasting'],
    deity: B('Lord Vishnu (Perumal)', 'திருமால் (பெருமாள்)'),
    rule: { tithi: [10, 25], at: 'sunrise' },
    ruleText: B('the 11th tithi of each fortnight (Shukla and Krishna Ekadasi) prevailing at sunrise — twice a month.', 'ஒவ்வொரு பட்சத்திலும் (வளர்பிறை, தேய்பிறை) சூரிய உதயத்தில் இருக்கும் 11-ஆம் திதி — மாதம் இருமுறை.'),
    line: B('Fasting day for Lord Vishnu, twice a month — for a calm mind and self-discipline.', 'மாதம் இருமுறை வரும் திருமாலுக்கான விரத நாள் — மன அமைதி, கட்டுப்பாட்டுக்காக.'),
    why: B('Ekadasi is believed to be the day most dear to Lord Vishnu. Giving the stomach rest and the mind to prayer on this day is said to purify body and thought. Tradition says sincere Ekadasi observance brings peace and moksha-oriented merit; there are 24 named Ekadasis in a year, each with its own story.',
      'ஏகாதசி திருமாலுக்கு மிகவும் உகந்த நாள் என்பது நம்பிக்கை. இந்நாளில் வயிற்றுக்கு ஓய்வும் மனத்துக்குப் பிரார்த்தனையும் கொடுப்பது உடலையும் சிந்தனையையும் தூய்மைப்படுத்தும் என்று சொல்லப்படுகிறது. ஆண்டில் 24 ஏகாதசிகள் உண்டு; ஒவ்வொன்றுக்கும் தனிப் பெயரும் கதையும் உண்டு.'),
    story: B('The Padma Purana tells that a demon named Mura troubled the devas. When Vishnu rested in a cave at Badarikashrama, a radiant goddess emerged from His body and defeated Mura. Pleased, Vishnu named her Ekadasi, as she appeared on the 11th day, and blessed that whoever fasts and prays on her day would be freed from sins. This first appearance is remembered as Utpanna Ekadasi.',
      'பத்ம புராணப்படி, முரன் என்ற அசுரன் தேவர்களைத் துன்புறுத்தினான். பதரிகாசிரமக் குகையில் திருமால் ஓய்வெடுத்தபோது, அவர் உடலிலிருந்து ஒளிமிக்க ஒரு தேவி தோன்றி முரனை வென்றாள். மகிழ்ந்த திருமால், 11-ஆம் நாளில் தோன்றியதால் அவளுக்கு "ஏகாதசி" என்று பெயரிட்டு, அந்நாளில் விரதமிருந்து வழிபடுவோரின் பாவங்கள் நீங்கும் என்று அருளினார். இதுவே உத்பன்ன ஏகாதசி.'),
    how: B(['Previous day (Dasami): one simple meal at noon, no night meal if comfortable.',
      'Ekadasi: avoid rice and grains; take fruit, milk or water as your health allows, or simply eat lightly.',
      'Light a lamp, offer tulasi to Perumal and chant "Om Namo Narayanaya" or Vishnu Sahasranamam.',
      'Visit a Perumal temple if you can; keep the day calm — less TV, more kindness.',
      'Dwadasi (next morning): break the fast early after prayer, with rice, sundakkai, agathi keerai and nellikkai as is the custom.'],
    ['முந்தைய நாள் (தசமி): மதியம் ஒரு வேளை எளிய உணவு; முடிந்தால் இரவு உணவு தவிர்க்கலாம்.',
      'ஏகாதசி அன்று அரிசி, தானியம் தவிர்த்து — உடல்நிலைக்கு ஏற்ப பழம், பால் அல்லது தண்ணீர்; அல்லது எளிய உணவு.',
      'விளக்கேற்றி, பெருமாளுக்குத் துளசி சாற்றி, "ஓம் நமோ நாராயணாய" அல்லது விஷ்ணு சகஸ்ரநாமம் சொல்லுங்கள்.',
      'முடிந்தால் பெருமாள் கோவிலுக்குச் செல்லுங்கள்; அன்று மனம் அமைதியாக — குறைவான தொலைக்காட்சி, அதிக அன்பு.',
      'துவாதசி (மறுநாள் காலை): பிரார்த்தனைக்குப் பின் சீக்கிரம் விரதம் முடியுங்கள் — வழக்கப்படி அகத்திக் கீரை, சுண்டைக்காய், நெல்லிக்காயுடன் உணவு.']),
    offer: B('Tulasi leaves, fruits, milk, panchamritam; for Dwadasi parana — agathi keerai, sundakkai, nellikkai.', 'துளசி, பழங்கள், பால், பஞ்சாமிர்தம்; துவாதசி பாரணைக்கு அகத்திக் கீரை, சுண்டைக்காய், நெல்லிக்காய்.'),
    temples: ['srirangam', 'tirumala', 'triplicane', 'kanchi_varadaraja'],
    regional: B('Tamil Smarta and Vaishnava calendars sometimes keep Ekadasi a day apart when the tithi touches Dasami at dawn; follow your family temple’s calendar. North Indian calendars use the same tithi.', 'தசமி விடியற்காலையைத் தொட்டால் ஸ்மார்த்த, வைணவப் பஞ்சாங்கங்களில் ஏகாதசி ஒரு நாள் மாறலாம்; உங்கள் குடும்பக் கோவில் பஞ்சாங்கத்தைப் பின்பற்றுங்கள்.'),
    see: ['vaikunta-ekadasi', 'ekadasi-nirjala'], sources: SRC,
  },
  {
    id: 'pradosham', kind: 'monthly', fast: true, mantra: 'shiva',
    names: B('Pradosham', 'பிரதோஷம்'),
    aliases: ['pradosham', 'pradosam', 'pirathosam', 'prathosam', 'pradosh', 'pradosha', 'pradosha vratham', 'பிரதோஷம்', 'பிரதோஷ', 'pradosham viratham'],
    deity: B('Lord Shiva and Nandi', 'சிவபெருமான், நந்தியெம்பெருமான்'),
    rule: { tithi: [12, 27], at: 'sunset' },
    ruleText: B('Trayodasi (13th tithi) prevailing at sunset, in both fortnights; the pradosha kalam is about 4:30–6 PM.', 'சூரிய அஸ்தமன நேரத்தில் இருக்கும் திரயோதசி (13-ஆம் திதி), இரு பட்சத்திலும்; பிரதோஷ காலம் மாலை சுமார் 4:30–6 மணி.'),
    line: B('Evening worship of Shiva and Nandi at twilight, twice a month.', 'மாதம் இருமுறை, அந்தி நேரத்தில் சிவன், நந்தி வழிபாடு.'),
    why: B('Tradition says that during the twilight of Trayodasi, Shiva danced between the horns of Nandi after saving the world from the Halahala poison. Worship at this hour is believed to remove sins and bring peace; a Pradosham on Saturday (Sani Pradosham) or Monday (Soma Pradosham) is held especially sacred.',
      'ஆலகால விஷத்திலிருந்து உலகைக் காத்த பின், திரயோதசி அந்தி நேரத்தில் சிவபெருமான் நந்தியின் கொம்புகளுக்கு நடுவே ஆனந்த நடனம் ஆடினார் என்பது மரபு. இந்த நேர வழிபாடு பாவங்களை நீக்கி அமைதி தரும் என்று நம்பப்படுகிறது; சனிக்கிழமை (சனிப் பிரதோஷம்), திங்கள் (சோமப் பிரதோஷம்) வரும் பிரதோஷம் தனிச் சிறப்பு.'),
    story: B('When the devas and asuras churned the ocean of milk for nectar, the deadly Halahala poison rose first. Everyone fled to Shiva, who swallowed it; Parvati held His throat so it stayed there, making Him Neelakantha, the blue-throated one. The devas, ashamed of forgetting to thank Him, prayed on Trayodasi evening, and Shiva blessed them with His dance on Nandi. Hence the pradosha abhishekam is done first to Nandi.',
      'தேவர்களும் அசுரர்களும் அமுதத்துக்காகப் பாற்கடலைக் கடைந்தபோது முதலில் கொடிய ஆலகால விஷம் எழுந்தது. அனைவரும் சிவனிடம் ஓடினர்; அவர் அதை விழுங்க, பார்வதி தேவி அவர் கழுத்தைப் பிடித்ததால் விஷம் அங்கேயே நின்று அவர் நீலகண்டர் ஆனார். நன்றி சொல்ல மறந்ததற்கு வருந்திய தேவர்கள் திரயோதசி மாலையில் வேண்ட, சிவன் நந்தியின் மேல் நடனமாடி அருளினார். அதனால் பிரதோஷ அபிஷேகம் முதலில் நந்திக்கு நடக்கிறது.'),
    how: B(['Fast lightly through the day if your health allows, or eat simply.', 'Go to a Shiva temple at 4:30–6 PM; watch the Nandi abhishekam and then Shiva’s.', 'Offer bilva (vilvam) leaves, and chant "Om Namah Shivaya".', 'Walk the special pradosha pradakshinam (somasutra pradakshinam) if the temple guides you.', 'Break the fast after the evening pooja.'],
      ['உடல்நிலை அனுமதித்தால் பகலில் லேசான விரதம், இல்லையெனில் எளிய உணவு.', 'மாலை 4:30–6 மணிக்குச் சிவன் கோவிலுக்குச் சென்று நந்தி அபிஷேகம், பின் சிவ அபிஷேகம் தரிசியுங்கள்.', 'வில்வ இலை சாற்றி "ஓம் நமசிவாய" சொல்லுங்கள்.', 'கோவிலில் சொல்லித் தரும் சோமசூத்திரப் பிரதட்சிணம் செய்யலாம்.', 'மாலைப் பூஜைக்குப் பின் விரதம் முடியுங்கள்.']),
    offer: B('Bilva leaves, milk, curd, honey, tender coconut for abhishekam; arugampul and raw rice-jaggery for Nandi.', 'அபிஷேகத்துக்குப் பால், தயிர், தேன், இளநீர்; வில்வம்; நந்திக்கு அருகம்புல், பச்சரிசி-வெல்லம்.'),
    temples: ['mylapore', 'thanjavur_big', 'tiruvannamalai', 'madurai_meenakshi'],
    regional: B('In North India it is called Pradosh Vrat and observed the same evening.', 'வட இந்தியாவில் "பிரதோஷ் விரத்" என்று அதே மாலையில் கடைப்பிடிக்கப்படுகிறது.'),
    see: ['sani-pradosham', 'maha-sivaratri'], sources: SRC,
  },
  {
    id: 'sani-pradosham', kind: 'monthly', fast: true, mantra: 'shiva', listed: false,
    names: B('Sani Pradosham', 'சனிப் பிரதோஷம்'),
    aliases: ['sani pradosham', 'shani pradosham', 'sani pradosam', 'சனி பிரதோஷம்', 'சனிப் பிரதோஷம்'],
    deity: B('Lord Shiva', 'சிவபெருமான்'),
    rule: { tithi: [12, 27], at: 'sunset', weekday: 6 },
    ruleText: B('a Pradosham (Trayodasi at sunset) that falls on a Saturday.', 'சனிக்கிழமை வரும் பிரதோஷம் (அஸ்தமனத்தில் திரயோதசி).'),
    line: B('Pradosham on a Saturday — held especially sacred.', 'சனிக்கிழமை வரும் பிரதோஷம் — தனிச் சிறப்பு.'),
    why: B('The Halahala episode is said to have happened on a Saturday Trayodasi, so a Sani Pradosham is believed to equal many ordinary Pradoshams in merit.', 'ஆலகால விஷ நிகழ்வு சனிக்கிழமை திரயோதசியில் நடந்ததாகச் சொல்லப்படுவதால், சனிப் பிரதோஷம் பல பிரதோஷங்களுக்குச் சமம் என்பது நம்பிக்கை.'),
    how: B(['Observe as for Pradosham; many also light a sesame-oil lamp.'], ['பிரதோஷம் போலவே கடைப்பிடியுங்கள்; பலர் நல்லெண்ணெய் விளக்கும் ஏற்றுவர்.']),
    temples: ['mylapore', 'thirunallar'], sources: SRC,
  },
  {
    id: 'soma-pradosham', kind: 'monthly', fast: true, mantra: 'shiva', listed: false,
    names: B('Soma Pradosham', 'சோமப் பிரதோஷம்'),
    aliases: ['soma pradosham', 'somavara pradosham', 'சோம பிரதோஷம்', 'சோமப் பிரதோஷம்'],
    deity: B('Lord Shiva', 'சிவபெருமான்'),
    rule: { tithi: [12, 27], at: 'sunset', weekday: 1 },
    ruleText: B('a Pradosham that falls on a Monday.', 'திங்கள்கிழமை வரும் பிரதோஷம்.'),
    line: B('Pradosham on a Monday, the Moon’s day dear to Shiva.', 'சிவனுக்கு உகந்த திங்களில் வரும் பிரதோஷம்.'),
    why: B('Monday belongs to Soma (the Moon), whom Shiva wears on His head; a Pradosham on Monday is considered doubly auspicious.', 'திங்கள் சந்திரனுக்கு உரியது; சந்திரனைத் தலையில் சூடியவர் சிவன் — அதனால் திங்கள் பிரதோஷம் இருமடங்கு சிறப்பு.'),
    how: B(['Observe as for Pradosham.'], ['பிரதோஷம் போலவே கடைப்பிடியுங்கள்.']), sources: SRC,
  },
  {
    id: 'sashti', kind: 'monthly', fast: true, mantra: 'murugan',
    names: B('Sashti Viratham', 'சஷ்டி விரதம்'),
    aliases: ['sashti', 'shasti', 'shashti', 'sasti', 'sashti viratham', 'shasti viratham', 'sashti vratham', 'சஷ்டி', 'சஷ்டி விரதம்', 'shashti vrat'],
    deity: B('Lord Murugan', 'முருகப் பெருமான்'),
    rule: { tithi: 5, at: 'sunrise' },
    ruleText: B('Shukla Sashti — the 6th tithi after Amavasai, prevailing at sunrise; once a month.', 'வளர்பிறை சஷ்டி — அமாவாசைக்குப் பின் 6-ஆம் திதி, சூரிய உதயத்தில்; மாதம் ஒருமுறை.'),
    line: B('Monthly fast for Lord Murugan on the 6th day of the waxing Moon.', 'வளர்பிறை ஆறாம் நாள், முருகனுக்கான மாத விரதம்.'),
    why: B('Sashti is the day Lord Murugan defeated Soorapadman, the ego-filled asura, at Tiruchendur. Fasting on Sashti is believed to win over inner enemies — anger, pride, fear — and families pray for children’s welfare and harmony. The saying "சட்டியில் இருந்தால் அகப்பையில் வரும்" is read as "observe Sashti and the blessing (of a child) comes to the womb (agappai)".',
      'தற்பெருமை மிக்க சூரபத்மனை முருகப் பெருமான் திருச்செந்தூரில் வென்ற நாள் சஷ்டி. சஷ்டி விரதம் கோபம், கர்வம், பயம் போன்ற உள் எதிரிகளை வெல்ல உதவும் என்பது நம்பிக்கை; குழந்தைகள் நலனுக்கும் குடும்ப ஒற்றுமைக்கும் வேண்டுவர். "சஷ்டியில் இருந்தால் அகப்பையில் வரும்" என்ற பழமொழி, "சஷ்டி விரதம் இருந்தால் கருப்பையில் (அகப்பை) குழந்தை வரும்" என்று விளக்கப்படுகிறது.'),
    story: B('Soorapadman, blessed with great boons, troubled the devas. Shiva created Murugan from six sparks of His third eye; the six babies were raised by the Karthigai maidens and joined by Parvati into one six-faced Shanmukha. With the Vel given by Parvati, Murugan fought Soorapadman for six days and on the sixth (Sashti) split him into a peacock and a rooster — the peacock became His mount and the rooster His flag.',
      'பெரும் வரங்கள் பெற்ற சூரபத்மன் தேவர்களைத் துன்புறுத்தினான். சிவனின் நெற்றிக்கண்ணிலிருந்து எழுந்த ஆறு தீப்பொறிகள் ஆறு குழந்தைகளாகி, கார்த்திகைப் பெண்களால் வளர்க்கப்பட்டு, பார்வதியால் ஒன்றாக அணைக்கப்பட்டு ஆறுமுகன் ஆனார். அன்னை தந்த வேலுடன் ஆறு நாள் போரிட்டு, ஆறாம் நாள் (சஷ்டி) சூரனை மயிலாகவும் சேவலாகவும் பிளந்தார் — மயில் வாகனமானது, சேவல் கொடியானது.'),
    how: B(['Fast till evening if healthy (fruit/milk is fine), or eat one simple meal.', 'Read or listen to Kanda Sashti Kavasam; chant "Om Saravanabhava".', 'Visit a Murugan temple; offer red flowers and a lamp.', 'Break the fast after the evening pooja.'],
      ['உடல்நலம் அனுமதித்தால் மாலை வரை விரதம் (பழம், பால் பரவாயில்லை), அல்லது ஒரு வேளை எளிய உணவு.', 'கந்த சஷ்டி கவசம் படியுங்கள் அல்லது கேளுங்கள்; "ஓம் சரவணபவ" சொல்லுங்கள்.', 'முருகன் கோவிலுக்குச் சென்று சிவப்பு மலர், விளக்கு சமர்ப்பியுங்கள்.', 'மாலைப் பூஜைக்குப் பின் விரதம் முடியுங்கள்.']),
    offer: B('Panchamritam, fruits, red flowers, sweet pongal; vel and peacock feather are traditional symbols.', 'பஞ்சாமிர்தம், பழங்கள், சிவப்பு மலர்கள், சர்க்கரைப் பொங்கல்.'),
    temples: ['tiruchendur', 'palani', 'swamimalai', 'thiruparankundram', 'thiruthani', 'pazhamudircholai'],
    regional: B('Tamil families keep the waxing (Shukla) Sashti; some also keep the waning one. The biggest is Kanda Sashti in Aippasi.', 'தமிழ்க் குடும்பங்கள் வளர்பிறை சஷ்டியைக் கடைப்பிடிக்கின்றனர்; சிலர் தேய்பிறைச் சஷ்டியும். பெரியது ஐப்பசி கந்த சஷ்டி.'),
    see: ['skanda-sashti'], sources: SRC,
  },
  {
    id: 'sankatahara', kind: 'monthly', fast: true, mantra: 'ganesha',
    names: B('Sankatahara Chathurthi', 'சங்கடஹர சதுர்த்தி'),
    aliases: ['sankatahara', 'sankatahara chathurthi', 'sankashti', 'sankashti chaturthi', 'sankatahara chaturthi', 'சங்கடஹர சதுர்த்தி', 'சங்கடஹர', 'சங்கட ஹர சதுர்த்தி'],
    deity: B('Lord Vinayagar (Ganesha)', 'விநாயகப் பெருமான்'),
    rule: { tithi: 18, at: 'moonrise' },
    ruleText: B('Krishna (waning) Chathurthi prevailing at moonrise, about 3 hours after sunset.', 'சந்திர உதய நேரத்தில் (அஸ்தமனத்துக்குச் சுமார் 3 மணி பின்) இருக்கும் தேய்பிறை சதுர்த்தி.'),
    line: B('Monthly Ganesha fast to remove obstacles; broken after seeing the Moon.', 'தடைகள் நீங்க மாதந்தோறும் விநாயகர் விரதம்; சந்திரனைப் பார்த்து முடிப்பது.'),
    why: B('“Sankata hara” means remover of troubles. Ganesha is believed to grant relief from difficulties to those who fast on the waning Chathurthi and pray after moonrise. A Sankatahara on Tuesday (Angaraka Chathurthi) is especially valued.',
      '"சங்கட ஹர" என்றால் துன்பம் நீக்குவது. தேய்பிறைச் சதுர்த்தியில் விரதமிருந்து சந்திர உதயத்துக்குப் பின் வழிபடுவோருக்கு விநாயகர் சிரமங்களிலிருந்து விடுதலை தருவார் என்பது நம்பிக்கை. செவ்வாய்க்கிழமை வரும் சங்கடஹர (அங்காரக சதுர்த்தி) மிகச் சிறப்பு.'),
    story: B('A popular account says the Moon laughed at Ganesha’s pot belly when He fell from His mouse; Ganesha said whoever saw the Moon on Chathurthi would face blame. When the devas pleaded, He softened it: on the waning Chathurthi, seeing the Moon after praying to Him would instead remove troubles.',
      'எலியிலிருந்து விழுந்த விநாயகரின் பெருவயிற்றைப் பார்த்துச் சந்திரன் சிரித்தான்; சதுர்த்தியில் சந்திரனைக் காண்போருக்குப் பழி வரும் என்றார் விநாயகர். தேவர்கள் வேண்ட, தேய்பிறைச் சதுர்த்தியில் தம்மை வழிபட்டுச் சந்திரனைக் காண்பது துன்பம் நீக்கும் என்று அருளினார் என்பது பரவலான கதை.'),
    how: B(['Fast through the day if healthy, or eat lightly.', 'In the evening offer arugampul (durva grass) and modakam to Vinayagar; chant "Om Gam Ganapataye Namaha".', 'After moonrise, see the Moon, offer water (arghya) and then eat.'],
      ['உடல்நலம் அனுமதித்தால் பகல் முழுவதும் விரதம், இல்லையெனில் லேசான உணவு.', 'மாலையில் விநாயகருக்கு அருகம்புல், கொழுக்கட்டை சமர்ப்பித்து "ஓம் கம் கணபதயே நமஹ" சொல்லுங்கள்.', 'சந்திர உதயத்துக்குப் பின் சந்திரனைப் பார்த்து நீர் அர்க்கியம் விட்டு உணவு உண்ணுங்கள்.']),
    offer: B('Arugampul, modakam (kozhukattai), sundal, appam, fruits.', 'அருகம்புல், கொழுக்கட்டை, சுண்டல், அப்பம், பழங்கள்.'),
    temples: ['pillaiyarpatti', 'trichy_rockfort'], see: ['vinayagar-chathurthi'], sources: SRC,
  },
  {
    id: 'chathurthi', kind: 'monthly', mantra: 'ganesha',
    names: B('Sukla Chathurthi', 'வளர்பிறைச் சதுர்த்தி'),
    aliases: ['chathurthi', 'chaturthi', 'sathurthi', 'vinayaka chaturthi monthly', 'sukla chathurthi', 'சதுர்த்தி', 'வளர்பிறை சதுர்த்தி'],
    deity: B('Lord Vinayagar', 'விநாயகப் பெருமான்'),
    rule: { tithi: 3, at: 'midday' },
    ruleText: B('Shukla Chathurthi (4th day after Amavasai) prevailing at midday.', 'நண்பகலில் இருக்கும் வளர்பிறைச் சதுர்த்தி (அமாவாசைக்குப் பின் 4-ஆம் நாள்).'),
    line: B('Monthly Vinayagar day on the waxing 4th — the Moon is not viewed this night.', 'வளர்பிறை நான்காம் நாள் மாத விநாயகர் வழிபாடு — அன்றிரவு சந்திரனைப் பார்ப்பதில்லை.'),
    why: B('Each Shukla Chathurthi is a small Vinayagar Chathurthi. Worship at midday, when Ganesha is said to have appeared, is believed to clear obstacles for new work.', 'ஒவ்வொரு வளர்பிறைச் சதுர்த்தியும் ஒரு சிறு விநாயகர் சதுர்த்தி. விநாயகர் தோன்றியதாகச் சொல்லப்படும் நண்பகலில் வழிபடுவது புதிய செயல்களின் தடைகளை நீக்கும் என்பது நம்பிக்கை.'),
    how: B(['Offer arugampul and kozhukattai at midday; chant the Ganesha mantra.'], ['நண்பகலில் அருகம்புல், கொழுக்கட்டை சமர்ப்பித்து விநாயகர் மந்திரம் சொல்லுங்கள்.']),
    offer: B('Kozhukattai, arugampul, fruits.', 'கொழுக்கட்டை, அருகம்புல், பழங்கள்.'),
    see: ['vinayagar-chathurthi', 'sankatahara'], sources: SRC,
  },
  {
    id: 'karthigai', kind: 'monthly', fast: true, mantra: 'murugan',
    names: B('Karthigai Viratham', 'கார்த்திகை விரதம்'),
    aliases: ['karthigai viratham', 'krithigai', 'kiruthigai', 'karthikai viratham', 'karthigai natchathiram', 'krithigai viratham', 'கிருத்திகை', 'கார்த்திகை விரதம்', 'கிருத்திகை விரதம்', 'monthly karthigai'],
    deity: B('Lord Murugan', 'முருகப் பெருமான்'),
    rule: { star: 2 },
    ruleText: B('the day the Moon is in Karthigai (Krittika) star at sunrise — about once a month.', 'சூரிய உதயத்தில் சந்திரன் கார்த்திகை (கிருத்திகை) நட்சத்திரத்தில் இருக்கும் நாள் — ஏறக்குறைய மாதம் ஒருமுறை.'),
    line: B('Monthly Murugan day on Karthigai star — the star of the six mothers who raised Him.', 'முருகனை வளர்த்த கார்த்திகைப் பெண்களின் நட்சத்திரம் — மாதாந்திர முருகன் விரதம்.'),
    why: B('The six Karthigai maidens (the Pleiades) nursed the six infant forms of Murugan at Saravana Poigai. Murugan blessed that those who pray to Him on their star would be protected; Aadi, Thai and Karthigai month Krithigai are the biggest.',
      'சரவணப் பொய்கையில் ஆறு குழந்தை வடிவ முருகனைப் பாலூட்டி வளர்த்தவர்கள் ஆறு கார்த்திகைப் பெண்கள். அவர்கள் நட்சத்திரத்தில் தம்மை வழிபடுவோரைக் காப்பதாக முருகன் அருளினார்; ஆடி, தை, கார்த்திகை மாதக் கிருத்திகைகள் மிகப் பெரியவை.'),
    how: B(['Fast or eat simply till evening; visit a Murugan temple; chant "Om Saravanabhava"; light lamps at home in the evening.'], ['மாலை வரை விரதம் அல்லது எளிய உணவு; முருகன் கோவில் தரிசனம்; "ஓம் சரவணபவ"; மாலையில் வீட்டில் விளக்கேற்றுங்கள்.']),
    offer: B('Panchamritam, milk, fruits, red flowers.', 'பஞ்சாமிர்தம், பால், பழங்கள், சிவப்பு மலர்கள்.'),
    temples: ['thiruthani', 'palani', 'tiruchendur', 'vadapalani'], see: ['aadi-krithigai', 'karthigai-deepam'], sources: SRC,
  },
  {
    id: 'amavasai', kind: 'monthly', mantra: 'shiva',
    names: B('Amavasai', 'அமாவாசை'),
    aliases: ['amavasai', 'amavasya', 'amavasi', 'amavasaai', 'new moon', 'அமாவாசை', 'அமாவாசைத்'],
    deity: B('Ancestors (pitrus); Shiva, Amman', 'முன்னோர்கள் (பித்ருக்கள்); சிவன், அம்மன்'),
    rule: { tithi: 29, at: 'sunrise' },
    ruleText: B('the new-moon tithi prevailing at sunrise (if it touches no sunrise, the day it runs).', 'சூரிய உதயத்தில் இருக்கும் அமாவாசைத் திதி (உதயத்தைத் தொடாவிட்டால், அது நடக்கும் நாள்).'),
    line: B('New-moon day to remember ancestors with tharpanam and charity.', 'தர்ப்பணம், தானம் மூலம் முன்னோர்களை நினைக்கும் அமாவாசை நாள்.'),
    why: B('On Amavasai the Sun and Moon are together; tradition holds that ancestors (pitrus) await our remembrance on this day. Offering tharpanam (sesame and water), feeding the needy and cows are believed to bring the ancestors’ blessings to the family. Many Amman temples hold special poojas.',
      'அமாவாசையில் சூரியனும் சந்திரனும் ஒன்றாக இருக்கின்றனர்; இந்நாளில் முன்னோர்கள் நம் நினைவுக்காகக் காத்திருப்பர் என்பது மரபு. எள்ளும் நீரும் கொண்டு தர்ப்பணம், ஏழைகளுக்கும் பசுவுக்கும் உணவளித்தல் குடும்பத்துக்கு முன்னோர் ஆசி தரும் என்பது நம்பிக்கை. பல அம்மன் கோவில்களில் சிறப்புப் பூஜை நடக்கும்.'),
    how: B(['Bathe early; those whose father has passed may give tharpanam with sesame and water (guided by a priest or elder).', 'Cook simple vegetarian food, keep a portion for crows, and feed someone in need.', 'Light a lamp in the evening.'],
      ['அதிகாலையில் நீராடுங்கள்; தந்தையை இழந்தவர்கள் புரோகிதர் அல்லது பெரியவர் வழிகாட்டலில் எள்-நீர் தர்ப்பணம் செய்யலாம்.', 'எளிய சைவ உணவு சமைத்து, காக்கைக்கு ஒரு பங்கு வைத்து, தேவையுள்ள ஒருவருக்கு உணவளியுங்கள்.', 'மாலையில் விளக்கேற்றுங்கள்.']),
    offer: B('Sesame (ellu), water, rice balls (pindam) for tharpanam; food for crows and cows; agathi keerai to cows.', 'தர்ப்பணத்துக்கு எள், நீர், பிண்டம்; காக்கைக்கும் பசுவுக்கும் உணவு; பசுவுக்கு அகத்திக் கீரை.'),
    temples: ['rameswaram', 'kanyakumari', 'mylapore'],
    regional: B('Aadi, Purattasi (Mahalaya) and Thai Amavasai are the three great ones in Tamil Nadu; in the North, Pitru Paksha Amavasya is the main one.', 'தமிழ்நாட்டில் ஆடி, புரட்டாசி (மகாளய), தை அமாவாசை மூன்றும் பெரியவை; வட இந்தியாவில் பித்ரு பட்ச அமாவாசை முக்கியம்.'),
    see: ['aadi-amavasai', 'thai-amavasai', 'mahalaya-amavasai'], sources: SRC,
  },
  {
    id: 'pournami', kind: 'monthly', mantra: 'ambal',
    names: B('Pournami', 'பௌர்ணமி'),
    aliases: ['pournami', 'pournamy', 'purnima', 'poornima', 'pournami viratham', 'full moon', 'பௌர்ணமி', 'பவுர்ணமி', 'பூரணை', 'முழு நிலவு'],
    deity: B('Ambal; Shiva at Tiruvannamalai; Sathyanarayana', 'அம்பாள்; திருவண்ணாமலை சிவன்; சத்யநாராயணர்'),
    rule: { tithi: 14, at: 'sunrise' },
    ruleText: B('the full-moon tithi prevailing at sunrise.', 'சூரிய உதயத்தில் இருக்கும் பௌர்ணமித் திதி.'),
    line: B('Full-moon day for Ambal pooja, Sathyanarayana pooja and Girivalam.', 'அம்பாள் பூஜை, சத்யநாராயண பூஜை, கிரிவலத்துக்கான முழு நிலவு நாள்.'),
    why: B('The full Moon is linked with a full, calm mind. Pournami is considered ideal for Devi worship, Sathyanarayana pooja and walking around the holy hill at Tiruvannamalai (Girivalam), which is believed to bring peace and grace.',
      'முழு நிலவு நிறைவான, அமைதியான மனத்தோடு தொடர்புடையது. தேவி வழிபாடு, சத்யநாராயண பூஜை, திருவண்ணாமலை கிரிவலம் ஆகியவற்றுக்குப் பௌர்ணமி மிக உகந்தது; அமைதியும் அருளும் தரும் என்பது நம்பிக்கை.'),
    how: B(['Light a lamp in the evening and offer kheer or sweet pongal to Ambal.', 'Read Lalitha Sahasranamam or Abhirami Anthathi.', 'Girivalam: walk the 14 km path at Tiruvannamalai barefoot, slowly, with water breaks — only if your health allows.'],
      ['மாலையில் விளக்கேற்றி அம்பாளுக்குப் பாயசம் அல்லது சர்க்கரைப் பொங்கல் படையுங்கள்.', 'லலிதா சகஸ்ரநாமம் அல்லது அபிராமி அந்தாதி படியுங்கள்.', 'கிரிவலம்: திருவண்ணாமலையில் 14 கி.மீ. பாதையை மெதுவாக, இடையிடையே தண்ணீர் அருந்தி — உடல்நலம் அனுமதித்தால் மட்டும்.']),
    offer: B('Payasam, sweet pongal, fruits, white flowers.', 'பாயசம், சர்க்கரைப் பொங்கல், பழங்கள், வெண்மலர்கள்.'),
    temples: ['tiruvannamalai', 'madurai_meenakshi', 'kanyakumari'], see: ['chithra-pournami', 'girivalam'], sources: SRC,
  },
  {
    id: 'girivalam', kind: 'monthly', listed: false, mantra: 'shiva',
    names: B('Pournami Girivalam', 'பௌர்ணமி கிரிவலம்'),
    aliases: ['girivalam', 'giri valam', 'kirivalam', 'கிரிவலம்', 'கிரி வலம்'],
    deity: B('Lord Arunachaleswarar', 'அருணாசலேஸ்வரர்'),
    rule: { tithi: 14, at: 'sunrise' },
    ruleText: B('every Pournami; the walk is usually done while the full-moon tithi runs, often at night.', 'ஒவ்வொரு பௌர்ணமியும்; பௌர்ணமித் திதி இருக்கும்போது, பெரும்பாலும் இரவில் வலம் வருவர்.'),
    line: B('Walking around the holy Arunachala hill on full-moon night.', 'பௌர்ணமி இரவில் அருணாசல மலையை வலம் வருதல்.'),
    why: B('Arunachala hill is itself worshipped as Shiva in the form of fire. Walking around it on full Moon, with prayer and silence, is believed to burn away karma and give peace of mind.', 'அருணாசல மலையே அக்னி வடிவச் சிவனாக வழிபடப்படுகிறது. பௌர்ணமியில் பிரார்த்தனையுடன், மௌனமாக வலம் வருவது வினைகளை எரித்து மன அமைதி தரும் என்பது நம்பிக்கை.'),
    how: B(['Walk clockwise, keeping the hill to your right; about 14 km, 4–5 hours.', 'Stop at the eight Ashta Lingams if you like; carry water, walk slowly, rest when needed.', 'Elderly people and those with knee or heart conditions can do a short walk or pray at the temple instead.'],
      ['மலையை வலப்பக்கம் வைத்து வலம் வாருங்கள்; சுமார் 14 கி.மீ., 4–5 மணி நேரம்.', 'விருப்பமிருந்தால் அஷ்ட லிங்கங்களில் வணங்கலாம்; தண்ணீர் எடுத்துச் செல்லுங்கள், மெதுவாக நடந்து தேவையானபோது ஓய்வெடுங்கள்.', 'முதியவர்கள், முழங்கால் அல்லது இதயப் பிரச்சினை உள்ளவர்கள் குறுகிய நடை அல்லது கோவிலில் வழிபாடு போதும்.']),
    temples: ['tiruvannamalai'], sources: SRC,
  },
  {
    id: 'masa-sivaratri', kind: 'monthly', fast: true, mantra: 'shiva',
    names: B('Masa Sivaratri', 'மாத சிவராத்திரி'),
    aliases: ['masa sivaratri', 'masa sivarathri', 'monthly sivaratri', 'masik shivratri', 'maasa sivarathiri', 'மாத சிவராத்திரி', 'மாதச் சிவராத்திரி'],
    deity: B('Lord Shiva', 'சிவபெருமான்'),
    rule: { tithi: 28, at: 'midnight' },
    ruleText: B('Krishna (waning) Chathurdasi prevailing at midnight — the night before Amavasai.', 'நள்ளிரவில் இருக்கும் தேய்பிறைச் சதுர்த்தசி — அமாவாசைக்கு முந்தைய இரவு.'),
    line: B('Monthly night of Shiva worship before the new moon.', 'அமாவாசைக்கு முந்தைய இரவு, மாதாந்திரச் சிவ வழிபாடு.'),
    why: B('Every waning Chathurdasi night is sacred to Shiva; the greatest of them, in Maasi, is Maha Sivaratri. Prayer through this night is believed to calm the mind and remove sins.', 'ஒவ்வொரு தேய்பிறைச் சதுர்த்தசி இரவும் சிவனுக்கு உகந்தது; அவற்றுள் மாசியில் வருவது மகா சிவராத்திரி. இந்த இரவின் பிரார்த்தனை மனத்தை அமைதிப்படுத்திப் பாவங்களை நீக்கும் என்பது நம்பிக்கை.'),
    how: B(['Fast lightly; worship Shiva at night with bilva; chant "Om Namah Shivaya".'], ['லேசான விரதம்; இரவில் வில்வத்துடன் சிவ வழிபாடு; "ஓம் நமசிவாய".']),
    offer: B('Bilva leaves, milk, fruits.', 'வில்வம், பால், பழங்கள்.'), see: ['maha-sivaratri'], sources: SRC,
  },
  {
    id: 'thiruvonam', kind: 'monthly', fast: true, mantra: 'narayana',
    names: B('Thiruvonam Viratham', 'திருவோண விரதம்'),
    aliases: ['thiruvonam', 'thiruonam', 'shravana viratham', 'thiruvonam viratham', 'திருவோணம்', 'திருவோண விரதம்'],
    deity: B('Lord Vishnu (Venkatesa, Oppiliappan)', 'திருமால் (வெங்கடேசர், ஒப்பிலியப்பன்)'),
    rule: { star: 21 },
    ruleText: B('the day the Moon is in Thiruvonam (Shravana) star at sunrise — monthly.', 'சூரிய உதயத்தில் சந்திரன் திருவோண நட்சத்திரத்தில் இருக்கும் நாள் — மாதந்தோறும்.'),
    line: B('Monthly Perumal fast on Thiruvonam, the star of Lord Venkatesa and Vamana.', 'வெங்கடேசர், வாமனர் நட்சத்திரமான திருவோணத்தில் பெருமாள் விரதம்.'),
    why: B('Thiruvonam is believed to be the star of Lord Srinivasa (Venkatesa) and of Vamana avatar. Observing it with a salt-free meal is a well-known custom at Oppiliappan Kovil, where the Lord accepts food without salt.', 'திருவோணம் ஸ்ரீநிவாசர் (வெங்கடேசர்), வாமன அவதார நட்சத்திரம் என்பது நம்பிக்கை. உப்பில்லா உணவுடன் விரதம் இருப்பது ஒப்பிலியப்பன் கோவிலில் பிரசித்தம் — அங்கு இறைவனுக்கு உப்பில்லா நைவேத்தியம்.'),
    how: B(['Take a simple salt-free meal once; visit a Perumal temple; chant "Om Namo Narayanaya".'], ['ஒரு வேளை உப்பில்லா எளிய உணவு; பெருமாள் கோவில் தரிசனம்; "ஓம் நமோ நாராயணாய".']),
    offer: B('Tulasi, curd rice without salt, fruits.', 'துளசி, உப்பில்லாத் தயிர் சாதம், பழங்கள்.'),
    temples: ['oppiliappan', 'tirumala'], see: ['onam'], sources: SRC,
  },
  {
    id: 'theipirai-ashtami', kind: 'monthly', mantra: 'shiva',
    names: B('Theipirai Ashtami (Kalabhairavar)', 'தேய்பிறை அஷ்டமி (காலபைரவர்)'),
    aliases: ['theipirai ashtami', 'teipirai ashtami', 'bhairavar ashtami', 'kalabhairava ashtami', 'kala bhairavar', 'தேய்பிறை அஷ்டமி', 'பைரவர் அஷ்டமி', 'காலபைரவர்'],
    deity: B('Lord Kalabhairavar', 'காலபைரவர்'),
    rule: { tithi: 22, at: 'sunrise' },
    ruleText: B('Krishna (waning) Ashtami prevailing at sunrise.', 'சூரிய உதயத்தில் இருக்கும் தேய்பிறை அஷ்டமி.'),
    line: B('Monthly worship of Kalabhairavar, guardian form of Shiva, on the waning 8th.', 'சிவனின் காவல் வடிவமான காலபைரவருக்குத் தேய்பிறை அஷ்டமி வழிபாடு.'),
    why: B('Kalabhairavar is the guardian deity (kshetrapalaka) of every Shiva temple and the lord of time. Praying to Him on the waning Ashtami is believed to remove fear and protect the family and travellers.', 'ஒவ்வொரு சிவன் கோவிலின் க்ஷேத்திர பாலகரும் காலத்தின் அதிபதியும் காலபைரவர். தேய்பிறை அஷ்டமியில் அவரை வழிபடுவது பயம் நீக்கிக் குடும்பத்தையும் பயணிகளையும் காக்கும் என்பது நம்பிக்கை.'),
    how: B(['Light a lamp with sesame oil or ghee before Bhairavar in the evening; offer a garland of vadai or cashews as is local custom; chant "Om Namah Shivaya".'], ['மாலையில் பைரவர் சன்னதியில் நல்லெண்ணெய் அல்லது நெய் விளக்கு; உள்ளூர் வழக்கப்படி வடை மாலை; "ஓம் நமசிவாய".']),
    offer: B('Sesame-oil lamp, vadai, honey, red flowers.', 'நல்லெண்ணெய் விளக்கு, வடை, தேன், சிவப்பு மலர்கள்.'), sources: SRC,
  },
  {
    id: 'month-start', kind: 'monthly',
    names: B('Tamil month begins (Sankranti)', 'தமிழ் மாதப் பிறப்பு'),
    aliases: ['month pirappu', 'matha pirappu', 'masa pirappu', 'sankranti', 'sankaranthi', 'tamil month start', 'மாதப் பிறப்பு', 'மாத பிறப்பு', 'சங்கராந்தி'],
    deity: B('Surya (the Sun)', 'சூரிய பகவான்'),
    rule: { solarDayAny: 1, exceptMonths: [0, 9] },
    ruleText: B('the day after the Sun enters a new sidereal rasi (if it enters after sunset, the next day).', 'சூரியன் புதிய ராசியில் நுழையும் நாள் (அஸ்தமனத்துக்குப் பின் நுழைந்தால் மறுநாள்).'),
    line: B('First day of a Tamil month — a day for tharpanam and Surya worship.', 'தமிழ் மாதத்தின் முதல் நாள் — தர்ப்பணம், சூரிய வழிபாட்டுக்கு உரியது.'),
    why: B('Each Tamil month begins when the Sun moves into the next rasi (Sankranti). It is a day of thanksgiving to the Sun and of tharpanam for ancestors; Thai 1 (Pongal) and Chithirai 1 (New Year) are the biggest.', 'சூரியன் அடுத்த ராசிக்கு நகரும் சங்கராந்தியில் ஒவ்வொரு தமிழ் மாதமும் தொடங்குகிறது. சூரியனுக்கு நன்றி செலுத்தவும் முன்னோருக்குத் தர்ப்பணம் செய்யவும் உரிய நாள்; தை 1 (பொங்கல்), சித்திரை 1 (புத்தாண்டு) மிகப் பெரியவை.'),
    how: B(['Offer water to the rising Sun and chant the Gayatri or Aditya Hridayam.'], ['உதய சூரியனுக்கு நீர் அர்க்கியம் விட்டு காயத்ரி அல்லது ஆதித்ய ஹ்ருதயம் சொல்லுங்கள்.']),
    mantra: 'gayatri', sources: SRC,
  },
];
