// Varga mapping variants, exact segment-boundary fixtures, Ashtakavarga (BPHS) checks.
// Expected values below were written by hand from the BPHS rules in shared/varga.js comments,
// not generated by vargaRasi itself.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { vargaRasi, VARGAS, VARGA_VARIANTS, ashtakavarga, AV_TABLES } from '../shared/varga.js';
import { birthChart } from '../shared/astro.js';

const at = (sign, deg) => sign * 30 + deg;
const EPS = 1e-9;

test('every offered varga has a unique named variant; D60 is not approved', () => {
  const ids = new Set();
  for (const v of VARGAS) {
    const m = VARGA_VARIANTS[v.n];
    assert.ok(m && m.id && m.rule, `D${v.n}`);
    assert.equal(typeof m.approved, 'boolean');
    ids.add(m.id);
  }
  assert.equal(ids.size, VARGAS.length);
  assert.equal(VARGA_VARIANTS[60].approved, false);
  assert.equal(VARGA_VARIANTS[60].note, 'awaiting astrologer review');
});

test('D2 Hora exact boundaries (15° goes to the second half)', () => {
  assert.equal(vargaRasi(at(0, 0), 2), 4); // Mesha 0° → Simha
  assert.equal(vargaRasi(at(0, 15 - EPS), 2), 4);
  assert.equal(vargaRasi(at(0, 15), 2), 3); // exactly 15° → Kataka
  assert.equal(vargaRasi(at(0, 30 - EPS), 2), 3);
  assert.equal(vargaRasi(at(1, 0), 2), 3); // Rishaba 0° → Kataka
  assert.equal(vargaRasi(at(1, 15), 2), 4); // Rishaba 15° → Simha
  assert.equal(vargaRasi(at(11, 15), 2), 4); // Meena (even) 15° → Simha
  assert.equal(vargaRasi(360, 2), 4); // 360° ≡ Mesha 0°
});

test('D30 Trimsamsa exact boundaries (odd and even signs)', () => {
  // odd (Mesha): [0,5) Mesha, [5,10) Kumbha, [10,18) Dhanusu, [18,25) Mithuna, [25,30) Thula
  const odd = [[0, 0], [5 - EPS, 0], [5, 10], [10 - EPS, 10], [10, 8], [18 - EPS, 8], [18, 2], [25 - EPS, 2], [25, 6], [30 - EPS, 6]];
  for (const [d, want] of odd) assert.equal(vargaRasi(at(4, d), 30), want, `Simha ${d}`);
  // even (Rishaba): [0,5) Rishaba, [5,12) Kanni, [12,20) Meena, [20,25) Makara, [25,30) Vrischika
  const even = [[0, 1], [5 - EPS, 1], [5, 5], [12 - EPS, 5], [12, 11], [20 - EPS, 11], [20, 9], [25 - EPS, 9], [25, 7], [30 - EPS, 7]];
  for (const [d, want] of even) assert.equal(vargaRasi(at(7, d), 30), want, `Vrischika ${d}`);
});

test('D60 exact boundaries (30′ parts from the sign itself)', () => {
  assert.equal(vargaRasi(at(0, 0), 60), 0);
  assert.equal(vargaRasi(at(0, 0.5 - EPS), 60), 0);
  assert.equal(vargaRasi(at(0, 0.5), 60), 1);
  assert.equal(vargaRasi(at(0, 6), 60), 0); // part 12 → back to Mesha
  assert.equal(vargaRasi(at(4, 29.5), 60), 3); // Simha part 59 → (59 + 4) mod 12 = Kataka
  assert.equal(vargaRasi(at(3, 29.5 - EPS), 60), (58 + 3) % 12); // Kataka part 58
  assert.equal(vargaRasi(at(11, 30 - EPS), 60), (59 + 11) % 12);
});

test('other equal-part vargas at boundaries', () => {
  assert.equal(vargaRasi(at(1, 10), 3), 5); // Rishaba 10° → 2nd drekkana → Kanni
  assert.equal(vargaRasi(at(1, 10 - EPS), 3), 1);
  assert.equal(vargaRasi(at(0, 7.5), 4), 3); // 2nd quarter → Kataka
  assert.equal(vargaRasi(at(2, 2.5), 12), 3); // Mithuna 2nd dwadasamsa → Kataka
  assert.equal(vargaRasi(at(0, 3), 10), 1); // Mesha 3° → 2nd dasamsa → Rishaba
});

test('Ashtakavarga BAV tables equal BPHS (spot cells) and totals', () => {
  // Spot cells cross-checked by hand against BPHS ch. 66–72 (Santhanam translation) / B.V. Raman.
  assert.deepEqual(AV_TABLES.Sun.Lagna, [3, 4, 6, 10, 11, 12]);
  assert.deepEqual(AV_TABLES.Moon.Mercury, [1, 3, 4, 5, 7, 8, 10, 11]);
  assert.deepEqual(AV_TABLES.Mars.Saturn, [1, 4, 7, 8, 9, 10, 11]);
  assert.deepEqual(AV_TABLES.Mercury.Venus, [1, 2, 3, 4, 5, 8, 9, 11]);
  assert.deepEqual(AV_TABLES.Jupiter.Lagna, [1, 2, 4, 5, 6, 7, 9, 10, 11]);
  assert.deepEqual(AV_TABLES.Venus.Moon, [1, 2, 3, 4, 5, 8, 9, 11, 12]);
  assert.deepEqual(AV_TABLES.Saturn.Mercury, [6, 8, 9, 10, 11, 12]);
  const totals = { Sun: 48, Moon: 49, Mars: 39, Mercury: 54, Jupiter: 56, Venus: 52, Saturn: 39 };
  for (const [p, n] of Object.entries(totals)) {
    const rows = Object.values(AV_TABLES[p]);
    assert.equal(rows.length, 8, `${p}: 7 grahas + Lagna contribute`);
    assert.equal(rows.reduce((s, a) => s + a.length, 0), n, p);
    for (const r of rows) assert.ok(r.every((h, i) => h >= 1 && h <= 12 && (i === 0 || h > r[i - 1])), `${p} sorted unique houses`);
  }
});

test('SAV total is 337 for any chart', () => {
  for (const b of [
    { date: '1943-06-01', time: '10:00', lat: 13.08, lon: 80.27, zone: 'Asia/Kolkata' },
    { date: '2001-09-09', time: '23:59', lat: 25.2, lon: 55.27, zone: 'Asia/Dubai' },
    { date: '1969-07-20', time: '20:17', lat: 40.7, lon: -74, zone: 'America/New_York' },
  ]) {
    const av = ashtakavarga(birthChart({ name: 'x', ...b }));
    assert.equal(av.total, 337);
    assert.equal(av.sav.length, 12);
  }
});
